######################################################################
# Automatically generated by qmake (2.01a) fr 19. jan 15:56:44 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
