######################################################################
# Automatically generated by qmake (2.01a) on 24. jan 10:08:34 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += spinboxtest.h
SOURCES += main.cpp spinboxtest.cpp
CONFIG += qtestlib console 
