######################################################################
# Automatically generated by qmake (2.01a) on 15. nov 19:10:54 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += xml 
CONFIG += console 
