// Dest.h : header file
//

/////////////////////////////////////////////////////////////////////////////
// CDest window

class CDest : public CSource
{
// Construction
public:
        CDest();
        
// Attributes
public:

// Operations
public:
// Overrides
        // ClassWizard generated virtual function overrides
        //{{AFX_VIRTUAL(CDest)
        //}}AFX_VIRTUAL

// Implementation
public:
        virtual ~CDest();

        // Generated message map functions
protected:
        //{{AFX_MSG(CDest)
        //}}AFX_MSG

        DECLARE_MESSAGE_MAP()
};

/////////////////////////////////////////////////////////////////////////////
