// Dest.cpp : implementation file
//

#include "stdafx.h"
#include "GDIExplorer.h"
#include "source.h"
#include "Dest.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

/////////////////////////////////////////////////////////////////////////////
// CDest

CDest::CDest()
{
}

CDest::~CDest()
{
}


BEGIN_MESSAGE_MAP(CDest, CSource)
        //{{AFX_MSG_MAP(CDest)
        //}}AFX_MSG_MAP
END_MESSAGE_MAP()

/////////////////////////////////////////////////////////////////////////////
// CDest message handlers


