Calculator: node_assign Class Reference
node_assign Class Reference
#include <node_impl.hpp>
Public Member Functions
node_assign (node identifier, node value)
node identifier () const
node value () const
Public Member Functions inherited from node_impl
node_impl ()
virtual ~node_impl ()
void print (std::ostream &stream, int indent) const
double evaluate () const
std::string to_string () const
Private Member Functions
std::string get_identifier () const
double evaluate_value () const
virtual void print_node (std::ostream &stream, int indent) const override
virtual double evaluate_node () const override
Private Attributes
node identifier_
node value_
Detailed Description
Assignment Keep track of an identifier and a value.
Definition at line 81 of file node_impl.hpp.
Constructor & Destructor Documentation
node_assign::node_assign (node identifier, node value)
Definition at line 117 of file node_impl.cpp.
 : node_impl{}, identifier_{identifier}, value_{value}
 {}
Member Function Documentation
double node_assign::evaluate_node () const override private virtual
Implements node_impl.
Definition at line 152 of file node_impl.cpp.
References evaluate_value(), get_identifier(), and set_variable().
 {
   double result( evaluate_value() );
   set_variable(get_identifier(), result);
   return result;
 }
double node_assign::evaluate_value () const private
Definition at line 139 of file node_impl.cpp.
References node::evaluate(), and value().
Referenced by evaluate_node().
 {
   return value().evaluate();
 }
std::string node_assign::get_identifier () const private
Definition at line 133 of file node_impl.cpp.
References identifier(), and node::to_string().
Referenced by evaluate_node(), and print_node().
 {
   return identifier().to_string();
 }
node node_assign::identifier () const
Definition at line 121 of file node_impl.cpp.
References identifier_.
Referenced by get_identifier().
 {
   return identifier_;
 }
void node_assign::print_node (std::ostream & stream, int indent) const override private virtual
Implements node_impl.
Definition at line 145 of file node_impl.cpp.
References get_identifier(), node::print(), and value().
 {
   stream << std::setw(indent) << "" << get_identifier() << ":=\n";
   value().print(stream, indent + 2);
 }
node node_assign::value () const
Definition at line 127 of file node_impl.cpp.
References value_.
Referenced by evaluate_value(), and print_node().
 {
   return value_;
 }
Member Data Documentation
node node_assign::identifier_ private
Definition at line 93 of file node_impl.hpp.
Referenced by identifier().
node node_assign::value_ private
Definition at line 94 of file node_impl.hpp.
Referenced by value().
The documentation for this class was generated from the following files:
node_impl.hpp
node_impl.cpp