Calculator: parse.cpp File Reference
parse.cpp File Reference
#include <sstream>
#include "node.hpp"
#include "parse.hpp"
Functions
void parse_loop (std::istream &input, std::ostream &output)
Function Documentation
void parse_loop (std::istream & input, std::ostream & output)
Parse loop. Read expressions from input and print results to output.
Parameters
input The input stream.
output The output stream.
Definition at line 272 of file parse.cpp.
References node::evaluate().
Referenced by BOOST_AUTO_TEST_CASE(), and main().
 {
   std::string line{};
   // No portable way to test whether the console is an interactive terminal
   // vs. a non-interactive file. If you have a system-specific way to test,
   // output the prompt only for the interactive case.
   for (output << "> "; std::getline(input, line); output << "> ") {
     std::istringstream input{std::move(line)};
     parser p{input};
     try {
       node n;
       while (p.get_expr(n))
         output << n.evaluate() << '\n';
     } catch(parse_error const& ex) {
       output << ex.what() << '\n';
     } catch(std::exception const& ex) {
       output << "exception: " << ex.what() << '\n';
     }
   }
 }