Calculator: test_parse.cpp File Reference
test_parse.cpp File Reference
#include <iostream>
#include <istream>
#include <ostream>
#include <sstream>
#include <string>
#include <boost/test/unit_test.hpp>
#include "parse.hpp"
Functions
BOOST_AUTO_TEST_SUITE (parser_test)
BOOST_AUTO_TEST_CASE (test_number)
BOOST_AUTO_TEST_CASE (test_negative)
BOOST_AUTO_TEST_CASE (test_add)
BOOST_AUTO_TEST_CASE (test_subtract)
BOOST_AUTO_TEST_CASE (test_multiply)
BOOST_AUTO_TEST_CASE (test_divide)
BOOST_AUTO_TEST_CASE (test_mix)
BOOST_AUTO_TEST_CASE (test_var)
BOOST_AUTO_TEST_CASE (test_predefined_vars)
BOOST_AUTO_TEST_CASE (test_error1)
BOOST_AUTO_TEST_CASE (test_error2)
BOOST_AUTO_TEST_CASE (test_error3)
BOOST_AUTO_TEST_CASE (test_error4)
BOOST_AUTO_TEST_SUITE_END ()
Function Documentation
BOOST_AUTO_TEST_CASE (test_number)
Definition at line 13 of file test_parse.cpp.
References parse_loop().
 {
   std::istringstream in("1\n3.14159\n1.23e45\n45.67e+8\n");
   std::ostringstream out;
   parse_loop(in, out);
   BOOST_CHECK_EQUAL("> 1\n> 3.14159\n> 1.23e+45\n> 4.567e+09\n> ", out.str());
 }
BOOST_AUTO_TEST_CASE (test_negative)
Definition at line 21 of file test_parse.cpp.
References parse_loop().
 {
   std::istringstream in("-1\n-3.14159\n-1.23e-45\n-34.56e-7\n");
   std::ostringstream out;
   parse_loop(in, out);
   BOOST_CHECK_EQUAL("> -1\n> -3.14159\n> -1.23e-45\n> -3.456e-06\n> ", out.str());
 }
BOOST_AUTO_TEST_CASE (test_add)
Definition at line 29 of file test_parse.cpp.
References parse_loop().
 {
   std::istringstream in("1 + 2\n1 + 2 + 3");
   std::ostringstream out;
   parse_loop(in, out);
   BOOST_CHECK_EQUAL("> 3\n> 6\n> ", out.str());
 }
BOOST_AUTO_TEST_CASE (test_subtract)
Definition at line 37 of file test_parse.cpp.
References parse_loop().
 {
   std::istringstream in("1 - 2\n5 - 1 - 2");
   std::ostringstream out;
   parse_loop(in, out);
   BOOST_CHECK_EQUAL("> -1\n> 2\n> ", out.str());
 }
BOOST_AUTO_TEST_CASE (test_multiply)
Definition at line 45 of file test_parse.cpp.
References parse_loop().
 {
   std::istringstream in("1 * 2\n5 * 2 * 1.5");
   std::ostringstream out;
   parse_loop(in, out);
   BOOST_CHECK_EQUAL("> 2\n> 15\n> ", out.str());
 }
BOOST_AUTO_TEST_CASE (test_divide)
Definition at line 53 of file test_parse.cpp.
References parse_loop().
 {
   std::istringstream in("1 / 2\n10 / 2 / 2");
   std::ostringstream out;
   parse_loop(in, out);
   BOOST_CHECK_EQUAL("> 0.5\n> 2.5\n> ", out.str());
 }
BOOST_AUTO_TEST_CASE (test_mix)
Definition at line 61 of file test_parse.cpp.
References parse_loop().
 {
   std::istringstream in(" 1.5 * 2 + 3 / 1.5 - (10 - 3) + 2 * -1");
   std::ostringstream out;
   parse_loop(in, out);
   BOOST_CHECK_EQUAL("> -4\n> ", out.str());
 }
BOOST_AUTO_TEST_CASE (test_var)
Definition at line 69 of file test_parse.cpp.
References parse_loop().
 {
   std::istringstream in(" var half = 1 / 2\nvar one=1.0\n one + half");
   std::ostringstream out;
   parse_loop(in, out);
   BOOST_CHECK_EQUAL("> 0.5\n> 1\n> 1.5\n> ", out.str());
 }
BOOST_AUTO_TEST_CASE (test_predefined_vars)
Definition at line 77 of file test_parse.cpp.
References parse_loop().
 {
   std::istringstream in(" pi - e");
   std::ostringstream out;
   parse_loop(in, out);
   BOOST_CHECK_EQUAL("> 0.423311\n> ", out.str());
 }
BOOST_AUTO_TEST_CASE (test_error1)
Definition at line 85 of file test_parse.cpp.
References parse_loop().
 {
   std::istringstream in("1+++2");
   std::ostringstream out;
   parse_loop(in, out);
   BOOST_CHECK_EQUAL("> syntax error: expected a primary, but got +\n> ", out.str());
 }
BOOST_AUTO_TEST_CASE (test_error2)
Definition at line 93 of file test_parse.cpp.
References parse_loop().
 {
   std::istringstream in("1..2");
   std::ostringstream out;
   parse_loop(in, out);
   BOOST_CHECK_EQUAL("> syntax error: expected digit after decimal point, got '.'\n> ", out.str());
 }
BOOST_AUTO_TEST_CASE (test_error3)
Definition at line 101 of file test_parse.cpp.
References parse_loop().
 {
   std::istringstream in("1 @ 2");
   std::ostringstream out;
   parse_loop(in, out);
   BOOST_CHECK_EQUAL("> syntax error: expected digit, got '@'\n> ", out.str());
 }
BOOST_AUTO_TEST_CASE (test_error4)
Definition at line 109 of file test_parse.cpp.
References parse_loop().
 {
   std::istringstream in("(1 + 2");
   std::ostringstream out;
   parse_loop(in, out);
   BOOST_CHECK_EQUAL("> syntax error: EOF when expecting ')'\n> ", out.str());
 }
BOOST_AUTO_TEST_SUITE (parser_test)
BOOST_AUTO_TEST_SUITE_END ()