######################################################################
# Automatically generated by qmake (2.01a) ti 2. jan 15:57:02 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += textandnumber.h textdevice.h textthread.h
SOURCES += main.cpp textandnumber.cpp textdevice.cpp textthread.cpp
CONFIG += console 
