######################################################################
# Automatically generated by qmake (2.01a) fr 16. mar 19:54:14 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += sender.h
SOURCES += main.cpp sender.cpp
QT += network 
CONFIG += console 
