######################################################################
# Automatically generated by qmake (2.01a) ti 12. sep 16:50:44 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += buttonbox.h
SOURCES += buttonbox.cpp main.cpp
