/*----------------------------------------------------
    RSRC.H    Resource IDs for STEPPER
  ----------------------------------------------------*/
#define IDI_APPICON         10
#define IDA_ACCELERATORS    10
#define IDM_APPMENU         10  
#define CMD_QUIT            100   /* File menu */
#define CMD_ABOUT           110
#define CMD_KILL            200   /* Process menu */
#define CMD_RESTART         210
#define CMD_SETBREAK        300   /* Run menu */
#define CMD_SETALLBREAKS    310
#define CMD_CLEARALLBREAKS  320
#define CMD_RUNTOCURSOR     330
#define CMD_RUN             340

