######################################################################
# Automatically generated by qmake (2.01a) ti 2. jan 10:03:03 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
CONFIG += console 
