######################################################################
# Automatically generated by qmake (2.01a) fr 17. nov 14:45:07 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
CONFIG += console 
