//
// MATLAB Compiler: 3.0
// Date: Tue Oct 13 19:22:00 2009
// Arguments: "-B" "macro_default" "-O" "all" "-O" "fold_scalar_mxarrays:on" "-O" "fold_non_scalar_mxarrays:on" "-O" "optimize_integer_for_loops:on" "-O" "array_indexing:on" "-O" "optimize_conditionals:on" "-B" "C:\Documents and Settings\Administrator\Application Data\MathWorks\MATLAB\R13\mccpath" "-I" "D:\MATLAB6p5\toolbox\matlab\general" "-I" "D:\MATLAB6p5\toolbox\matlab\ops" "-I" "D:\MATLAB6p5\toolbox\matlab\lang" "-I" "D:\MATLAB6p5\toolbox\matlab\elmat" "-I" "D:\MATLAB6p5\toolbox\matlab\elfun" "-I" "D:\MATLAB6p5\toolbox\matlab\specfun" "-I" "D:\MATLAB6p5\toolbox\matlab\matfun" "-I" "D:\MATLAB6p5\toolbox\matlab\datafun" "-I" "D:\MATLAB6p5\toolbox\matlab\audio" "-I" "D:\MATLAB6p5\toolbox\matlab\polyfun" "-I" "D:\MATLAB6p5\toolbox\matlab\funfun" "-I" "D:\MATLAB6p5\toolbox\matlab\sparfun" "-I" "D:\MATLAB6p5\toolbox\matlab\graph2d" "-I" "D:\MATLAB6p5\toolbox\matlab\graph3d" "-I" "D:\MATLAB6p5\toolbox\matlab\specgraph" "-I" "D:\MATLAB6p5\toolbox\matlab\graphics" "-I" "D:\MATLAB6p5\toolbox\matlab\uitools" "-I" "D:\MATLAB6p5\toolbox\matlab\strfun" "-I" "D:\MATLAB6p5\toolbox\matlab\iofun" "-I" "D:\MATLAB6p5\toolbox\matlab\timefun" "-I" "D:\MATLAB6p5\toolbox\matlab\datatypes" "-I" "D:\MATLAB6p5\toolbox\matlab\verctrl" "-I" "D:\MATLAB6p5\toolbox\matlab\winfun" "-I" "D:\MATLAB6p5\toolbox\matlab\winfun\comcli" "-I" "D:\MATLAB6p5\toolbox\matlab\demos" "-I" "D:\MATLAB6p5\toolbox\local" "-I" "D:\MATLAB6p5\toolbox\simulink\simulink" "-I" "D:\MATLAB6p5\toolbox\simulink\blocks" "-I" "D:\MATLAB6p5\toolbox\simulink\components" "-I" "D:\MATLAB6p5\toolbox\simulink\fixedandfloat" "-I" "D:\MATLAB6p5\toolbox\simulink\fixedandfloat\fxpdemos" "-I" "D:\MATLAB6p5\toolbox\simulink\fixedandfloat\obsolete" "-I" "D:\MATLAB6p5\toolbox\simulink\simdemos" "-I" "D:\MATLAB6p5\toolbox\simulink\simdemos\aerospace" "-I" "D:\MATLAB6p5\toolbox\simulink\simdemos\automotive" "-I" "D:\MATLAB6p5\toolbox\simulink\simdemos\simfeatures" "-I" "D:\MATLAB6p5\toolbox\simulink\simdemos\simgeneral" "-I" "D:\MATLAB6p5\toolbox\simulink\simdemos\simnew" "-I"
// "D:\MATLAB6p5\toolbox\simulink\dee" "-I" "D:\MATLAB6p5\toolbox\simulink\dastudio" "-I" "D:\MATLAB6p5\toolbox\stateflow\stateflow" "-I" "D:\MATLAB6p5\toolbox\stateflow\sfdemos" "-I" "D:\MATLAB6p5\toolbox\stateflow\coder" "-I" "D:\MATLAB6p5\toolbox\rtw\rtw" "-I" "D:\MATLAB6p5\toolbox\rtw\rtwdemos" "-I" "D:\MATLAB6p5\toolbox\rtw\rtwdemos\rsimdemos" "-I" "D:\MATLAB6p5\toolbox\rtw\targets\asap2\asap2" "-I" "D:\MATLAB6p5\toolbox\rtw\targets\asap2\asap2\user" "-I" "D:\MATLAB6p5\toolbox\rtw\targets\rtwin\rtwin" "-I" "D:\MATLAB6p5\toolbox\aeroblks\aeroblks" "-I" "D:\MATLAB6p5\toolbox\aeroblks\aerodemos" "-I" "D:\MATLAB6p5\toolbox\ccslink\ccslink" "-I" "D:\MATLAB6p5\toolbox\ccslink\ccsdemos" "-I" "D:\MATLAB6p5\toolbox\ccslink\rtdxblks" "-I" "D:\MATLAB6p5\toolbox\cdma\cdma" "-I" "D:\MATLAB6p5\toolbox\cdma\cdmamasks" "-I" "D:\MATLAB6p5\toolbox\cdma\cdmamex" "-I" "D:\MATLAB6p5\toolbox\cdma\cdmademos" "-I" "D:\MATLAB6p5\toolbox\combuilder\combuilder" "-I" "D:\MATLAB6p5\toolbox\comm\comm" "-I" "D:\MATLAB6p5\toolbox\comm\commdemos" "-I" "D:\MATLAB6p5\toolbox\comm\commobsolete" "-I" "D:\MATLAB6p5\toolbox\commblks\commblks" "-I" "D:\MATLAB6p5\toolbox\commblks\commmasks" "-I" "D:\MATLAB6p5\toolbox\commblks\commmex" "-I" "D:\MATLAB6p5\toolbox\commblks\commblksdemos" "-I" "D:\MATLAB6p5\toolbox\commblks\commblksobsolete\commblksobsolete" "-I" "D:\MATLAB6p5\toolbox\compiler" "-I" "D:\MATLAB6p5\toolbox\control\control" "-I" "D:\MATLAB6p5\toolbox\control\ctrlguis" "-I" "D:\MATLAB6p5\toolbox\control\ctrlobsolete" "-I" "D:\MATLAB6p5\toolbox\control\ctrlutil" "-I" "D:\MATLAB6p5\toolbox\control\ctrldemos" "-I" "D:\MATLAB6p5\toolbox\curvefit\curvefit" "-I" "D:\MATLAB6p5\toolbox\curvefit\cftoolgui" "-I" "D:\MATLAB6p5\toolbox\daq\daq" "-I" "D:\MATLAB6p5\toolbox\daq\daqguis" "-I" "D:\MATLAB6p5\toolbox\daq\daqdemos" "-I" "D:\MATLAB6p5\toolbox\database\database" "-I" "D:\MATLAB6p5\toolbox\database\dbdemos" "-I" "D:\MATLAB6p5\toolbox\database\vqb" "-I" "D:\MATLAB6p5\toolbox\datafeed\datafeed" "-I" "D:\MATLAB6p5\toolbox\datafeed\dfgui" "-I"
// "D:\MATLAB6p5\toolbox\dials" "-I" "D:\MATLAB6p5\toolbox\dspblks\dspblks" "-I" "D:\MATLAB6p5\toolbox\dspblks\dspmasks" "-I" "D:\MATLAB6p5\toolbox\dspblks\dspmex" "-I" "D:\MATLAB6p5\toolbox\dspblks\dspdemos" "-I" "D:\MATLAB6p5\toolbox\rtw\targets\ecoder" "-I" "D:\MATLAB6p5\toolbox\rtw\targets\ecoder\ecoderdemos" "-I" "D:\MATLAB6p5\toolbox\exlink" "-I" "D:\MATLAB6p5\toolbox\filterdesign\filterdesign" "-I" "D:\MATLAB6p5\toolbox\filterdesign\quantization" "-I" "D:\MATLAB6p5\toolbox\filterdesign\filtdesdemos" "-I" "D:\MATLAB6p5\toolbox\finance\finance" "-I" "D:\MATLAB6p5\toolbox\finance\calendar" "-I" "D:\MATLAB6p5\toolbox\finance\findemos" "-I" "D:\MATLAB6p5\toolbox\finance\finsupport" "-I" "D:\MATLAB6p5\toolbox\finderiv\finderiv" "-I" "D:\MATLAB6p5\toolbox\fixpoint" "-I" "D:\MATLAB6p5\toolbox\ftseries\ftseries" "-I" "D:\MATLAB6p5\toolbox\ftseries\ftsdemos" "-I" "D:\MATLAB6p5\toolbox\ftseries\ftsdata" "-I" "D:\MATLAB6p5\toolbox\ftseries\ftstutorials" "-I" "D:\MATLAB6p5\toolbox\fuzzy\fuzzy" "-I" "D:\MATLAB6p5\toolbox\fuzzy\fuzdemos" "-I" "D:\MATLAB6p5\toolbox\garch\garch" "-I" "D:\MATLAB6p5\toolbox\garch\garchdemos" "-I" "D:\MATLAB6p5\toolbox\ident\ident" "-I" "D:\MATLAB6p5\toolbox\ident\idobsolete" "-I" "D:\MATLAB6p5\toolbox\ident\idguis" "-I" "D:\MATLAB6p5\toolbox\ident\idutils" "-I" "D:\MATLAB6p5\toolbox\ident\iddemos" "-I" "D:\MATLAB6p5\toolbox\ident\idhelp" "-I" "D:\MATLAB6p5\toolbox\images\images" "-I" "D:\MATLAB6p5\toolbox\images\imdemos" "-I" "D:\MATLAB6p5\toolbox\instrument\instrument" "-I" "D:\MATLAB6p5\toolbox\instrument\instrumentdemos" "-I" "D:\MATLAB6p5\toolbox\lmi\lmictrl" "-I" "D:\MATLAB6p5\toolbox\lmi\lmilab" "-I" "D:\MATLAB6p5\toolbox\map\map" "-I" "D:\MATLAB6p5\toolbox\map\mapdisp" "-I" "D:\MATLAB6p5\toolbox\map\mapproj" "-I" "D:\MATLAB6p5\toolbox\matlabxl\matlabxl" "-I" "D:\MATLAB6p5\toolbox\mbc\mbc" "-I" "D:\MATLAB6p5\toolbox\mbc\mbcdata" "-I" "D:\MATLAB6p5\toolbox\mbc\mbcdesign" "-I" "D:\MATLAB6p5\toolbox\mbc\mbcexpr" "-I" "D:\MATLAB6p5\toolbox\mbc\mbcguitools" "-I"
// "D:\MATLAB6p5\toolbox\mbc\mbclayouts" "-I" "D:\MATLAB6p5\toolbox\mbc\mbcmodels" "-I" "D:\MATLAB6p5\toolbox\mbc\mbcsimulink" "-I" "D:\MATLAB6p5\toolbox\mbc\mbctools" "-I" "D:\MATLAB6p5\toolbox\mbc\mbcview" "-I" "D:\MATLAB6p5\toolbox\physmod\mech\mech" "-I" "D:\MATLAB6p5\toolbox\physmod\mech\mechdemos" "-I" "D:\MATLAB6p5\toolbox\mpc\mpccmds" "-I" "D:\MATLAB6p5\toolbox\mpc\mpcdemos" "-I" "D:\MATLAB6p5\toolbox\rtw\targets\mpc555dk\mpc555dk" "-I" "D:\MATLAB6p5\toolbox\rtw\targets\mpc555dk\common\canlib\blockset" "-I" "D:\MATLAB6p5\toolbox\rtw\targets\mpc555dk\common\canlib\blockset\mfiles" "-I" "D:\MATLAB6p5\toolbox\rtw\targets\mpc555dk\common\vectorlib\blockset" "-I" "D:\MATLAB6p5\toolbox\rtw\targets\mpc555dk\common\vectorlib\blockset\mfiles" "-I" "D:\MATLAB6p5\toolbox\rtw\targets\mpc555dk\common\configuration" "-I" "D:\MATLAB6p5\toolbox\rtw\targets\mpc555dk\pil" "-I" "D:\MATLAB6p5\toolbox\rtw\targets\mpc555dk\rt\blockset" "-I" "D:\MATLAB6p5\toolbox\rtw\targets\mpc555dk\rt\blockset\mfiles" "-I" "D:\MATLAB6p5\toolbox\rtw\targets\mpc555dk\rt\blockset\mfiles\SimulinkUtilities" "-I" "D:\MATLAB6p5\toolbox\rtw\targets\mpc555dk\mpc555demos" "-I" "D:\MATLAB6p5\toolbox\mutools\commands" "-I" "D:\MATLAB6p5\toolbox\mutools\subs" "-I" "D:\MATLAB6p5\toolbox\ncd" "-I" "D:\MATLAB6p5\toolbox\nnet\nnet" "-I" "D:\MATLAB6p5\toolbox\nnet\nnutils" "-I" "D:\MATLAB6p5\toolbox\nnet\nncontrol" "-I" "D:\MATLAB6p5\toolbox\nnet\nndemos" "-I" "D:\MATLAB6p5\toolbox\nnet\nnobsolete" "-I" "D:\MATLAB6p5\toolbox\optim" "-I" "D:\MATLAB6p5\toolbox\pde" "-I" "D:\MATLAB6p5\toolbox\simulink\perftools" "-I" "D:\MATLAB6p5\toolbox\simulink\mdldiff" "-I" "D:\MATLAB6p5\toolbox\simulink\simcoverage" "-I" "D:\MATLAB6p5\toolbox\rtw\accel" "-I" "D:\MATLAB6p5\toolbox\powersys\powersys" "-I" "D:\MATLAB6p5\toolbox\powersys\powerdemo" "-I" "D:\MATLAB6p5\toolbox\reqmgt" "-I" "D:\MATLAB6p5\toolbox\robust" "-I" "D:\MATLAB6p5\toolbox\rptgen" "-I" "D:\MATLAB6p5\toolbox\rptgenext" "-I" "D:\MATLAB6p5\toolbox\runtime" "-I" "D:\MATLAB6p5\toolbox\sb2sl" "-I"
// "D:\MATLAB6p5\toolbox\signal\signal" "-I" "D:\MATLAB6p5\toolbox\signal\sigtools" "-I" "D:\MATLAB6p5\toolbox\signal\sptoolgui" "-I" "D:\MATLAB6p5\toolbox\signal\sigdemos" "-I" "D:\MATLAB6p5\toolbox\splines" "-I" "D:\MATLAB6p5\toolbox\stats" "-I" "D:\MATLAB6p5\toolbox\symbolic" "-I" "D:\MATLAB6p5\toolbox\rtw\targets\tic6000\tic6000" "-I" "D:\MATLAB6p5\toolbox\rtw\targets\tic6000\blks" "-I" "D:\MATLAB6p5\toolbox\vr\vr" "-I" "D:\MATLAB6p5\toolbox\vr\vrdemos" "-I" "D:\MATLAB6p5\toolbox\wavelet\wavelet" "-I" "D:\MATLAB6p5\toolbox\wavelet\wavedemo" "-I" "D:\MATLAB6p5\toolbox\webserver\webserver" "-I" "D:\MATLAB6p5\toolbox\webserver\wsdemos" "-I" "D:\MATLAB6p5\toolbox\rtw\targets\xpc\xpc" "-I" "D:\MATLAB6p5\toolbox\rtw\targets\xpc\target\build\xpcblocks" "-I" "D:\MATLAB6p5\toolbox\rtw\targets\xpc\xpcdemos" "-I" "D:\MATLAB6p5\toolbox\rtw\targets\xpc\target\kernel\embedded" "-I" "D:\MATLAB6p5\work" "-L" "Cpp" "libmmfile.mlib" "-A" "line:on" "-G" "-A" "debugline:on" "-O" "fold_scalar_mxarrays:off" "-O" "fold_non_scalar_mxarrays:off" "-O" "optimize_integer_for_loops:off" "-O" "array_indexing:off" "-O" "optimize_conditionals:off" "-O" "speculate:off" "libmmfile.mlib" "-v" "-I" "D:\VC2005\Exp_13_3_4" "-I" "D:\VC2005\Exp_13_3_4" "-t" "-T" "codegen" "D:\VC2005\Exp_13_3_4\mymagic.m" 
//
#ifndef __mymagic_hpp
#define __mymagic_hpp 1

#include "libmatlb.hpp"

extern void InitializeModule_mymagic();
extern void TerminateModule_mymagic();
extern _mexLocalFunctionTable _local_function_table_mymagic;

extern mwArray mymagic(mwArray n = mwArray::DIN);
#ifdef __cplusplus
extern "C"
#endif
void mlxMymagic(int nlhs, mxArray * plhs[], int nrhs, mxArray * prhs[]);

#endif
