######################################################################
# Automatically generated by qmake (2.01a) to 1. feb 13:50:49 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += server.h serverthread.h
SOURCES += main.cpp server.cpp serverthread.cpp
QT += network 
QT -= ui 
CONFIG += console
