######################################################################
# Automatically generated by qmake (2.01a) ti 2. jan 14:31:10 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += textdevice.h textthread.h
SOURCES += main.cpp textdevice.cpp textthread.cpp
CONFIG += console 
