######################################################################
# Automatically generated by qmake (2.01a) on 6. dec 17:48:46 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dyndialog.h
SOURCES += dyndialog.cpp main.cpp
TRANSLATIONS += swedish.ts english.ts
CONFIG += console 
