//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DSplit.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_DSPLITTYPE                  129
#define IDD_DIALOG1                     130
#define IDD_DIALOG2                     131
#define IDD_DIALOG_Pingyi               132
#define IDD_DIALOG_Suofang              133
#define IDD_DIALOG_XuanZhuan            134
#define IDC_EDIT_XMOVE                  1000
#define IDC_EDIT_YMOVE                  1001
#define IDC_EDIT_XZoom                  1002
#define IDC_EDIT_YZoom                  1003
#define IDC_EDIT_Rotate                 1004
#define ID_DYNSPLIT                     32771
#define ID_hhhh                         32772
#define ID_F0Q1                         32773
#define ID_FILEOPEN                     32774
#define ID_YUANTU                       32775
#define ID_FILESAVE                     32776
#define ID_Tuxiangpingyi                32778
#define ID_Shuipingjingxiang            32779
#define ID_Chuizhijingxiang             32780
#define ID_Zhuanzhi                     32781
#define ID_Suofang                      32782
#define ID_SuoXiao                      32782
#define ID_Xuanzhuan                    32783
#define ID_Fangda                       32784

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
