######################################################################
# Automatically generated by qmake (2.01a) sö 3. dec 19:31:19 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
TRANSLATIONS += noop_sv_SE.ts 
CONFIG += console 
