//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SynchronizationExplorer.rc
//
#define IDD_ABOUTBOX                    100
#define IDS_PLATFORM_WIN32_NT           110
#define IDS_PLATFORM_WIN32_NTAS         111
#define IDS_PLATFORM_WIN32_NTW          112
#define IDS_PLATFORM_WIN32_NTS          113
#define IDS_PLATFORM_WIN32s             114
#define IDS_PLATFORM_WIN32_WINDOWS      115
#define IDS_PLATFORM_UNKNOWN            116
#define IDS_PLATFORM_WIN32_NT2          117
#define IDS_PLATFORM_WIN32_NTAS2        118
#define IDS_PLATFORM_WIN32_NTW2         119
#define IDS_PROCESSOR_ARCHITECTURE_UNKNOWN 120
#define IDS_PROCESSOR_ARCHITECTURE_INTEL_386_486 121
#define IDS_PROCESSOR_ARCHITECTURE_INTEL_PENTIUM 122
#define IDS_PROCESSOR_ARCHITECTURE_ALPHA 123
#define IDS_PROCESSOR_ARCHITECTURE_MIPS 124
#define IDS_PROCESSOR_ARCHITECTURE_PPC  125
#define IDS_PROCESSOR_LEVEL_INTEL_UNKNOWN 126
#define IDS_PROCESSOR_LEVEL_ALPHA_UNKNOWN 127
#define IDR_MAINFRAME                   128
#define IDR_SYNCHRTYPE                  129
#define IDD_TASK                        130
#define IDR_PANEL                       130
#define IDD_CONTROL                     131
#define IDI_JMNCO                       140
#define IDS_PROCESSOR_LEVEL_MIPS_UNKNOWN 143
#define IDS_PROCESSOR_LEVEL_PPC_UNKNOWN 144
#define IDS_PROCESSOR_NOREV_INTEL_386   145
#define IDS_PROCESSOR_NOREV_INTEL_486   146
#define IDS_PROCESSOR_NOREV_INTEL_PENTIUM 147
#define IDS_PROCESSOR_NOREV_MIPS_R4000  148
#define IDS_PROCESSOR_NOREV_ALPHA_21064 149
#define IDS_STEP                        150
#define IDS_STOP                        151
#define IDS_RUN                         152
#define IDC_LOCK                        1000
#define IDC_FETCH                       1001
#define IDC_INCREMENT                   1002
#define IDC_STORE                       1003
#define IDC_ABOUT_OSVERSION             1004
#define IDC_UNLOCK                      1004
#define IDC_INTERATIONS                 1005
#define IDC_ABOUT_PROCESSORVERSION      1006
#define IDC_N                           1006
#define IDC_ACTUAL                      1007
#define IDC_STEP                        1007
#define IDC_ABOUT_FILEDESCRIPTION       1008
#define IDC_SPEED                       1008
#define IDC_RUNSTOP                     1008
#define IDC_ABOUT_VERSION               1009
#define IDC_ABOUT_LEGALCOPYRIGHT        1010
#define IDC_LOCKING                     1010
#define IDC_ABOUT_LEGALTRADEMARKS       1011
#define IDC_RANDOM                      1011
#define IDC_ABOUT_COMMENTS              1012
#define IDC_ERRORBAR                    1012
#define IDC_SPEED_DISPLAY               1013
#define IDC_SYNCHRONOUS                 1014
#define IDC_SPIN_PRIORITY               1014
#define IDC_PRIORITY                    1016

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
