######################################################################
# Automatically generated by qmake (2.01a) ti 23. jan 15:22:12 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imagecollection.h imagecollectiontest.h
SOURCES += imagecollection.cpp imagecollectiontest.cpp main.cpp
CONFIG += qtestlib console
QT += sql
