######################################################################
# Automatically generated by qmake (2.00a) fr 11. aug 14:12:41 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myclass.h
SOURCES += myclass.cpp sig-slot.cpp
CONFIG += console 
