//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ImageProcessing.rc
//
#define IDDECODING                      3
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_IMAGEPTYPE                  129
#define IDD_DLG_SHOW_HISTOGRAM          130
#define IDD_DLG_ENHANCE_SMOOTH          131
#define IDD_DLG_ENHANCE_MEDIAN          132
#define IDD_DLG_ENHANCE_COLOR           133
#define IDD_DLG_ENHANCE_LINTRANS        134
#define IDD_DLG_REG                     135
#define IDD_DLG_AFTREG                  136
#define IDD_DLG_RECOG_MATCH             137
#define IDD_CODING_HUFFMAN              138
#define IDD_CODING_SHANFINO             139
#define IDD_CODING_BITPLANE             140
#define IDD_CODING_ARITH                141
#define IDC_DLG_HIST_SHOW               1001
#define IDC_BIT                         1001
#define IDC_RADIO_AVERTEM               1002
#define IDC_RADIO_GUASSTEM              1003
#define IDCODING                        1003
#define IDC_RADIO_SELFTEM               1004
#define IDC_EDIT_SELFTEM_COEF           1005
#define IDC_EDIT_SELFTEM_HEIGHT         1006
#define IDC_EDIT_SELFTEM_WIDTH          1007
#define IDC_EDIT_SELFTEM_CEN_X          1008
#define IDC_EDIT_SELFTEM_CEN_Y          1009
#define IDC_EDIT_SELFTEM_EL0            1011
#define IDC_EDIT_SELFTEM_EL1            1012
#define IDC_RADIO_MEDIAN_VERTICAL       1012
#define IDC_EDIT_SELFTEM_EL2            1013
#define IDC_RADIO_MEDIAN_HORIZON        1013
#define IDC_EDIT_SELFTEM_EL3            1014
#define IDC_RADIO_MEDIAN_2DIMEN         1014
#define IDC_EDIT_SELFTEM_EL4            1015
#define IDC_RADIO_MEDIAN_SELFDEF        1015
#define IDC_EDIT_SELFTEM_EL5            1016
#define IDC_EDIT_MEDIAN_FILH            1016
#define IDC_EDIT_SELFTEM_EL6            1017
#define IDC_EDIT_MEDIAN_FILW            1017
#define IDC_LIST_ENH_COLOR              1017
#define IDC_EDIT_SELFTEM_EL7            1018
#define IDC_EDIT_MEDIAN_FILCENX         1018
#define IDC_EDIT_LINTRANS_X1            1018
#define IDC_EDIT_SELFTEM_EL8            1019
#define IDC_EDIT_MEDIAN_FILCENY         1019
#define IDC_EDIT_SELFTEM_EL9            1020
#define IDC_EDIT_SELFTEM_EL10           1021
#define IDC_EDIT_SELFTEM_EL11           1022
#define IDC_LST_Table                   1022
#define IDC_EDIT_SELFTEM_EL12           1023
#define IDC_EDIT_LINTRANS_Y1            1023
#define IDC_STATIC1                     1023
#define IDC_EDIT_SELFTEM_EL13           1024
#define IDC_EDIT_LINTRANS_X2            1024
#define IDC_STATIC2                     1024
#define IDC_EDIT_SELFTEM_EL14           1025
#define IDC_EDIT_LINTRANS_Y2            1025
#define IDC_STATIC3                     1025
#define IDC_EDIT_SELFTEM_EL15           1026
#define IDC_LINTRANS_SHOWCOR            1026
#define IDC_EDIT1                       1026
#define IDC_EDIT_SELFTEM_EL16           1027
#define IDC_REG_INIT_IMAGE              1027
#define IDC_EDIT2                       1027
#define IDC_EDIT_SELFTEM_EL17           1028
#define IDC_REG_RESLT_IMAGE             1028
#define IDC_EDIT3                       1028
#define IDC_EDIT_SELFTEM_EL18           1029
#define IDC_REG_OPEN                    1029
#define IDC_EDIT4                       1029
#define IDC_EDIT_SELFTEM_EL19           1030
#define IDC_REG_CHOSE_FEATURE           1030
#define IDC_AFTREG_IMAGE                1030
#define IDC_EDIT_SELFTEM_EL20           1031
#define IDC_REG_REG                     1031
#define IDC_RECOG_INIIMAGE              1031
#define IDC_EDIT_SELFTEM_EL21           1032
#define IDC_RECOG_MODIMAGE              1032
#define IDC_EDIT_SELFTEM_EL22           1033
#define IDC_RECOG_RESLTIMAGE            1033
#define IDC_EDIT_SELFTEM_EL23           1034
#define IDC_RECOG_OPEN_MODEL            1034
#define IDC_EDIT_SELFTEM_EL24           1035
#define IDC_RECOG_MATCH                 1035
#define ID_REGIONSEG_FIX                32772
#define ID_ROBERTS_OPERATOR             32773
#define ID_REAL_DFT                     32774
#define ID_FFT_1D                       32775
#define ID_FFT_2D                       32776
#define ID_EDGE_TRACK                   32777
#define ID_REGION_GROW                  32778
#define ID_ADA_REGION_SEG               32779
#define ID_LAPLACE_OPERATOR             32780
#define ID_DFT                          32781
#define ID_DFT_2D                       32782
#define ID_FILE_RELOAD                  32784
#define ID_VIEW_HISTOGRAM               32785
#define ID_ENHANCE_SMOOTH               32786
#define ID_ENHANCE_MEDIAN               32787
#define ID_ENHANCE_SMOOTH_FR            32788
#define ID_ENHANCE_PSEUDCOLOR           32789
#define ID_TRANS_DWT                    32790
#define ID_TRANS_IDWT                   32791
#define IDC_ENHANCE_LINTRANS            32793
#define IDC_ENHANCE_EQUHIST             32794
#define IDC_ENHANCE_HISTEQU             32795
#define IDC_ENHANCE_SHARP               32796
#define IDC_ENHANCE_BUTT_LOW            32797
#define IDC_ENHANCE_BUTT_HIGHT          32798
#define IDC_ENHANCE_SHARP_FREQ          32799
#define ID_REG_REG                      32800
#define ID_MENUITEM32801                32801
#define ID_EDGE_ROBERTS                 32802
#define ID_EDGE_SOBEL                   32803
#define ID_EDGE_PREWITT                 32804
#define ID_EDGE_LAPLACE                 32805
#define ID_EDGE_CANNY                   32806
#define ID_MOTION_BACKGROUND            32807
#define ID_RECOG_MATCH                  32808
#define ID_DEGENERATION_INVERSE         32809
#define ID_RESTORE_INVERSE              32810
#define ID_DEGENERATION_MOTION          32811
#define ID_RESTORE_MOTION               32812
#define ID_DEGENERATION_Winner          32813
#define ID_RESTORE_WINNER               32814
#define ID_MOMENT                       32815
#define ID_BARYCENTERMOMENT             32816
#define ID_ANALYSIS_HOLENUM             32817
#define ID_STREET_TRANSFORM             32818
#define ID_STREET_FRAMEWORK             32819
#define ID_FRAME_RESTORE                32820
#define ID_OUTLINE                      32821
#define ID_TRACE                        32822
#define ID_CODING_HUFFMAN               32823
#define ID_CODING_SHANFINO              32824
#define ID_CODING_ARITH                 32825
#define ID_CODING_WRITEIMG              32826
#define ID_CODING_LOADIMG               32827
#define ID_CODING_BITPLANE              32828
#define ID_VIEW_BAYER                   32829
#define ID_VIEW_FloydSteinberg          32830
#define ID_FREQ_DCT                     32831
#define ID_FREQ_WALSH                   32832
#define ID_FREQ_HOTELLING               32833

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32834
#define _APS_NEXT_CONTROL_VALUE         1036
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
