######################################################################
# Automatically generated by qmake (2.01a) Sat Jun 2 15:02:51 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += handleitem.h
SOURCES += handleitem.cpp main.cpp
CONFIG += console 
