//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ADOSampClient.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ADOSAMPCLIENT_DIALOG        102
#define IDR_MAINFRAME                   128
#define IDC_ACCOUNT                     1000
#define IDC_AMOUNT                      1001
#define IDC_DEBIT                       1002
#define IDC_CREDIT                      1003
#define ID_POST                         1004

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
    #define _APS_NEXT_RESOURCE_VALUE        129
    #define _APS_NEXT_COMMAND_VALUE         32771
    #define _APS_NEXT_CONTROL_VALUE         1005
    #define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
