//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WebQuery.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_WEBQUERY_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDC_EDIT_HOST                   1000
#define IDC_RADIO_TYPE		            1001
#define IDC_RADIO_FTP                   1002
#define IDC_LIST_FILE                   1006
#define IDC_STATIC_NAME                 1007
#define IDC_EDIT_NAME                   1008
#define IDC_STATIC_PWD                  1009
#define IDC_EDIT_PWD                    1010
#define IDC_RADIO_GOPHER                1011

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1012
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
