//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by timesheet.rc
//
#define IDS_FORMX                       1
#define IDB_FORMX                       1
#define IDS_FORMX_PPG                   2
#define IDS_FORMX_PPG_CAPTION           200
#define IDD_PROPPAGE_FORMX              200
#define IDC_MYMSFLEXGRID                202
#define IDD_FORMX                       203
#define IDC_TEXT_INPUT                  204

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
    #define _APS_NEXT_RESOURCE_VALUE        205
    #define _APS_NEXT_COMMAND_VALUE         32768
    #define _APS_NEXT_CONTROL_VALUE         205
    #define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
