######################################################################
# Automatically generated by qmake (2.01a) on 22. nov 13:46:01 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
