######################################################################
# Automatically generated by qmake (2.01a) on 18. okt 19:40:38 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
