######################################################################
# Automatically generated by qmake (2.01a) to 12. apr 20:00:42 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
