// ImageErrors.h

#ifndef __IMAGEERRORS_H__
#define __IMAGEERRORS_H__

#define GL_SUCCESS 0

// File errors
#define GL_FILE_OPEN_ERROR -1
#define GL_FILE_CREATION_ERROR -2
#define GL_FILE_WRITE_ERROR -3
#define GL_FILE_READ_ERROR -4

// Memory erros
#define GL_MEMORY_ALLOCATION_ERROR -50
#define GL_MEMORY_LOCK_ERROR -51

// Argument errors
#define GL_NODIB -100

//
#define GL_UNSUPPORTED_FILETYPE -200
#define GL_HDIB_NULL -201
#define GL_LOGICAL_PALETTE_CREATION_ERROR -202
#define GL_NO_PALETTE_FOR_HIGH_COLOR -203
#define GL_STRETCHDIBITS_ERROR -204
#define GL_PALETTE_QUANTIZE_ERROR -205
#define GL_ATTEMPT_CHANGE_TO_SAME 206
#define GL_ROTATION_VALUE_ERROR -207
#define GL_ROTATE_ERROR -208

#endif

