######################################################################
# Automatically generated by qmake (2.01a) on 22. nov 09:16:19 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += tipzones.h
SOURCES += main.cpp tipzones.cpp
