APPNAME = simple_thread
CFLAGS  = /c /EHsc /Zc:wchar_t /fp:precise /D_WIN32_WINNT=0x0501 /D_DLL /MD /I"$(BOOST_DIR)"
LDFLAGS = /LIBPATH:"$(BOOST_DIR)/stage/lib"

all:
	cl $(CFLAGS) $(APPNAME).cpp
	link /OUT:$(APPNAME).exe $(LDFLAGS) $(APPNAME).obj

clean:
	del *.obj *.exe
