//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MfcCircCtrl.rc
//
#define IDS_CIRC                        1
#define IDD_ABOUTBOX_CIRC               1
#define IDB_CIRC                        1
#define IDI_ABOUTDLL                    1
#define IDS_CIRC_PPG                    2
#define IDS_CIRC_PPG_CAPTION            200
#define IDD_PROPPAGE_CIRC               200
#define IDC_CAPTION                     201
#define IDC_CIRCLEOFFSET                202
#define IDC_CIRCLESHAPE                 203

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
    #define _APS_NEXT_RESOURCE_VALUE        201
    #define _APS_NEXT_COMMAND_VALUE         32768
    #define _APS_NEXT_CONTROL_VALUE         204
    #define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
