######################################################################
# Automatically generated by qmake (2.01a) ti 12. sep 13:45:17 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
