######################################################################
# Automatically generated by qmake (2.01a) to 26. okt 19:29:55 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += eventwidget.h
SOURCES += eventwidget.cpp main.cpp
