######################################################################
# Automatically generated by qmake (2.00a) sö 13. aug 19:59:30 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myclass.h
SOURCES += gui-connection.cpp myclass.cpp
CONFIG += console 
