######################################################################
# Automatically generated by qmake (2.00a) ti 8. aug 18:09:23 2006
######################################################################

TEMPLATE = app
TARGET +=
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += cpp-with-qobject.cpp

CONFIG += console