######################################################################
# Automatically generated by qmake (2.00a) må 21. aug 14:28:49 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += special-lists.cpp
CONFIG += console