######################################################################
# Automatically generated by qmake (2.01a) ti 28. nov 15:19:13 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += wizard.h
SOURCES += main.cpp wizard.cpp
CONFIG += console 
