/*++

Copyright (c) Microsoft Corporation.  All rights reserved.

    THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
    KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
    PURPOSE.

Module Name:

   Event.h

--*/

#ifndef __PUBLIC__
#define __PUBLIC__


#include "devioctl.h"
#include <dontuse.h>


#define SIZEOF_REGISTER_EVENT  sizeof(REGISTER_EVENT )

#define IOCTL_ASIO_START \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x800, METHOD_NEITHER, FILE_ANY_ACCESS )

#define IOCTL_ASIO_STOP \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x801, METHOD_NEITHER, FILE_ANY_ACCESS )

#define IOCTL_ASIO_EVENT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x802, METHOD_NEITHER, FILE_ANY_ACCESS )

#define IOCTL_ASIO_BUFFERS \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x803, METHOD_NEITHER, FILE_ANY_ACCESS )

#define IOCTL_ASIO_BUFFER_READY \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x804, METHOD_NEITHER, FILE_ANY_ACCESS )

#define IOCTL_ASIO_BUFFER_SIZE \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x805, METHOD_NEITHER, FILE_ANY_ACCESS )

#define DRIVER_FUNC_INSTALL     0x01
#define DRIVER_FUNC_REMOVE      0x02

#define DRIVER_NAME       "event"



__inline KDBG(int nLevel, char* msg, ...);

#endif // __PUBLIC__

