//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by VCActiveX.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_VCACTIVEX_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDC_CALENDARCTRL                1005
#define IDC_YEAR                        1006
#define IDC_MONTH                       1007
#define IDC_DAY                         1008
#define IDC_NEXTWEEK                    1009
#define IDC_SELECTDATE                  1010

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
    #define _APS_NEXT_RESOURCE_VALUE        130
    #define _APS_NEXT_COMMAND_VALUE         32771
    #define _APS_NEXT_CONTROL_VALUE         1011
    #define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
