/* Generated by Together */

package com.javapatterns.facade.sessionfacade;

import javax.ejb.EJBObject;
import java.rmi.RemoteException;
import javax.ejb.EJBException;

public interface SessionFacade extends EJBObject {
    void BusinessMethod2() throws RemoteException, EJBException ;

    void BusinessMethod1() throws RemoteException, EJBException;

    /** @link dependency */
    /*#SessionFacadeBean lnkSession1Bean;*/
}
