// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "acroaxdocshim.h"

/////////////////////////////////////////////////////////////////////////////
// CAcroAXDocShim

IMPLEMENT_DYNCREATE(CAcroAXDocShim, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CAcroAXDocShim properties

/////////////////////////////////////////////////////////////////////////////
// CAcroAXDocShim operations

CString CAcroAXDocShim::GetSrc()
{
    CString result;
    InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
    return result;
}

void CAcroAXDocShim::SetSrc(LPCTSTR lpszNewValue)
{
    static BYTE parms[] =
        VTS_BSTR;
    InvokeHelper(0x1, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
                 lpszNewValue);
}

BOOL CAcroAXDocShim::LoadFile(LPCTSTR fileName)
{
    BOOL result;
    static BYTE parms[] =
        VTS_BSTR;
    InvokeHelper(0x2, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
                 fileName);
    return result;
}

void CAcroAXDocShim::setShowToolbar(BOOL On)
{
    static BYTE parms[] =
        VTS_BOOL;
    InvokeHelper(0x3, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
                 On);
}

void CAcroAXDocShim::gotoFirstPage()
{
    InvokeHelper(0x4, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAcroAXDocShim::gotoLastPage()
{
    InvokeHelper(0x5, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAcroAXDocShim::gotoNextPage()
{
    InvokeHelper(0x6, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAcroAXDocShim::gotoPreviousPage()
{
    InvokeHelper(0x7, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAcroAXDocShim::setCurrentPage(long n)
{
    static BYTE parms[] =
        VTS_I4;
    InvokeHelper(0x8, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
                 n);
}

void CAcroAXDocShim::goForwardStack()
{
    InvokeHelper(0x9, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAcroAXDocShim::goBackwardStack()
{
    InvokeHelper(0xa, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAcroAXDocShim::setPageMode(LPCTSTR pageMode)
{
    static BYTE parms[] =
        VTS_BSTR;
    InvokeHelper(0xb, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
                 pageMode);
}

void CAcroAXDocShim::setLayoutMode(LPCTSTR layoutMode)
{
    static BYTE parms[] =
        VTS_BSTR;
    InvokeHelper(0xc, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
                 layoutMode);
}

void CAcroAXDocShim::setNamedDest(LPCTSTR namedDest)
{
    static BYTE parms[] =
        VTS_BSTR;
    InvokeHelper(0xd, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
                 namedDest);
}

void CAcroAXDocShim::Print()
{
    InvokeHelper(0xe, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAcroAXDocShim::printWithDialog()
{
    InvokeHelper(0xf, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAcroAXDocShim::setZoom(float percent)
{
    static BYTE parms[] =
        VTS_R4;
    InvokeHelper(0x10, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
                 percent);
}

void CAcroAXDocShim::setZoomScroll(float percent, float left, float top)
{
    static BYTE parms[] =
        VTS_R4 VTS_R4 VTS_R4;
    InvokeHelper(0x11, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
                 percent, left, top);
}

void CAcroAXDocShim::setView(LPCTSTR viewMode)
{
    static BYTE parms[] =
        VTS_BSTR;
    InvokeHelper(0x12, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
                 viewMode);
}

void CAcroAXDocShim::setViewScroll(LPCTSTR viewMode, float offset)
{
    static BYTE parms[] =
        VTS_BSTR VTS_R4;
    InvokeHelper(0x13, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
                 viewMode, offset);
}

void CAcroAXDocShim::setViewRect(float left, float top, float width, float height)
{
    static BYTE parms[] =
        VTS_R4 VTS_R4 VTS_R4 VTS_R4;
    InvokeHelper(0x14, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
                 left, top, width, height);
}

void CAcroAXDocShim::printPages(long from, long to)
{
    static BYTE parms[] =
        VTS_I4 VTS_I4;
    InvokeHelper(0x15, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
                 from, to);
}

void CAcroAXDocShim::printPagesFit(long from, long to, BOOL shrinkToFit)
{
    static BYTE parms[] =
        VTS_I4 VTS_I4 VTS_BOOL;
    InvokeHelper(0x16, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
                 from, to, shrinkToFit);
}

void CAcroAXDocShim::printAll()
{
    InvokeHelper(0x17, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAcroAXDocShim::printAllFit(BOOL shrinkToFit)
{
    static BYTE parms[] =
        VTS_BOOL;
    InvokeHelper(0x18, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
                 shrinkToFit);
}

void CAcroAXDocShim::setShowScrollbars(BOOL On)
{
    static BYTE parms[] =
        VTS_BOOL;
    InvokeHelper(0x19, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
                 On);
}

VARIANT CAcroAXDocShim::GetVersions()
{
    VARIANT result;
    InvokeHelper(0x1a, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
    return result;
}

void CAcroAXDocShim::setCurrentHightlight(long a, long b, long c, long d)
{
    static BYTE parms[] =
        VTS_I4 VTS_I4 VTS_I4 VTS_I4;
    InvokeHelper(0x1b, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
                 a, b, c, d);
}

void CAcroAXDocShim::setCurrentHighlight(long a, long b, long c, long d)
{
    static BYTE parms[] =
        VTS_I4 VTS_I4 VTS_I4 VTS_I4;
    InvokeHelper(0x1c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
                 a, b, c, d);
}

void CAcroAXDocShim::postMessage(const VARIANT& strArray)
{
    static BYTE parms[] =
        VTS_VARIANT;
    InvokeHelper(0x1d, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
                 &strArray);
}

VARIANT CAcroAXDocShim::GetMessageHandler()
{
    VARIANT result;
    InvokeHelper(0x1e, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
    return result;
}

void CAcroAXDocShim::SetMessageHandler(const VARIANT& newValue)
{
    static BYTE parms[] =
        VTS_VARIANT;
    InvokeHelper(0x1e, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
                 &newValue);
}

void CAcroAXDocShim::execCommand(const VARIANT& strArray)
{
    static BYTE parms[] =
        VTS_VARIANT;
    InvokeHelper(0x1f, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
                 &strArray);
}
