// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAcroAXDocShim wrapper class

class CAcroAXDocShim : public CWnd
{
protected:
    DECLARE_DYNCREATE(CAcroAXDocShim)
public:
    CLSID const& GetClsid()
    {
        static CLSID const clsid
            = { 0xca8a9780, 0x280d, 0x11cf, { 0xa2, 0x4d, 0x44, 0x45, 0x53, 0x54, 0x0, 0x0 } };
        return clsid;
    }
    virtual BOOL Create(LPCTSTR lpszClassName,
                        LPCTSTR lpszWindowName, DWORD dwStyle,
                        const RECT& rect,
                        CWnd* pParentWnd, UINT nID,
                        CCreateContext* pContext = NULL)
    {
        return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID);
    }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
                const RECT& rect, CWnd* pParentWnd, UINT nID,
                CFile* pPersist = NULL, BOOL bStorage = FALSE,
                BSTR bstrLicKey = NULL)
    {
        return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
                             pPersist, bStorage, bstrLicKey);
    }

// Attributes
public:

// Operations
public:
    CString GetSrc();
    void SetSrc(LPCTSTR lpszNewValue);
    BOOL LoadFile(LPCTSTR fileName);
    void setShowToolbar(BOOL On);
    void gotoFirstPage();
    void gotoLastPage();
    void gotoNextPage();
    void gotoPreviousPage();
    void setCurrentPage(long n);
    void goForwardStack();
    void goBackwardStack();
    void setPageMode(LPCTSTR pageMode);
    void setLayoutMode(LPCTSTR layoutMode);
    void setNamedDest(LPCTSTR namedDest);
    void Print();
    void printWithDialog();
    void setZoom(float percent);
    void setZoomScroll(float percent, float left, float top);
    void setView(LPCTSTR viewMode);
    void setViewScroll(LPCTSTR viewMode, float offset);
    void setViewRect(float left, float top, float width, float height);
    void printPages(long from, long to);
    void printPagesFit(long from, long to, BOOL shrinkToFit);
    void printAll();
    void printAllFit(BOOL shrinkToFit);
    void setShowScrollbars(BOOL On);
    VARIANT GetVersions();
    void setCurrentHightlight(long a, long b, long c, long d);
    void setCurrentHighlight(long a, long b, long c, long d);
    void postMessage(const VARIANT& strArray);
    VARIANT GetMessageHandler();
    void SetMessageHandler(const VARIANT& newValue);
    void execCommand(const VARIANT& strArray);
};
