//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by dipper.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DIPPER_DIALOG               102
#define IDS_PLATFORM_WIN32_NT           110
#define IDS_PLATFORM_WIN32_NTAS         111
#define IDS_PLATFORM_WIN32_NTW          112
#define IDS_PLATFORM_WIN32_NTS          113
#define IDS_PLATFORM_WIN32s             114
#define IDS_PLATFORM_WIN32_WINDOWS      115
#define IDS_PLATFORM_UNKNOWN            116
#define IDS_PLATFORM_WIN32_NT2          117
#define IDS_PLATFORM_WIN32_NTAS2        118
#define IDS_PLATFORM_WIN32_NTW2         119
#define IDS_PROCESSOR_ARCHITECTURE_UNKNOWN 120
#define IDS_PROCESSOR_ARCHITECTURE_INTEL_386_486 121
#define IDS_PROCESSOR_ARCHITECTURE_INTEL_PENTIUM 122
#define IDS_PROCESSOR_ARCHITECTURE_ALPHA 123
#define IDS_PROCESSOR_ARCHITECTURE_MIPS 124
#define IDS_PROCESSOR_ARCHITECTURE_PPC  125
#define IDS_PROCESSOR_LEVEL_INTEL_UNKNOWN 126
#define IDS_PROCESSOR_LEVEL_ALPHA_UNKNOWN 127
#define IDR_MAINFRAME                   128
#define IDC_EMPTY_DIPPER                129
#define IDC_FULL_DIPPER                 130
#define IDI_EMPTY_GLASS                 131
#define IDI_1_GLASS                     132
#define IDI_2_GLASS                     133
#define IDI_3_GLASS                     134
#define IDI_BUCKET                      136
#define IDI_JMNCO                       140
#define IDS_PROCESSOR_LEVEL_MIPS_UNKNOWN 143
#define IDS_PROCESSOR_LEVEL_PPC_UNKNOWN 144
#define IDS_PROCESSOR_NOREV_INTEL_386   145
#define IDS_PROCESSOR_NOREV_INTEL_486   146
#define IDS_PROCESSOR_NOREV_INTEL_PENTIUM 147
#define IDS_PROCESSOR_NOREV_MIPS_R4000  148
#define IDS_PROCESSOR_NOREV_ALPHA_21064 149
#define IDS_READY                       500
#define IDS_CARRYING                    501
#define IDS_FULL                        502
#define IDS_DROPPABLE                   503
#define IDS_WASTE                       504
#define IDC_GLASS1                      1000
#define IDC_GLASS2                      1001
#define IDC_GLASS3                      1002
#define IDC_GLASS4                      1003
#define IDC_GLASS5                      1004
#define IDC_ABOUT_OSVERSION             1004
#define IDC_BUCKET                      1005
#define IDC_STATUS                      1006
#define IDC_ABOUT_PROCESSORVERSION      1006
#define IDC_ABOUT_FILEDESCRIPTION       1008
#define IDC_ABOUT_VERSION               1009
#define IDC_ABOUT_LEGALCOPYRIGHT        1010
#define IDC_ABOUT_LEGALTRADEMARKS       1011
#define IDC_ABOUT_COMMENTS              1012

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
