######################################################################
# Automatically generated by qmake (2.01a) må 16. okt 15:40:21 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
