######################################################################
# Automatically generated by qmake (2.01a) sö 22. okt 17:26:05 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += sortonsecondmodel.h
SOURCES += main.cpp sortonsecondmodel.cpp
