######################################################################
# Automatically generated by qmake (2.01a) må 30. okt 07:22:22 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += circlebar.h
SOURCES += circlebar.cpp main.cpp
CONFIG += console 
