######################################################################
# Automatically generated by qmake (2.00a) må 21. aug 15:57:33 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += map-examples.cpp
CONFIG += console 
