######################################################################
# Automatically generated by qmake (2.01a) lö 28. okt 16:32:43 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
