######################################################################
# Automatically generated by qmake (2.01a) on 17. jan 19:15:37 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += sql 
