######################################################################
# Automatically generated by qmake (2.01a) ti 28. nov 19:41:06 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
CONFIG += assistant 
TARGET = assist-demo 
