######################################################################
# Automatically generated by qmake (2.01a) fr 8. dec 22:18:27 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
CONFIG += console
