######################################################################
# Automatically generated by qmake (2.01a) sö 22. okt 15:48:57 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += objecttreemodel.h
SOURCES += main.cpp objecttreemodel.cpp
