#if !defined(AFX_CLOCK_H__BD8EE04A_F00E_4DCF_B3FE_25EA804CEA0F__INCLUDED_)
#define AFX_CLOCK_H__BD8EE04A_F00E_4DCF_B3FE_25EA804CEA0F__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CClock wrapper class

class CClock : public CWnd
{
protected:
	DECLARE_DYNCREATE(CClock)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x1beef2e0, 0x6d34, 0x4a57, { 0xa5, 0xac, 0x38, 0x40, 0x8a, 0x8f, 0x7, 0x53 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	OLE_COLOR GetBackColor();
	void SetBackColor(OLE_COLOR);
	OLE_COLOR GetForeColor();
	void SetForeColor(OLE_COLOR);
	short GetInterval();
	void SetInterval(short);

// Operations
public:
	void Hello();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CLOCK_H__BD8EE04A_F00E_4DCF_B3FE_25EA804CEA0F__INCLUDED_)
