//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DSplit.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_DSPLITTYPE                  129
#define IDD_DIALOG1                     130
#define IDD_DIALOG2                     131
#define ID_DYNSPLIT                     32771
#define ID_hhhh                         32772
#define ID_F0Q1                         32773
#define ID_FILEOPEN                     32774
#define ID_YUANTU                       32775
#define ID_FILESAVE                     32776
#define ID_QuickForuier                 32778
#define ID_LISANYUXUAN                  32779
#define ID_WALSH                        32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
