xcopy lua5.1.lib "%SDK_DIR%\lib\usr\*.*" /y
xcopy lua5.1-static.lib "%SDK_DIR%\lib\usr\*.*" /y
xcopy lua.exe "%UTIL_DIR%\*.*" /y
xcopy luac.exe "%UTIL_DIR%\*.*" /y
xcopy lua5.1.dll "%UTIL_DIR%\*.*" /y
xcopy lua.h "%SDK_DIR%\include\usr\*.*" /y
xcopy luaconf.h "%SDK_DIR%\include\usr\*.*" /y
xcopy lualib.h "%SDK_DIR%\include\usr\*.*" /y
xcopy lauxlib.h "%SDK_DIR%\include\usr\*.*" /y
