// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "vlcaudio.h"


/////////////////////////////////////////////////////////////////////////////
// CVLCAudio properties

/////////////////////////////////////////////////////////////////////////////
// CVLCAudio operations

BOOL CVLCAudio::GetMute()
{
    BOOL result;
    InvokeHelper(0x60020000, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
    return result;
}

void CVLCAudio::SetMute(BOOL bNewValue)
{
    static BYTE parms[] =
        VTS_BOOL;
    InvokeHelper(0x60020000, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
                 bNewValue);
}

long CVLCAudio::GetVolume()
{
    long result;
    InvokeHelper(0x60020002, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
    return result;
}

void CVLCAudio::SetVolume(long nNewValue)
{
    static BYTE parms[] =
        VTS_I4;
    InvokeHelper(0x60020002, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
                 nNewValue);
}

void CVLCAudio::toggleMute()
{
    InvokeHelper(0x60020004, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

long CVLCAudio::GetTrack()
{
    long result;
    InvokeHelper(0x60020005, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
    return result;
}

void CVLCAudio::SetTrack(long nNewValue)
{
    static BYTE parms[] =
        VTS_I4;
    InvokeHelper(0x60020005, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
                 nNewValue);
}

long CVLCAudio::GetChannel()
{
    long result;
    InvokeHelper(0x60020007, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
    return result;
}

void CVLCAudio::SetChannel(long nNewValue)
{
    static BYTE parms[] =
        VTS_I4;
    InvokeHelper(0x60020007, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
                 nNewValue);
}
