#if !defined(AFX_VLCAUDIO_H__5D3BB691_A807_484E_80D2_7E165E17596C__INCLUDED_)
#define AFX_VLCAUDIO_H__5D3BB691_A807_484E_80D2_7E165E17596C__INCLUDED_

#if _MSC_VER > 1000
    #pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CVLCAudio wrapper class

class CVLCAudio : public COleDispatchDriver
{
public:
    CVLCAudio() {}      // Calls COleDispatchDriver default constructor
    CVLCAudio(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
    CVLCAudio(const CVLCAudio& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
    BOOL GetMute();
    void SetMute(BOOL bNewValue);
    long GetVolume();
    void SetVolume(long nNewValue);
    void toggleMute();
    long GetTrack();
    void SetTrack(long nNewValue);
    long GetChannel();
    void SetChannel(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VLCAUDIO_H__5D3BB691_A807_484E_80D2_7E165E17596C__INCLUDED_)
