#if !defined(AFX_VLCCONTROL2_H__741C3A54_587A_43F5_9590_3498360F8495__INCLUDED_)
#define AFX_VLCCONTROL2_H__741C3A54_587A_43F5_9590_3498360F8495__INCLUDED_

#if _MSC_VER > 1000
    #pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CVLCAudio;
class CVLCInput;
class CVLCLog;
class CVLCPlaylist;
class CVLCVideo;

/////////////////////////////////////////////////////////////////////////////
// CVLCControl2 wrapper class

class CVLCControl2 : public CWnd
{
protected:
    DECLARE_DYNCREATE(CVLCControl2)
public:
    CLSID const& GetClsid()
    {
        static CLSID const clsid
            = { 0x9be31822, 0xfdad, 0x461b, { 0xad, 0x51, 0xbe, 0x1d, 0x1c, 0x15, 0x99, 0x21 } };
        return clsid;
    }
    virtual BOOL Create(LPCTSTR lpszClassName,
                        LPCTSTR lpszWindowName, DWORD dwStyle,
                        const RECT& rect,
                        CWnd* pParentWnd, UINT nID,
                        CCreateContext* pContext = NULL)
    {
        return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID);
    }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
                const RECT& rect, CWnd* pParentWnd, UINT nID,
                CFile* pPersist = NULL, BOOL bStorage = FALSE,
                BSTR bstrLicKey = NULL)
    {
        return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
                             pPersist, bStorage, bstrLicKey);
    }

// Attributes
public:

// Operations
public:
    BOOL GetAutoLoop();
    void SetAutoLoop(BOOL bNewValue);
    BOOL GetAutoPlay();
    void SetAutoPlay(BOOL bNewValue);
    CString GetBaseURL();
    void SetBaseURL(LPCTSTR lpszNewValue);
    long GetStartTime();
    void SetStartTime(long nNewValue);
    CString GetMrl();
    void SetMrl(LPCTSTR lpszNewValue);
    BOOL GetToolbar();
    void SetToolbar(BOOL bNewValue);
    CString GetVersionInfo();
    BOOL GetVisible();
    void SetVisible(BOOL bNewValue);
    long GetVolume();
    void SetVolume(long nNewValue);
    unsigned long GetBackColor();
    void SetBackColor(unsigned long newValue);
    CVLCAudio GetAudio();
    CVLCInput GetInput();
    CVLCLog GetLog();
    CVLCPlaylist GetPlaylist();
    CVLCVideo GetVideo();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VLCCONTROL2_H__741C3A54_587A_43F5_9590_3498360F8495__INCLUDED_)
