// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "vlcinput.h"


/////////////////////////////////////////////////////////////////////////////
// CVLCInput properties

/////////////////////////////////////////////////////////////////////////////
// CVLCInput operations

double CVLCInput::GetLength()
{
    double result;
    InvokeHelper(0x60020000, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
    return result;
}

double CVLCInput::GetPosition()
{
    double result;
    InvokeHelper(0x60020001, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
    return result;
}

void CVLCInput::SetPosition(double newValue)
{
    static BYTE parms[] =
        VTS_R8;
    InvokeHelper(0x60020001, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
                 newValue);
}

double CVLCInput::GetTime()
{
    double result;
    InvokeHelper(0x60020003, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
    return result;
}

void CVLCInput::SetTime(double newValue)
{
    static BYTE parms[] =
        VTS_R8;
    InvokeHelper(0x60020003, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
                 newValue);
}

long CVLCInput::GetState()
{
    long result;
    InvokeHelper(0x60020005, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
    return result;
}

double CVLCInput::GetRate()
{
    double result;
    InvokeHelper(0x60020006, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
    return result;
}

void CVLCInput::SetRate(double newValue)
{
    static BYTE parms[] =
        VTS_R8;
    InvokeHelper(0x60020006, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
                 newValue);
}

double CVLCInput::GetFps()
{
    double result;
    InvokeHelper(0x60020008, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
    return result;
}

BOOL CVLCInput::GetHasVout()
{
    BOOL result;
    InvokeHelper(0x60020009, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
    return result;
}
