#if !defined(AFX_VLCINPUT_H__8423E70E_9EE6_4546_9F9C_43ADE4DC4B2B__INCLUDED_)
#define AFX_VLCINPUT_H__8423E70E_9EE6_4546_9F9C_43ADE4DC4B2B__INCLUDED_

#if _MSC_VER > 1000
    #pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CVLCInput wrapper class

class CVLCInput : public COleDispatchDriver
{
public:
    CVLCInput() {}      // Calls COleDispatchDriver default constructor
    CVLCInput(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
    CVLCInput(const CVLCInput& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
    double GetLength();
    double GetPosition();
    void SetPosition(double newValue);
    double GetTime();
    void SetTime(double newValue);
    long GetState();
    double GetRate();
    void SetRate(double newValue);
    double GetFps();
    BOOL GetHasVout();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VLCINPUT_H__8423E70E_9EE6_4546_9F9C_43ADE4DC4B2B__INCLUDED_)
