// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "vlclog.h"

// Dispatch interfaces referenced by this interface
#include "vlcmessages.h"


/////////////////////////////////////////////////////////////////////////////
// CVLCLog properties

/////////////////////////////////////////////////////////////////////////////
// CVLCLog operations

CVLCMessages CVLCLog::GetMessages()
{
    LPDISPATCH pDispatch;
    InvokeHelper(0x60020000, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
    return CVLCMessages(pDispatch);
}

long CVLCLog::GetVerbosity()
{
    long result;
    InvokeHelper(0x60020001, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
    return result;
}

void CVLCLog::SetVerbosity(long nNewValue)
{
    static BYTE parms[] =
        VTS_I4;
    InvokeHelper(0x60020001, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
                 nNewValue);
}
