#if !defined(AFX_VLCLOG_H__B840C8A2_94B6_459D_9FE1_62186E334CEE__INCLUDED_)
#define AFX_VLCLOG_H__B840C8A2_94B6_459D_9FE1_62186E334CEE__INCLUDED_

#if _MSC_VER > 1000
    #pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CVLCMessages;

/////////////////////////////////////////////////////////////////////////////
// CVLCLog wrapper class

class CVLCLog : public COleDispatchDriver
{
public:
    CVLCLog() {}        // Calls COleDispatchDriver default constructor
    CVLCLog(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
    CVLCLog(const CVLCLog& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
    CVLCMessages GetMessages();
    long GetVerbosity();
    void SetVerbosity(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VLCLOG_H__B840C8A2_94B6_459D_9FE1_62186E334CEE__INCLUDED_)
