// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "vlcmessage.h"


/////////////////////////////////////////////////////////////////////////////
// CVLCMessage properties

/////////////////////////////////////////////////////////////////////////////
// CVLCMessage operations

VARIANT CVLCMessage::Get_Value()
{
    VARIANT result;
    InvokeHelper(0x0, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
    return result;
}

long CVLCMessage::GetSeverity()
{
    long result;
    InvokeHelper(0x60020001, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
    return result;
}

CString CVLCMessage::GetType()
{
    CString result;
    InvokeHelper(0x60020002, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
    return result;
}

CString CVLCMessage::GetName()
{
    CString result;
    InvokeHelper(0x60020003, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
    return result;
}

CString CVLCMessage::GetHeader()
{
    CString result;
    InvokeHelper(0x60020004, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
    return result;
}

CString CVLCMessage::GetMessage()
{
    CString result;
    InvokeHelper(0x60020005, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
    return result;
}
