#if !defined(AFX_VLCMESSAGEITERATOR_H__EC4E8466_65B0_4C02_88FB_07A794EF8B34__INCLUDED_)
#define AFX_VLCMESSAGEITERATOR_H__EC4E8466_65B0_4C02_88FB_07A794EF8B34__INCLUDED_

#if _MSC_VER > 1000
    #pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CVLCMessage;

/////////////////////////////////////////////////////////////////////////////
// CVLCMessageIterator wrapper class

class CVLCMessageIterator : public COleDispatchDriver
{
public:
    CVLCMessageIterator() {}        // Calls COleDispatchDriver default constructor
    CVLCMessageIterator(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
    CVLCMessageIterator(const CVLCMessageIterator& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
    BOOL GetHasNext();
    CVLCMessage next();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VLCMESSAGEITERATOR_H__EC4E8466_65B0_4C02_88FB_07A794EF8B34__INCLUDED_)
