#if !defined(AFX_VLCMESSAGE_H__D32BC219_ABFD_4553_946A_22B66D7316CE__INCLUDED_)
#define AFX_VLCMESSAGE_H__D32BC219_ABFD_4553_946A_22B66D7316CE__INCLUDED_

#if _MSC_VER > 1000
    #pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CVLCMessage wrapper class

class CVLCMessage : public COleDispatchDriver
{
public:
    CVLCMessage() {}        // Calls COleDispatchDriver default constructor
    CVLCMessage(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
    CVLCMessage(const CVLCMessage& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
    VARIANT Get_Value();
    long GetSeverity();
    CString GetType();
    CString GetName();
    CString GetHeader();
    CString GetMessage();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VLCMESSAGE_H__D32BC219_ABFD_4553_946A_22B66D7316CE__INCLUDED_)
