#if !defined(AFX_VLCMESSAGES_H__2589AD12_8E6B_4B17_82D3_5968A0994D7E__INCLUDED_)
#define AFX_VLCMESSAGES_H__2589AD12_8E6B_4B17_82D3_5968A0994D7E__INCLUDED_

#if _MSC_VER > 1000
    #pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CVLCMessageIterator;

/////////////////////////////////////////////////////////////////////////////
// CVLCMessages wrapper class

class CVLCMessages : public COleDispatchDriver
{
public:
    CVLCMessages() {}       // Calls COleDispatchDriver default constructor
    CVLCMessages(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
    CVLCMessages(const CVLCMessages& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
    LPUNKNOWN Get_NewEnum();
    void clear();
    long GetCount();
    CVLCMessageIterator iterator();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VLCMESSAGES_H__2589AD12_8E6B_4B17_82D3_5968A0994D7E__INCLUDED_)
