// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "vlcmessages.h"

// Dispatch interfaces referenced by this interface
#include "vlcmessageiterator.h"


/////////////////////////////////////////////////////////////////////////////
// CVLCMessages properties

/////////////////////////////////////////////////////////////////////////////
// CVLCMessages operations

LPUNKNOWN CVLCMessages::Get_NewEnum()
{
    LPUNKNOWN result;
    InvokeHelper(0xfffffffc, DISPATCH_PROPERTYGET, VT_UNKNOWN, (void*)&result, NULL);
    return result;
}

void CVLCMessages::clear()
{
    InvokeHelper(0x60020001, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

long CVLCMessages::GetCount()
{
    long result;
    InvokeHelper(0x60020002, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
    return result;
}

CVLCMessageIterator CVLCMessages::iterator()
{
    LPDISPATCH pDispatch;
    InvokeHelper(0x60020003, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, NULL);
    return CVLCMessageIterator(pDispatch);
}
