// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "vlcplaylistitems.h"


/////////////////////////////////////////////////////////////////////////////
// CVLCPlaylistItems properties

/////////////////////////////////////////////////////////////////////////////
// CVLCPlaylistItems operations

long CVLCPlaylistItems::GetCount()
{
    long result;
    InvokeHelper(0x60020000, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
    return result;
}

void CVLCPlaylistItems::clear()
{
    InvokeHelper(0x60020001, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CVLCPlaylistItems::remove(long itemId)
{
    static BYTE parms[] =
        VTS_I4;
    InvokeHelper(0x60020002, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
                 itemId);
}
