#if !defined(AFX_VLCPLAYLISTITEMS_H__C5956DB5_97C3_48D8_AA6C_31363ECC4E69__INCLUDED_)
#define AFX_VLCPLAYLISTITEMS_H__C5956DB5_97C3_48D8_AA6C_31363ECC4E69__INCLUDED_

#if _MSC_VER > 1000
    #pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CVLCPlaylistItems wrapper class

class CVLCPlaylistItems : public COleDispatchDriver
{
public:
    CVLCPlaylistItems() {}      // Calls COleDispatchDriver default constructor
    CVLCPlaylistItems(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
    CVLCPlaylistItems(const CVLCPlaylistItems& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
    long GetCount();
    void clear();
    void remove(long itemId);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VLCPLAYLISTITEMS_H__C5956DB5_97C3_48D8_AA6C_31363ECC4E69__INCLUDED_)
