#if !defined(AFX_VLCVIDEO_H__249875F1_D9EE_46E8_B574_B3A86F6733E9__INCLUDED_)
#define AFX_VLCVIDEO_H__249875F1_D9EE_46E8_B574_B3A86F6733E9__INCLUDED_

#if _MSC_VER > 1000
    #pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPicture;

/////////////////////////////////////////////////////////////////////////////
// CVLCVideo wrapper class

class CVLCVideo : public COleDispatchDriver
{
public:
    CVLCVideo() {}      // Calls COleDispatchDriver default constructor
    CVLCVideo(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
    CVLCVideo(const CVLCVideo& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
    BOOL GetFullscreen();
    void SetFullscreen(BOOL bNewValue);
    long GetWidth();
    long GetHeight();
    CString GetAspectRatio();
    void SetAspectRatio(LPCTSTR lpszNewValue);
    long GetSubtitle();
    void SetSubtitle(long nNewValue);
    CString GetCrop();
    void SetCrop(LPCTSTR lpszNewValue);
    long GetTeletext();
    void SetTeletext(long nNewValue);
    void toggleFullscreen();
    CPicture takeSnapshot();
    void toggleTeletext();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VLCVIDEO_H__249875F1_D9EE_46E8_B574_B3A86F6733E9__INCLUDED_)
