######################################################################
# Automatically generated by qmake (2.01a) lö 28. okt 16:45:10 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += clocklabel.h
SOURCES += clocklabel.cpp main.cpp
CONFIG += console 
