Calculator: node_subtract Class Reference
node_subtract Class Reference
#include <node_impl.hpp>
Public Member Functions
node_subtract (node left, node right)
node_subtract (std::istream &stream)
Public Member Functions inherited from node_binary
node_binary (node left, node right)
node left () const
node right () const
Public Member Functions inherited from node_impl
node_impl ()
virtual ~node_impl ()
node_impl (node_impl &&)=default
node_impl & operator= (node_impl &&)=default
void print (std::ostream &stream, int indent) const
number evaluate () const
std::string to_string () const
identifier_list const & get_parameters () const
void save (std::ostream &stream) const
Private Member Functions
virtual void print_node (std::ostream &stream, int indent) const override
virtual number evaluate_node () const override
virtual void save_node (std::ostream &stream) const override
Additional Inherited Members
Static Public Member Functions inherited from node_impl
static std::shared_ptr< node_impl > read_node (std::istream &stream)
Protected Member Functions inherited from node_binary
node_binary (std::istream &stream)
number evaluate_left () const
number evaluate_right () const
Detailed Description
Subtraction.
Definition at line 191 of file node_impl.hpp.
Constructor & Destructor Documentation
node_subtract::node_subtract (node left, node right)
Definition at line 465 of file node_impl.cpp.
References node_binary::left().
 : node_binary{left, right}
 {}
node_subtract::node_subtract (std::istream & stream)
Definition at line 469 of file node_impl.cpp.
 : node_binary{stream}
 {}
Member Function Documentation
number node_subtract::evaluate_node () const override private virtual
Implements node_binary.
Definition at line 481 of file node_impl.cpp.
References node_binary::evaluate_left(), and node_binary::evaluate_right().
 {
   return evaluate_left() - evaluate_right();
 }
void node_subtract::print_node (std::ostream & stream, int indent) const override private virtual
Implements node_binary.
Definition at line 473 of file node_impl.cpp.
References node_binary::left(), node::print(), and node_binary::right().
 {
   stream << std::setw(indent) << "" << "-\n";
   left().print(stream, indent + 2);
   right().print(stream, indent + 2);
 }
void node_subtract::save_node (std::ostream & stream) const override private virtual
Implements node_binary.
Definition at line 487 of file node_impl.cpp.
References node_binary::left(), node_binary::right(), and node::save().
 {
   stream << "subtract ";
   left().save(stream);
   right().save(stream);
 }
The documentation for this class was generated from the following files:
node_impl.hpp
node_impl.cpp