Calculator: node Class Reference
node Class Reference
#include <node.hpp>
Public Member Functions
node ()
node (std::istream &stream)
node (long x)
node (int x)
node (double x)
node (number num)
node (std::string identifier)
node (char op, node operand)
node (node left, char op, node right)
node (identifier_list parameters, node definition)
node (std::string name, node_list arguments)
node (node const &)=default
node (node &&)=default
node & operator= (node const &)=default
node & operator= (node &&)=default
~node ()=default
void print (std::ostream &stream, int indent=0) const
number evaluate () const
std::string to_string () const
identifier_list const & get_parameters () const
void save (std::ostream &stream) const
Static Private Member Functions
static std::shared_ptr< node_impl > make_binary_operator (node, char, node)
Factory function to make the binary operator nodes.
Private Attributes
std::shared_ptr< node_impl > pimpl_
Detailed Description
Wrapper class for all parse-tree nodes. The actual parse tree nodes derive from node_impl. This class uses the pimpl idiom to make it easier to work with node objects.
Definition at line 28 of file node.hpp.
Constructor & Destructor Documentation
node::node ()
Construct a node of type void.
Definition at line 23 of file node.cpp.
 : pimpl_{std::make_shared<node_void>()}
 {}
node::node (std::istream & stream)
Construct a node by reading from a library file.
Definition at line 27 of file node.cpp.
References node_impl::read_node().
 : pimpl_{node_impl::read_node(stream)}
 {}
node::node (long x)
Construct an integer node.
Parameters
x The integer
Definition at line 35 of file node.cpp.
 : pimpl_{std::make_shared<node_number>(number{x})}
 {}
node::node (int x)
Construct an integer node.
Parameters
x The integer
Definition at line 31 of file node.cpp.
 : pimpl_{std::make_shared<node_number>(number{x})}
 {}
node::node (double x)
Construct a floating-point node.
Parameters
x The value
Definition at line 39 of file node.cpp.
 : pimpl_{std::make_shared<node_number>(number{x})}
 {}
node::node (number num)
Construct a numeric node.
Parameters
num The number
Definition at line 43 of file node.cpp.
 : pimpl_{std::make_shared<node_number>(num)}
 {}
node::node (std::string identifier)
Construct an identifier node.
Parameters
identifier The identifier
Definition at line 47 of file node.cpp.
   : pimpl_{std::make_shared<node_identifier>(std::move(identifier))}
   {}
node::node (char op, node operand)
Construct a unary operator node.
Parameters
op The operator character, e.g., '-'
operand The operand node
Definition at line 51 of file node.cpp.
 : pimpl_{std::make_shared<node_negate>(operand)}
 {}
node::node (node left, char op, node right)
Construct a binary operator node.
Parameters
left The left-hand parse-tree
op The operator character, e.g., '*'
right The right-hand operand
Definition at line 55 of file node.cpp.
References make_binary_operator().
 : pimpl_{make_binary_operator(left, op, right)}
 {}
node::node (identifier_list parameters, node definition)
Construct a function definition node.
Parameters
parameters The list of all the parameter names
definition The function definition
Definition at line 59 of file node.cpp.
 : pimpl_{std::make_shared<node_function>(std::move(parameters), definition)}
 {}
node::node (std::string name, node_list arguments)
Construct a function call node.
Parameters
name The function name
arguments The function arguments
Definition at line 63 of file node.cpp.
 : pimpl_{std::make_shared<node_function_call>(std::move(name), std::move(arguments))}
 {}
node::node (node const &) default
node::node (node &&) default
node::~node () default
Member Function Documentation
number node::evaluate () const
Evaluate a parse tree. Evaluate and tree and return the result.
Definition at line 73 of file node.cpp.
References pimpl_.
Referenced by BOOST_AUTO_TEST_CASE(), node_binary::evaluate_left(), node_identifier::evaluate_node(), node_function::evaluate_node(), node_unary::evaluate_operand(), node_binary::evaluate_right(), and parser::get_statement().
 {
   return pimpl_->evaluate();
 }
identifier_list const & node::get_parameters () const
Return a list of parameter names. Most node return a reference to a global, static, const, empty list. Only function nodes return a list of parameters.
Definition at line 85 of file node.cpp.
References pimpl_.
Referenced by node_function_call::evaluate_node().
 {
   return pimpl_->get_parameters();
 }
std::shared_ptr< node_impl > node::make_binary_operator (node left, char op, node right) static private
Factory function to make the binary operator nodes.
Definition at line 9 of file node.cpp.
Referenced by node().
 {
   if (op == '+')
     return std::make_shared<node_add>(left, right);
   else if (op == '-')
     return std::make_shared<node_subtract>(left, right);
   else if (op == '*')
     return std::make_shared<node_multiply>(left, right);
   else if (op == '/')
     return std::make_shared<node_divide>(left, right);
   else
     throw calc_error{"fatal error in make_binary_opreator: unknown operator: " + std::string(1,op)};
 }
node& node::operator= (node const &) default
node& node::operator= (node &&) default
void node::print (std::ostream & stream, int indent = 0) const
Print a tree. For debugging, print a visual representation of the parse tree. Each level increments the indent to make the tree structure evident.
Parameters
stream The output stream
indent The indentation.
Definition at line 67 of file node.cpp.
References pimpl_.
Referenced by node_function::print_node(), node_negate::print_node(), node_add::print_node(), node_subtract::print_node(), node_multiply::print_node(), and node_divide::print_node().
 {
   pimpl_->print(stream, indent);
 }
void node::save (std::ostream & stream) const
Save the node to a stream.
Parameters
stream The output stream
Definition at line 91 of file node.cpp.
References pimpl_.
Referenced by node_function::save_node(), node_negate::save_node(), node_add::save_node(), node_subtract::save_node(), node_multiply::save_node(), and node_divide::save_node().
 {
   pimpl_->save(stream);
 }
std::string node::to_string () const
Return a string representation. For an identifier node, return the identifier. For all other nodes, return a string representation of the evaluated value.
Definition at line 79 of file node.cpp.
References pimpl_.
Referenced by BOOST_AUTO_TEST_CASE().
 {
   return pimpl_->to_string();
 }
Member Data Documentation
std::shared_ptr<node_impl> node::pimpl_ private
Definition at line 114 of file node.hpp.
Referenced by evaluate(), get_parameters(), print(), save(), and to_string().
The documentation for this class was generated from the following files:
node.hpp
node.cpp