Calculator: node_function_call Class Reference
node_function_call Class Reference
#include <node_impl.hpp>
Public Member Functions
node_function_call (std::string name, node_list arguments)
node_function_call (std::istream &stream)
std::string name () const
node_list const & arguments () const
Public Member Functions inherited from node_impl
node_impl ()
virtual ~node_impl ()
node_impl (node_impl &&)=default
node_impl & operator= (node_impl &&)=default
void print (std::ostream &stream, int indent) const
number evaluate () const
std::string to_string () const
identifier_list const & get_parameters () const
void save (std::ostream &stream) const
Private Member Functions
virtual void print_node (std::ostream &stream, int indent) const override
virtual number evaluate_node () const override
virtual void save_node (std::ostream &stream) const override
Private Attributes
std::string name_
node_list arguments_
Additional Inherited Members
Static Public Member Functions inherited from node_impl
static std::shared_ptr< node_impl > read_node (std::istream &stream)
Detailed Description
Function call.
Definition at line 118 of file node_impl.hpp.
Constructor & Destructor Documentation
node_function_call::node_function_call (std::string name, node_list arguments)
Definition at line 276 of file node_impl.cpp.
 : node_impl{}, name_{std::move(name)}, arguments_{std::move(arguments)}
 {}
node_function_call::node_function_call (std::istream & stream)
Definition at line 280 of file node_impl.cpp.
 : node_impl{}
 {
   std::string name{};
   if (not (stream >> name_))
     throw calc_error{"malformed library file, cannot read function call name"};
   std::size_t size{};
   if (not (stream >> size))
     throw calc_error{"malformed library file, cannot read function call"};
   arguments_.reserve(size);
   while (size-- != 0) {
     arguments_.emplace_back(stream);
   }
 }
Member Function Documentation
node_list const & node_function_call::arguments () const
Definition at line 301 of file node_impl.cpp.
References arguments_.
Referenced by evaluate_node(), print_node(), and save_node().
 {
   return arguments_;
 }
number node_function_call::evaluate_node () const override private virtual
Implements node_impl.
Definition at line 320 of file node_impl.cpp.
References arguments(), get_function(), node::get_parameters(), and name().
 {
   // Create a local symbol table, assigning all the node values to the parameters.
   node function{ get_function(name()) };
   identifier_list const& parameters{ function.get_parameters() };
   if (parameters.size() != arguments().size())
     throw function_error{name(), parameters.size(), arguments().size()};
   else
   {
     // Create a local symbol table by assigning the arguments to the function parameters.
     symbol_table locals{};
     identifier_list::const_iterator parm{parameters.begin()};
     for (auto const& arg : arguments()) {
       locals.insert(std::make_pair(*parm, arg));
       ++parm;
     }
     set_symbol_table syms{locals};
     return function.evaluate();
   }
 }
std::string node_function_call::name () const
Definition at line 295 of file node_impl.cpp.
References name_.
Referenced by evaluate_node(), print_node(), and save_node().
 {
   return name_;
 }
void node_function_call::print_node (std::ostream & stream, int indent) const override private virtual
Implements node_impl.
Definition at line 307 of file node_impl.cpp.
References arguments(), and name().
 {
   stream << std::setw(indent) << "" << name() << "(\n";
   std::size_t index{0};
   for (auto const& arg : arguments()) {
     stream << std::setw(indent+1) << "" << "arg " << index << ": ";
     arg.print(stream, indent + 2);
     ++index;
   }
   stream << std::setw(indent) << "" << ")\n";
 }
void node_function_call::save_node (std::ostream & stream) const override private virtual
Implements node_impl.
Definition at line 342 of file node_impl.cpp.
References arguments(), and name().
 {
   stream << "call " << name() << ' ' << arguments().size() << ' ';
   for (auto const& arg : arguments())
     arg.save(stream);
 }
Member Data Documentation
node_list node_function_call::arguments_ private
Definition at line 130 of file node_impl.hpp.
Referenced by arguments().
std::string node_function_call::name_ private
Definition at line 129 of file node_impl.hpp.
Referenced by name().
The documentation for this class was generated from the following files:
node_impl.hpp
node_impl.cpp