Calculator: node_identifier Class Reference
node_identifier Class Reference
#include <node_impl.hpp>
Public Member Functions
node_identifier (std::string name)
node_identifier (std::istream &stream)
std::string const & name () const
Public Member Functions inherited from node_impl
node_impl ()
virtual ~node_impl ()
node_impl (node_impl &&)=default
node_impl & operator= (node_impl &&)=default
void print (std::ostream &stream, int indent) const
number evaluate () const
std::string to_string () const
identifier_list const & get_parameters () const
void save (std::ostream &stream) const
Private Member Functions
virtual void print_node (std::ostream &stream, int indent) const override
virtual number evaluate_node () const override
virtual std::string evaluate_string () const override
virtual void save_node (std::ostream &stream) const override
Private Attributes
std::string name_
Additional Inherited Members
Static Public Member Functions inherited from node_impl
static std::shared_ptr< node_impl > read_node (std::istream &stream)
Detailed Description
Identifier data type. Used for variable references.
Definition at line 84 of file node_impl.hpp.
Constructor & Destructor Documentation
node_identifier::node_identifier (std::string name)
Definition at line 160 of file node_impl.cpp.
 : node_impl{}, name_{std::move(name)}
 {}
node_identifier::node_identifier (std::istream & stream)
Definition at line 164 of file node_impl.cpp.
 : node_impl{}
 {
   if (not (stream >> name_))
     throw calc_error("malformed library file, cannot read identifier");
 }
Member Function Documentation
number node_identifier::evaluate_node () const override private virtual
Implements node_impl.
Definition at line 183 of file node_impl.cpp.
References node::evaluate(), get_variable(), and name().
 {
   return get_variable(name()).evaluate();
 }
std::string node_identifier::evaluate_string () const override private virtual
Reimplemented from node_impl.
Definition at line 189 of file node_impl.cpp.
References name().
 {
   return name();
 }
std::string const & node_identifier::name () const
Definition at line 171 of file node_impl.cpp.
References name_.
Referenced by evaluate_node(), evaluate_string(), print_node(), and save_node().
 {
   return name_;
 }
void node_identifier::print_node (std::ostream & stream, int indent) const override private virtual
Implements node_impl.
Definition at line 177 of file node_impl.cpp.
References name().
 {
   stream << std::setw(indent) << "" << "identifier " << name() << '\n';
 }
void node_identifier::save_node (std::ostream & stream) const override private virtual
Implements node_impl.
Definition at line 195 of file node_impl.cpp.
References name().
 {
   stream << "identifier " << name() << '\n';
 }
Member Data Documentation
std::string node_identifier::name_ private
Definition at line 95 of file node_impl.hpp.
Referenced by name().
The documentation for this class was generated from the following files:
node_impl.hpp
node_impl.cpp