Calculator: node_number Class Reference
node_number Class Reference
#include <node_impl.hpp>
Public Member Functions
node_number (number value)
node_number (std::istream &stream)
number value () const
Public Member Functions inherited from node_impl
node_impl ()
virtual ~node_impl ()
node_impl (node_impl &&)=default
node_impl & operator= (node_impl &&)=default
void print (std::ostream &stream, int indent) const
number evaluate () const
std::string to_string () const
identifier_list const & get_parameters () const
void save (std::ostream &stream) const
Private Member Functions
virtual void print_node (std::ostream &stream, int indent) const override
virtual number evaluate_node () const override
virtual void save_node (std::ostream &stream) const override
Private Attributes
number value_
Additional Inherited Members
Static Public Member Functions inherited from node_impl
static std::shared_ptr< node_impl > read_node (std::istream &stream)
Detailed Description
Number data type. Used for numeric literals.
Definition at line 68 of file node_impl.hpp.
Constructor & Destructor Documentation
node_number::node_number (number value)
Definition at line 125 of file node_impl.cpp.
 : node_impl{}, value_{value}
 {}
node_number::node_number (std::istream & stream)
Definition at line 129 of file node_impl.cpp.
 : node_impl{}, value_{stream}
 {}
Member Function Documentation
number node_number::evaluate_node () const override private virtual
Implements node_impl.
Definition at line 145 of file node_impl.cpp.
References value().
 {
   return value();
 }
void node_number::print_node (std::ostream & stream, int indent) const override private virtual
Implements node_impl.
Definition at line 139 of file node_impl.cpp.
References value().
 {
   stream << std::setw(indent) << "" << value() << '\n';
 }
void node_number::save_node (std::ostream & stream) const override private virtual
Implements node_impl.
Definition at line 151 of file node_impl.cpp.
References number::save(), and value().
 {
   stream << "number ";
   value().save(stream);
   stream << '\n';
 }
number node_number::value () const
Definition at line 133 of file node_impl.cpp.
References value_.
Referenced by evaluate_node(), print_node(), and save_node().
 {
   return value_;
 }
Member Data Documentation
number node_number::value_ private
Definition at line 78 of file node_impl.hpp.
Referenced by value().
The documentation for this class was generated from the following files:
node_impl.hpp
node_impl.cpp