Calculator: rational< T > Class Template Reference
rational< T > Class Template Reference
Represent a rational number (fraction) as a numerator and denominator.
#include <rational.hpp>
Public Types
typedef T value_type
Convenience typedef for the integral type of the numerator and denominator.
Public Member Functions
rational (value_type num=0)
rational (value_type num, value_type den)
rational (double r)
template<class U >
rational (rational< U > const &that)
Copy from a different type of rational.
value_type numerator () const
Return the numerator.
value_type denominator () const
Return the denominator.
template<class U , class EnableIfFloat = typename std::enable_if<std::is_floating_point<U>::value>::type>
operator U () const
Convert the rational number to a floating-point type.
rational & operator= (value_type)
Assignment of an integer.
template<class U >
rational & operator= (rational< U > const &rhs)
Assignment of a rational with a different size.
rational & operator+= (rational const &rhs)
Addition assignment operator.
rational & operator+= (value_type const &rhs)
Addition assignment operator.
rational & operator-= (rational const &rhs)
Subtraction assignment operator.
rational & operator-= (value_type const &rhs)
Subtraction assignment operator.
rational & operator*= (rational const &rhs)
Multiplication assignment operator.
rational & operator*= (value_type const &rhs)
Multiplication assignment operator.
rational & operator/= (rational const &rhs)
Division assignment operator.
rational & operator/= (value_type const &rhs)
Division assignment operator.
rational & operator++ ()
Pre-increment.
rational & operator-- ()
Pre-decrement.
rational operator++ (int)
Post-increment.
rational operator-- (int)
Post-decrement.
template<class U >
T scale (U value)
template<class U >
rational< T > & operator= (rational< U > const &rhs)
Private Member Functions
void reduce ()
Reduce the numerator and denominator by their GCD.
void normalize ()
template<class U >
value_type scale (U value)
Private Attributes
value_type numerator_
value_type denominator_
Static Private Attributes
static constexpr value_type double_divisor = power10<value_type>(std::numeric_limits<value_type>::digits10 - 1)
Detailed Description
template<class T>
class rational< T >
Represent a rational number (fraction) as a numerator and denominator.
Definition at line 26 of file rational.hpp.
Member Typedef Documentation
template<class T> typedef T rational< T >::value_type
Convenience typedef for the integral type of the numerator and denominator.
Definition at line 30 of file rational.hpp.
Constructor & Destructor Documentation
template<class T> rational< T >::rational (value_type num = 0) inline
Default constructor and constructor from a single value. As a default constructor, initializes to zero. Otherwise, initializes to the integer num.
Parameters
num The integer value to use as the initial value
Definition at line 36 of file rational.hpp.
 : numerator_{num}, denominator_{1} {}
template<class T > rational< T >::rational (value_type num, value_type den)
Construct a rational number
Parameters
num numerator
den denominator
Exceptions
zero_denominator if den == 0
Definition at line 113 of file rational.hpp.
 : numerator_{num},
   denominator_{den == value_type{} ? throw zero_denominator{"zero denominator"} : den}
 {
   normalize();
 }
template<class T > rational< T >::rational (double r)
Initialize the rational number with an approximation of r
Parameters
r the initial value
Definition at line 121 of file rational.hpp.
References rational< T >::double_divisor.
 : numerator_{static_cast<T>(r / double_divisor + 0.5)}, denominator_{double_divisor}
 {}
template<class T > template<class U > rational< T >::rational (rational< U > const & that)
Copy from a different type of rational.
Definition at line 127 of file rational.hpp.
References rational< T >::denominator(), rational< T >::denominator_, rational< T >::numerator(), and rational< T >::reduce().
 : numerator_{scale<U>(that.numerator())}, denominator_{scale<U>(that.denominator())}
 {
   reduce();
 }
Member Function Documentation
template<class T> value_type rational< T >::denominator () const inline
Return the denominator.
Definition at line 52 of file rational.hpp.
Referenced by absval(), number_rational::do_divide(), rational< long long >::operator U(), rational< T >::operator*=(), rational< T >::operator++(), rational< T >::operator+=(), operator-(), rational< T >::operator--(), rational< T >::operator-=(), operator/(), rational< T >::operator/=(), rational< T >::operator=(), operator==(), rational< T >::rational(), and rational< T >::reduce().
 { return denominator_; }
template<class T > void rational< T >::normalize () private
Reduce the numerator and denominator, and normalize the signs of both, that is, ensure denominator is not negative.
Definition at line 144 of file rational.hpp.
References rational< T >::denominator_, rational< T >::numerator_, and rational< T >::reduce().
Referenced by rational< T >::operator/=().
 {
   if (denominator_ < value_type{})
   {
     denominator_ = -denominator_;
     numerator_ = -numerator_;
   }
   reduce();
 }
template<class T> value_type rational< T >::numerator () const inline
Return the numerator.
Definition at line 50 of file rational.hpp.
Referenced by absval(), number_rational::do_divide(), rational< long long >::operator U(), rational< T >::operator*=(), rational< T >::operator+=(), operator-(), rational< T >::operator-=(), operator/(), rational< T >::operator/=(), operator<(), operator<<(), rational< T >::operator=(), operator==(), rational< T >::rational(), and rational< T >::reduce().
 { return numerator_; }
template<class T> template<class U , class EnableIfFloat = typename std::enable_if<std::is_floating_point<U>::value>::type> rational< T >::operator U () const inline explicit
Convert the rational number to a floating-point type.
Definition at line 55 of file rational.hpp.
 { return static_cast<U>(numerator()) / denominator(); }
template<class T > rational< T > & rational< T >::operator*= (rational< T > const & rhs)
Multiplication assignment operator.
Definition at line 217 of file rational.hpp.
References rational< T >::denominator(), rational< T >::denominator_, rational< T >::numerator(), rational< T >::numerator_, and rational< T >::reduce().
 {
   numerator_ *= rhs.numerator();
   denominator_ *= rhs.denominator();
   reduce();
   return *this;
 }
template<class T > rational< T > & rational< T >::operator*= (value_type const & rhs)
Multiplication assignment operator.
Definition at line 226 of file rational.hpp.
References rational< T >::numerator_, and rational< T >::reduce().
 {
   numerator_ *= rhs;
   reduce();
   return *this;
 }
template<class T > rational< T > & rational< T >::operator++ ()
Pre-increment.
Definition at line 255 of file rational.hpp.
References rational< T >::denominator(), and rational< T >::numerator_.
 {
   numerator_ += denominator();
   return *this;
 }
template<class T > rational< T > rational< T >::operator++ (int)
Post-increment.
Definition at line 262 of file rational.hpp.
 {
   rational result(*this);
   ++*this;
   return result;
 }
template<class T > rational< T > & rational< T >::operator+= (rational< T > const & rhs)
Addition assignment operator.
Definition at line 183 of file rational.hpp.
References rational< T >::denominator(), rational< T >::denominator_, rational< T >::numerator(), rational< T >::numerator_, and rational< T >::reduce().
 {
   numerator_ = numerator() * rhs.denominator() + rhs.numerator() * denominator();
   denominator_ *= rhs.denominator();
   reduce();
   return *this;
 }
template<class T > rational< T > & rational< T >::operator+= (value_type const & rhs)
Addition assignment operator.
Definition at line 192 of file rational.hpp.
References rational< T >::denominator(), rational< T >::numerator(), rational< T >::numerator_, and rational< T >::reduce().
 {
   numerator_ = numerator() + rhs * denominator();
   reduce();
   return *this;
 }
template<class T > rational< T > & rational< T >::operator-- ()
Pre-decrement.
Definition at line 270 of file rational.hpp.
References rational< T >::denominator(), and rational< T >::numerator_.
 {
   numerator_ -= denominator();
   return *this;
 }
template<class T > rational< T > rational< T >::operator-- (int)
Post-decrement.
Definition at line 277 of file rational.hpp.
 {
   rational result(*this);
   --*this;
   return result;
 }
template<class T > rational< T > & rational< T >::operator-= (rational< T > const & rhs)
Subtraction assignment operator.
Definition at line 200 of file rational.hpp.
References rational< T >::denominator(), rational< T >::denominator_, rational< T >::numerator(), rational< T >::numerator_, and rational< T >::reduce().
 {
   numerator_ = numerator() * rhs.denominator() - rhs.numerator() * denominator();
   denominator_ *= rhs.denominator();
   reduce();
   return *this;
 }
template<class T > rational< T > & rational< T >::operator-= (value_type const & rhs)
Subtraction assignment operator.
Definition at line 209 of file rational.hpp.
References rational< T >::denominator(), rational< T >::numerator(), rational< T >::numerator_, and rational< T >::reduce().
 {
   numerator_ = numerator() - rhs * denominator();
   reduce();
   return *this;
 }
template<class T > rational< T > & rational< T >::operator/= (rational< T > const & rhs)
Division assignment operator.
Definition at line 234 of file rational.hpp.
References rational< T >::denominator(), rational< T >::denominator_, rational< T >::normalize(), rational< T >::numerator(), and rational< T >::numerator_.
 {
   if (rhs.numerator() == value_type{})
     throw zero_denominator{"divide by zero"};
   numerator_ *= rhs.denominator();
   denominator_ *= rhs.numerator();
   normalize();
   return *this;
 }
template<class T > rational< T > & rational< T >::operator/= (value_type const & rhs)
Division assignment operator.
Definition at line 245 of file rational.hpp.
References rational< T >::denominator_, and rational< T >::normalize().
 {
   if (rhs == value_type{})
     throw zero_denominator{"divide by zero"};
   denominator_ *= rhs;
   normalize();
   return *this;
 }
template<class T > rational< T > & rational< T >::operator= (value_type num)
Assignment of an integer.
Definition at line 165 of file rational.hpp.
References rational< T >::denominator_, and rational< T >::numerator_.
 {
   numerator_ = num;
   denominator_ = value_type{1};
   return *this;
 }
template<class T> template<class U > rational& rational< T >::operator= (rational< U > const & rhs)
Assignment of a rational with a different size.
template<class T> template<class U > rational<T>& rational< T >::operator= (rational< U > const & rhs)
Definition at line 174 of file rational.hpp.
References rational< T >::denominator(), rational< T >::denominator_, rational< T >::numerator(), rational< T >::numerator_, and rational< T >::reduce().
 {
   numerator_ = scale<U>(rhs.numerator());
   denominator_ = scale<U>(rhs.denominator());
   reduce();
   return *this;
 }
template<class T > void rational< T >::reduce () private
Reduce the numerator and denominator by their GCD.
Definition at line 155 of file rational.hpp.
References rational< T >::denominator(), rational< T >::denominator_, gcd(), rational< T >::numerator(), and rational< T >::numerator_.
Referenced by rational< T >::normalize(), rational< T >::operator*=(), rational< T >::operator+=(), rational< T >::operator-=(), rational< T >::operator=(), and rational< T >::rational().
 {
   value_type div{gcd(numerator(), denominator())};
   if (div == value_type{})
     throw zero_denominator{"zero denominator"};
   numerator_ /= div;
   denominator_ /= div;
 }
template<class T> template<class U > value_type rational< T >::scale (U value) private
Scale an integer of type U to the value_type. If U has more digits than value_type shift value to the right.
template<class T> template<class U > T rational< T >::scale (U value)
Definition at line 135 of file rational.hpp.
 {
   if (std::numeric_limits<T>::digits >= std::numeric_limits<U>::digits)
     return T{value};
   else
     return T{value >> (std::numeric_limits<U>::digits - std::numeric_limits<T>::digits)};
 }
Member Data Documentation
template<class T> value_type rational< T >::denominator_ private
Definition at line 109 of file rational.hpp.
Referenced by rational< long long >::denominator(), rational< T >::normalize(), rational< T >::operator*=(), rational< T >::operator+=(), rational< T >::operator-=(), rational< T >::operator/=(), rational< T >::operator=(), rational< T >::rational(), and rational< T >::reduce().
template<class T> constexpr value_type rational< T >::double_divisor = power10<value_type>(std::numeric_limits<value_type>::digits10 - 1) static private
Compute the divisor to use when converting a double to rational. This is the largest power of 10 that value_type can represent.
Definition at line 106 of file rational.hpp.
Referenced by rational< T >::rational().
template<class T> value_type rational< T >::numerator_ private
Definition at line 108 of file rational.hpp.
Referenced by rational< T >::normalize(), rational< long long >::numerator(), rational< T >::operator*=(), rational< T >::operator++(), rational< T >::operator+=(), rational< T >::operator--(), rational< T >::operator-=(), rational< T >::operator/=(), rational< T >::operator=(), and rational< T >::reduce().
The documentation for this class was generated from the following file:
rational.hpp