Calculator: number.hpp File Reference
number.hpp File Reference
#include <memory>
#include <ostream>
#include <string>
#include "rational.hpp"
Classes
class number
Functions
bool operator== (number a, number b)
bool operator!= (number a, number b)
bool operator< (number a, number b)
bool operator<= (number a, number b)
bool operator> (number a, number b)
bool operator>= (number a, number b)
number operator- (number n)
std::ostream & operator<< (std::ostream &stream, number n)
Function Documentation
bool operator!= (number a, number b) inline
Compare two number objects for numeric inequality. The objects are coerced to a common type before comparing.
Parameters
a The left-hand operand
b The right-hand operand
Returns
true if a != b (watch out for floating-point comparisons).
Definition at line 149 of file number.hpp.
 {
   return not (a == b);
 }
number operator- (number n) inline
Negate a number.
Parameters
n the number
Returns
-n
Definition at line 202 of file number.hpp.
 {
   return number{0} - n;
 }
bool operator< (number a, number b) inline
Compare two number objects for numeric less-than. The objects are coerced to a common type before comparing.
Parameters
a The left-hand operand
b The right-hand operand
Returns
true if a < b (watch out for floating-point comparisons).
Definition at line 160 of file number.hpp.
References number::less().
 {
   return a.less(b);
 }
std::ostream& operator<< (std::ostream & stream, number n) inline
Print a number
Parameters
stream The output stream
n The number to print
Definition at line 211 of file number.hpp.
References number::print().
 {
   n.print(stream);
   return stream;
 }
bool operator<= (number a, number b) inline
Compare two number objects for numeric less-than-or-equal. The objects are coerced to a common type before comparing.
Parameters
a The left-hand operand
b The right-hand operand
Returns
true if a <= b (watch out for floating-point comparisons).
Definition at line 171 of file number.hpp.
 {
   return not(b < a);
 }
bool operator== (number a, number b) inline
Compare two number objects for numeric equality. The objects are coerced to a common type before comparing.
Parameters
a The left-hand operand
b The right-hand operand
Returns
true if a == b (watch out for floating-point comparisons).
Definition at line 138 of file number.hpp.
References number::equals().
 {
   return a.equals(b);
 }
bool operator> (number a, number b) inline
Compare two number objects for numeric greater-than. The objects are coerced to a common type before comparing.
Parameters
a The left-hand operand
b The right-hand operand
Returns
true if a > b (watch out for floating-point comparisons).
Definition at line 182 of file number.hpp.
 {
   return b < a;
 }
bool operator>= (number a, number b) inline
Compare two number objects for numeric greater-than-or-equal. The objects are coerced to a common type before comparing.
Parameters
a The left-hand operand
b The right-hand operand
Returns
true if a >= b (watch out for floating-point comparisons).
Definition at line 193 of file number.hpp.
 {
   return not (a < b);
 }