Calculator: rational.hpp File Reference
rational.hpp File Reference
#include <istream>
#include <limits>
#include <ostream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <type_traits>
#include "gcd.hpp"
#include "ioflags.hpp"
#include "power10.hpp"
Classes
class zero_denominator
Exception class if the denominator is ever zero.
class rational< T >
Represent a rational number (fraction) as a numerator and denominator.
Functions
template<class T >
rational< T > operator- (rational< T > const &r)
Negate a rational number.
template<class T >
rational< T > absval (rational< T > const &r)
template<class T >
rational< T > operator+ (rational< T > lhs, rational< T > const &rhs)
Addition.
template<class T >
rational< T > operator+ (rational< T > lhs, T const &rhs)
Addition.
template<class T >
rational< T > operator+ (T const &lhs, rational< T > rhs)
Addition.
template<class T >
rational< T > operator- (rational< T > lhs, rational< T > const &rhs)
Subtraction.
template<class T >
rational< T > operator- (rational< T > lhs, T const &rhs)
Subtraction.
template<class T >
rational< T > operator- (T const &lhs, rational< T > rhs)
Subtraction.
template<class T >
rational< T > operator* (rational< T > lhs, rational< T > const &rhs)
Multiplication.
template<class T >
rational< T > operator* (rational< T > lhs, T const &rhs)
Multiplication.
template<class T >
rational< T > operator* (T const &lhs, rational< T > rhs)
Multiplication.
template<class T >
rational< T > operator/ (rational< T > lhs, rational< T > const &rhs)
Division.
template<class T >
rational< T > operator/ (rational< T > lhs, T const &rhs)
Division.
template<class T >
rational< T > operator/ (T const &lhs, rational< T > rhs)
Division.
template<class T , class U >
bool operator== (rational< T > const &a, rational< U > const &b)
Equality comparison.
template<class T >
bool operator== (rational< T > const &lhs, T rhs)
Equality comparison.
template<class T >
bool operator== (T lhs, rational< T > const &rhs)
Equality comparison.
template<class T >
bool operator< (rational< T > const &a, rational< T > const &b)
Less-than comparison.
template<class T >
bool operator< (rational< T > const &a, T const &b)
Less-than comparison.
template<class T >
bool operator< (T const &a, rational< T > const &b)
Less-than comparison.
template<class T , class U >
bool operator!= (rational< T > const &a, rational< U > const &b)
Inequality comparison.
template<class T >
bool operator!= (rational< T > const &a, T b)
Inequality comparison.
template<class T >
bool operator!= (T a, rational< T > const &b)
Inequality comparison.
template<class T >
bool operator<= (rational< T > const &a, rational< T > const &b)
Less-than-or-equal comparison.
template<class T >
bool operator<= (rational< T > const &a, T const &b)
Less-than-or-equal comparison.
template<class T >
bool operator<= (T const &a, rational< T > const &b)
Less-than-or-equal comparison.
template<class T >
bool operator> (rational< T > const &a, rational< T > const &b)
Greater-than comparison.
template<class T >
bool operator> (rational< T > const &a, T const &b)
Greater-than comparison.
template<class T >
bool operator> (T const &a, rational< T > const &b)
Greater-than comparison.
template<class T >
bool operator>= (rational< T > const &a, rational< T > const &b)
Greater-than-or-equal comparison.
template<class T >
bool operator>= (rational< T > const &a, T const &b)
Greater-than-or-equal comparison.
template<class T >
bool operator>= (T const &a, rational< T > const &b)
Greater-than-or-equal comparison.
template<class T , class Char , class Traits >
std::basic_istream< Char,
Traits > & operator>> (std::basic_istream< Char, Traits > &in, rational< T > &rat)
Input operator.
template<class T , class Char , class Traits >
std::basic_ostream< Char,
Traits > & operator<< (std::basic_ostream< Char, Traits > &out, rational< T > const &rat)
Output operator.
Function Documentation
template<class T > rational<T> absval (rational< T > const & r)
Definition at line 292 of file rational.hpp.
References rational< T >::denominator(), and rational< T >::numerator().
 {
   using std::abs;
   return rational<T>{abs(r.numerator()), r.denominator()};
 }
template<class T , class U > bool operator!= (rational< T > const & a, rational< U > const & b) inline
Inequality comparison.
Definition at line 442 of file rational.hpp.
 {
   return not (a == b);
 }
template<class T > bool operator!= (rational< T > const & a, T b) inline
Inequality comparison.
Definition at line 449 of file rational.hpp.
 {
   return not (a == b);
 }
template<class T > bool operator!= (T a, rational< T > const & b) inline
Inequality comparison.
Definition at line 456 of file rational.hpp.
 {
   return not (a == b);
 }
template<class T > rational<T> operator* (rational< T > lhs, rational< T > const & rhs)
Multiplication.
Definition at line 349 of file rational.hpp.
 {
   lhs *= rhs;
   return lhs;
 }
template<class T > rational<T> operator* (rational< T > lhs, T const & rhs)
Multiplication.
Definition at line 357 of file rational.hpp.
 {
   lhs *= rhs;
   return lhs;
 }
template<class T > rational<T> operator* (T const & lhs, rational< T > rhs)
Multiplication.
Definition at line 365 of file rational.hpp.
 {
   rhs *= lhs;
   return rhs;
 }
template<class T > rational<T> operator+ (rational< T > lhs, rational< T > const & rhs)
Addition.
Definition at line 300 of file rational.hpp.
 {
   lhs += rhs;
   return lhs;
 }
template<class T > rational<T> operator+ (rational< T > lhs, T const & rhs)
Addition.
Definition at line 308 of file rational.hpp.
 {
   lhs += rhs;
   return lhs;
 }
template<class T > rational<T> operator+ (T const & lhs, rational< T > rhs)
Addition.
Definition at line 316 of file rational.hpp.
 {
   rhs += lhs;
   return rhs;
 }
template<class T > rational<T> operator- (rational< T > const & r)
Negate a rational number.
Definition at line 286 of file rational.hpp.
References rational< T >::denominator(), and rational< T >::numerator().
 {
   return rational<T>{-r.numerator(), r.denominator()};
 }
template<class T > rational<T> operator- (rational< T > lhs, rational< T > const & rhs)
Subtraction.
Definition at line 324 of file rational.hpp.
 {
   lhs -= rhs;
   return lhs;
 }
template<class T > rational<T> operator- (rational< T > lhs, T const & rhs)
Subtraction.
Definition at line 332 of file rational.hpp.
 {
   lhs -= rhs;
   return lhs;
 }
template<class T > rational<T> operator- (T const & lhs, rational< T > rhs)
Subtraction.
Definition at line 340 of file rational.hpp.
 {
   // Gotta be a little tricky.
   rhs += -lhs;
   return -rhs;
 }
template<class T > rational<T> operator/ (rational< T > lhs, rational< T > const & rhs)
Division.
Definition at line 373 of file rational.hpp.
 {
   lhs /= rhs;
   return lhs;
 }
template<class T > rational<T> operator/ (rational< T > lhs, T const & rhs)
Division.
Definition at line 381 of file rational.hpp.
 {
   lhs /= rhs;
   return lhs;
 }
template<class T > rational<T> operator/ (T const & lhs, rational< T > rhs)
Division.
Definition at line 389 of file rational.hpp.
References rational< T >::denominator(), and rational< T >::numerator().
 {
   return rational<T>{lhs * rhs.denominator(), rhs.numerator()};
 }
template<class T > bool operator< (rational< T > const & a, rational< T > const & b)
Less-than comparison.
Definition at line 421 of file rational.hpp.
References rational< T >::numerator().
 {
   return a.numerator() * b.denominator() < b.numerator() * a.denominator();
 }
template<class T > bool operator< (rational< T > const & a, T const & b)
Less-than comparison.
Definition at line 428 of file rational.hpp.
 {
   return a.numerator() < b * a.denominator();
 }
template<class T > bool operator< (T const & a, rational< T > const & b)
Less-than comparison.
Definition at line 435 of file rational.hpp.
 {
   return a * b.denominator() < b.numerator();
 }
template<class T , class Char , class Traits > std::basic_ostream<Char, Traits>& operator<< (std::basic_ostream< Char, Traits > & out, rational< T > const & rat)
Output operator.
Definition at line 562 of file rational.hpp.
References rational< T >::numerator().
 {
   typename std::basic_ostream<Char, Traits>::sentry sentry{out};
   std::ostringstream stream;
   stream << rat.numerator() << '/' << rat.denominator();
   out << stream.str();
   return out;
 }
template<class T > bool operator<= (rational< T > const & a, rational< T > const & b) inline
Less-than-or-equal comparison.
Definition at line 463 of file rational.hpp.
 {
   return not (b < a);
 }
template<class T > bool operator<= (rational< T > const & a, T const & b) inline
Less-than-or-equal comparison.
Definition at line 470 of file rational.hpp.
 {
   return not (b < a);
 }
template<class T > bool operator<= (T const & a, rational< T > const & b) inline
Less-than-or-equal comparison.
Definition at line 477 of file rational.hpp.
 {
   return not (b < a);
 }
template<class T , class U > bool operator== (rational< T > const & a, rational< U > const & b)
Equality comparison.
Definition at line 397 of file rational.hpp.
References rational< T >::denominator(), and rational< T >::numerator().
 {
   return a.numerator() == b.numerator() and
          a.denominator() == b.denominator();
 }
template<class T > bool operator== (rational< T > const & lhs, T rhs)
Equality comparison.
Definition at line 405 of file rational.hpp.
References rational< T >::denominator(), and rational< T >::numerator().
 {
   return lhs.denominator() == 1 and
          lhs.numerator()   == rhs;
 }
template<class T > bool operator== (T lhs, rational< T > const & rhs)
Equality comparison.
Definition at line 413 of file rational.hpp.
References rational< T >::denominator(), and rational< T >::numerator().
 {
   return rhs.denominator() == 1 and
          rhs.numerator()   == lhs;
 }
template<class T > bool operator> (rational< T > const & a, rational< T > const & b) inline
Greater-than comparison.
Definition at line 484 of file rational.hpp.
 {
   return b < a;
 }
template<class T > bool operator> (rational< T > const & a, T const & b) inline
Greater-than comparison.
Definition at line 491 of file rational.hpp.
 {
   return b < a;
 }
template<class T > bool operator> (T const & a, rational< T > const & b) inline
Greater-than comparison.
Definition at line 498 of file rational.hpp.
 {
   return b < a;
 }
template<class T > bool operator>= (rational< T > const & a, rational< T > const & b) inline
Greater-than-or-equal comparison.
Definition at line 505 of file rational.hpp.
 {
   return not (b > a);
 }
template<class T > bool operator>= (rational< T > const & a, T const & b) inline
Greater-than-or-equal comparison.
Definition at line 512 of file rational.hpp.
 {
   return not (b > a);
 }
template<class T > bool operator>= (T const & a, rational< T > const & b) inline
Greater-than-or-equal comparison.
Definition at line 519 of file rational.hpp.
 {
   return not (b > a);
 }
template<class T , class Char , class Traits > std::basic_istream<Char, Traits>& operator>> (std::basic_istream< Char, Traits > & in, rational< T > & rat)
Input operator.
Definition at line 526 of file rational.hpp.
 {
   typename std::basic_istream<Char, Traits>::sentry sentry{in, false};
   ioflags flags{in};
   T n{};
   if (not (in >> n))
     // Error reading the numerator.
     return in;
   in >> std::noskipws;
   char sep{};
   if (not (in >> sep))
     // Error reading the separator character.
     return in;
   else if (sep != '/')
   {
     // Push sep back into the input stream, so the next input operation
     // will read it.
     in.unget();
     rat = n;
     return in;
   }
   else
   {
     T d{};
     if (in >> d)
       // Successfully read numerator, separator, and denominator.
       rat = rational<T>{n, d};
   }
   return in;
 }