######################################################################
# Automatically generated by qmake (2.01a) sö 15. apr 16:10:32 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
