######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 4 19:11:36 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
