//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DCEXPLORER.RC
//

#define IDD_ABOUTBOX                    100
#define IDS_PLATFORM_WIN32_NT           110
#define IDS_PLATFORM_WIN32_NTAS         111
#define IDD_DEMO                        111
#define IDD_BRICKS                      111
#define IDS_PLATFORM_WIN32_NTW          112
#define IDB_BRICKS                      112
#define IDS_PLATFORM_WIN32_NTS          113
#define IDS_PLATFORM_WIN32s             114
#define IDS_PLATFORM_WIN32_WINDOWS      115
#define IDS_PLATFORM_UNKNOWN            116
#define IDS_PLATFORM_WIN32_NT2          117
#define IDS_PLATFORM_WIN32_NTAS2        118
#define IDS_PLATFORM_WIN32_NTW2         119
#define IDS_PROCESSOR_ARCHITECTURE_UNKNOWN 120
#define IDS_PROCESSOR_ARCHITECTURE_INTEL_386_486 121
#define IDS_PROCESSOR_ARCHITECTURE_INTEL_PENTIUM 122
#define IDS_PROCESSOR_ARCHITECTURE_ALPHA 123
#define IDS_PROCESSOR_ARCHITECTURE_MIPS 124
#define IDS_PROCESSOR_ARCHITECTURE_PPC  125
#define IDS_PROCESSOR_LEVEL_INTEL_UNKNOWN 126
#define IDS_PROCESSOR_LEVEL_ALPHA_UNKNOWN 127
#define IDR_MAINFRAME			128
#define IDR_DCEXPLTYPE			129
#define IDI_JMNCO                       130
#define IDS_PLATFORM_WIN32_NT3          130
#define IDD_BACKGROUND                  131
#define IDD_TEXT                        132
#define IDD_MAPPING                     133
#define IDD_PEN                         134
#define IDD_XFORM                       135
#define IDD_ROP2                        136
#define IDI_ICON1                       137
#define IDD_ALIGNMENT                   138
#define IDC_SELF                        139
#define IDD_DEVICECAPS                  139
#define IDC_CANDUMP                     140
#define IDD_PALETTE                     141
#define IDD_BKGSAMPLE                   142
#define IDS_PROCESSOR_LEVEL_MIPS_UNKNOWN 143
#define IDC_DUMPING1                    143
#define IDS_PROCESSOR_LEVEL_PPC_UNKNOWN 144
#define IDC_DUMPING2                    144
#define IDS_PROCESSOR_NOREV_INTEL_386   145
#define IDC_DUMPED                      145
#define IDS_PROCESSOR_NOREV_INTEL_486   146
#define IDC_DUMPING3                    146
#define IDS_PROCESSOR_NOREV_INTEL_PENTIUM 147
#define IDC_DUMPING4                    147
#define IDS_PROCESSOR_NOREV_MIPS_R4000  148
#define IDS_PROCESSOR_NOREV_ALPHA_21064 149
#define IDS_MM_TEXT                     150
#define IDS_MM_HIENGLISH                151
#define IDS_MM_LOENGLISH                152
#define IDS_MM_HIMETRIC                 153
#define IDS_MM_LOMETRIC                 154
#define IDS_MM_TWIPS                    155
#define IDS_MM_ISOTROPIC                156
#define IDS_MM_ANISOTROPIC              157
#define IDS_OEM_FIXED_FONT              158
#define IDS_ANSI_FIXED_FONT             159
#define IDS_ANSI_VAR_FONT               160
#define IDS_SYSTEM_FONT                 161
#define IDS_DEVICE_DEFAULT_FONT         162
#define IDS_RED                         168
#define IDS_GREEN                       169
#define IDS_BLUE                        170
#define IDS_CYAN                        171
#define IDS_MAGENTA                     172
#define IDS_YELLOW                      173
#define IDS_BLACK                       174
#define IDS_GRAY                        175
#define IDS_WHITE                       176
#define IDS_LTGRAY                      177
#define IDS_DKGRAY                      178
#define IDS_TEAL                        179
#define IDS_LIME                        180
#define IDS_MAROON                      181
#define IDS_OLIVE                       182
#define IDS_PURPLE                      183
#define IDS_NAVY                        184
#define IDS_PALEGREEN                   185
#define IDS_SKYBLUE                     186
#define IDS_CREAM                       187
#define IDS_MDGRAY                      188
#define IDS_DMORIENT_LANDSCAPE          200
#define IDS_DMORIENT_PORTRAIT           201
#define IDS_DMCOLOR_COLOR               202
#define IDS_DMCOLOR_MONOCHROME          203
#define IDS_DMDUP_SIMPLEX               204
#define IDS_DMDUP_HORIZONTAL            205
#define IDS_DMDUP_VERTICAL              206
#define IDS_DMRES_HIGH                  207
#define IDS_DMRES_MEDIUM                208
#define IDS_DMRES_LOW                   209
#define IDS_DMRES_DRAFT                 210
#define IDS_DMTT_BITMAP                 211
#define IDS_DMTT_DOWNLOAD               212
#define IDS_DMTT_SUBDEV                 213
#define IDS_DMCOLLATE_TRUE              214
#define IDS_DMCOLLATE_FALSE             215
#define IDS_DMGRAYSCALE                 216
#define IDS_DMINTERLACED                217
#define IDS_NO_DC                       218
#define IDS_DT_PLOTTER                  222
#define IDS_DT_RASDISPLAY               223
#define IDS_DT_RASPRINTER               224
#define IDS_DT_RASCAMERA                225
#define IDS_DT_CHARSTREAM               226
#define IDS_DT_METAFILE                 227
#define IDS_DT_DISPFILE                 228
#define IDS_RC_BANDING                  229
#define IDS_RC_BITBLT                   230
#define IDS_RC_BITMAP64                 231
#define IDS_RC_DI_BITMAP                232
#define IDS_RC_DIBTODEV                 233
#define IDS_RC_FLOODFILL                234
#define IDS_RC_GDI20_OUTPUT             235
#define IDS_RC_PALETTE                  236
#define IDS_RC_SCALING                  237
#define IDS_RC_STRETCHBLT               238
#define IDS_RC_STRETCHDIB               239
#define IDS_CC_NONE                     240
#define IDS_CC_CIRCLES                  241
#define IDS_CC_PIE                      242
#define IDS_CC_CHORD                    243
#define IDS_CC_ELLIPSES                 244
#define IDS_CC_WIDE                     245
#define IDS_CC_STYLED                   246
#define IDS_CC_WIDESTYLED               247
#define IDS_CC_INTERIORS                248
#define IDS_LC_NONE                     249
#define IDS_LC_POLYLINE                 250
#define IDS_LC_MARKER                   251
#define IDS_LC_POLYMARKER               252
#define IDS_LC_WIDE                     253
#define IDS_LC_STYLED                   254
#define IDS_LC_WIDESTYLED               255
#define IDS_LC_INTERIORS                256
#define IDS_PC_NONE                     257
#define IDS_PC_POLYGON                  258
#define IDS_PC_RECTANGLE                259
#define IDS_PC_WINDPOLYGON              260
#define IDS_PC_SCANLINE                 261
#define IDS_PC_WIDE                     262
#define IDS_PC_STYLED                   263
#define IDS_PC_WIDESTYLED               264
#define IDS_PC_INTERIORS                265
#define IDS_TC_OP_CHARACTER             266
#define IDS_TC_OP_STROKE                267
#define IDS_TC_CP_STROKE                268
#define IDS_TC_CR_90                    269
#define IDS_TC_CR_ANY                   270
#define IDS_TC_SF_X_YINDEP              271
#define IDS_TC_SA_DOUBLE                272
#define IDS_TC_SA_INTEGER               273
#define IDS_TC_SA_CONTIN                274
#define IDS_TC_EA_DOUBLE                275
#define IDS_TC_IA_ABLE                  276
#define IDS_TC_UA_ABLE                  277
#define IDS_TC_SO_ABLE                  278
#define IDS_TC_RA_ABLE                  279
#define IDS_TC_VA_ABLE                  280
#define IDS_TC_RESERVED                 281
#define IDS_TC_SCROLLBLT                282
#define IDS_CC_ROUNDRECT                283
#define IDS_RC_SAVEBITMAP               284
#define IDS_RC_BIGFONT                  285
#define IDS_PC_POLYPOLYGON              286
#define IDS_PC_PATHS                    287
#define IDS_RC_OP_DX_OUTPUT             288
#define IDS_RC_DEVBITS                  289
#define IDS_PC_TRAPEZOID                290
#define IDS_RC_GDI20_STATE              291
#define IDS_THIN                        300
#define IDS_EXTRALIGHT                  301
#define IDS_LIGHT                       302
#define IDS_NORMAL                      303
#define IDS_MEDIUM                      304
#define IDS_SEMIBOLD                    305
#define IDS_BOLD                        306
#define IDS_EXTRABOLD                   307
#define IDS_HEAVY                       308
#define IDS_COLOR_SCROLLBAR             330
#define IDS_COLOR_BACKGROUND            331
#define IDS_COLOR_ACTIVECAPTION         332
#define IDS_COLOR_INACTIVECAPTION       333
#define IDS_COLOR_MENU                  334
#define IDS_COLOR_WINDOW                335
#define IDS_COLOR_WINDOWFRAME           336
#define IDS_COLOR_MENUTEXT              337
#define IDS_COLOR_WINDOWTEXT            338
#define IDS_COLOR_CAPTIONTEXT           339
#define IDS_COLOR_ACTIVEBORDER          340
#define IDS_COLOR_INACTIVEBORDER        341
#define IDS_COLOR_APPWORKSPACE          342
#define IDS_COLOR_HIGHLIGHT             343
#define IDS_COLOR_HIGHLIGHTTEXT         344
#define IDS_COLOR_BTNFACE               345
#define IDS_COLOR_BTNSHADOW             346
#define IDS_COLOR_GRAYTEXT              347
#define IDS_COLOR_BTNTEXT               348
#define IDS_COLOR_INACTIVECAPTIONTEXT   349
#define IDS_COLOR_BTNHIGHLIGHT          350
#define IDS_COLOR_3DDKSHADOW            351
#define IDS_COLOR_3DLIGHT               352
#define IDS_COLOR_INFOTEXT              353
#define IDS_COLOR_INFOBK                354
#define IDS_COLOR_DESKTOP               355
#define IDS_COLOR_3DFACE                356
#define IDS_COLOR_3DSHADOW              357
#define IDS_COLOR_3DHIGHLIGHT           358
#define IDS_R2_BLACK                    400
#define IDS_R2_NOTMERGEPEN              401
#define IDS_R2_MASKNOTPEN               402
#define IDS_R2_NOTCOPYPEN               403
#define IDS_R2_MASKPENNOT               404
#define IDS_R2_NOT                      405
#define IDS_R2_XORPEN                   406
#define IDS_R2_NOTMASKPEN               407
#define IDS_R2_MASKPEN                  408
#define IDS_R2_NOTXORPEN                409
#define IDS_R2_NOP                      410
#define IDS_R2_MERGENOTPEN              411
#define IDS_R2_COPYPEN                  412
#define IDS_R2_MERGEPENNOT              413
#define IDS_R2_MERGEPEN                 414
#define IDS_R2_WHITE                    415
#define IDS_HS_HORIZONTAL               420
#define IDS_HS_VERTICAL                 421
#define IDS_HS_CROSS                    422
#define IDS_HS_FDIAGONAL                423
#define IDS_HS_BDIAGONAL                424
#define IDS_HS_DIAGCROSS                425
#define IDS_WHITE_BRUSH                 430
#define IDS_LTGRAY_BRUSH                431
#define IDS_GRAY_BRUSH                  432
#define IDS_DKGRAY_BRUSH                433
#define IDS_BLACK_BRUSH                 434
#define IDS_NULL_BRUSH                  435
#define IDS_BLACK_PEN                   436
#define IDS_WHITE_PEN                   437
#define IDS_NULL_PEN                    438
#define IDS_PS_SOLID                    439
#define IDS_PS_DASH                     440
#define IDS_PS_DOT                      441
#define IDS_PS_DASHDOT                  442
#define IDS_PS_NULL                     443
#define IDS_PS_INSIDEFRAME              444
#define IDS_PS_ALTERNATE                445
#define IDS_PS_USERSTYLE                446
#define IDS_PS_ENDCAP_ROUND             447
#define IDS_PS_ENDCAP_SQUARE            448
#define IDS_PS_ENDCAP_FLAT              449
#define IDS_PS_JOIN_BEVEL               450
#define IDS_PS_JOIN_MITER               451
#define IDS_PS_JOIN_ROUND               452
#define IDS_PS_DASHDOTDOT               453
#define IDS_BS_SOLID                    454
#define IDS_BRICKS                      455
#define IDS_GRAPHIC_EXAMPLE             500
#define IDS_STAR_CAPTION                501
#define IDS_TEXT_BASE                   502
#define IDS_STRING503                   503
#define IDS_STRING504                   504
#define IDS_STRING505                   505
#define IDS_TEXT_LIMIT                  506
#define IDC_BKCOLOR                     1001
#define IDC_OPAQUE                      1002
#define IDC_TRANSPARENT                 1003
#define IDC_ABOUT_OSVERSION             1004
#define IDC_WNDCOLOR                    1004
#define IDC_STOCKBRUSH                  1005
#define IDC_SOLIDBRUSH                  1006
#define IDC_ABOUT_PROCESSORVERSION      1006
#define IDC_HATCHBRUSH                  1007
#define IDC_STOCKBRUSHES                1008
#define IDC_ABOUT_FILEDESCRIPTION       1008
#define IDC_SOLIDBRUSHES                1009
#define IDC_ABOUT_VERSION               1009
#define IDC_HATCHBRUSHES                1010
#define IDC_ABOUT_LEGALCOPYRIGHT        1010
#define IDC_BRUSHORGX                   1011
#define IDC_ABOUT_LEGALTRADEMARKS       1011
#define IDC_BRUSHORGY                   1012
#define IDC_ABOUT_COMMENTS              1012
#define IDC_XFORM_CAPTION               1012
#define IDC_TEXTCOLOR                   1013
#define IDC_CUSTOMFONT                  1014
#define IDC_FONTNAME                    1015
#define IDC_ALTERNATE                   1015
#define IDC_WINDING                     1016
#define IDC_STOCKPENS                   1018
#define IDC_STOCKFONTS                  1019
#define IDC_SOLIDPEN                    1019
#define IDC_STOCKFONT                   1020
#define IDC_SOLIDPENS                   1020
#define IDC_PENORGX                     1021
#define IDC_PENORGY                     1022
#define IDC_ENDCAPS                     1023
#define IDC_LINEJOIN                    1024
#define IDC_RASTEROP                    1025
#define IDC_BRUSHSTYLE                  1025
#define IDC_RESULT                      1025
#define IDC_M11                         1026
#define IDC_PENWIDTH                    1026
#define IDC_M12                         1027
#define IDC_STOCKPEN                    1027
#define IDC_COSMETIC                    1028
#define IDC_M21                         1028
#define IDC_GEOMETRIC                   1029
#define IDC_M22                         1029
#define IDC_DX                          1030
#define IDC_PENSTYLES                   1030
#define IDC_DY                          1031
#define IDC_MITERLIMIT                  1031
#define IDC_MAPPINGMODE                 1032
#define IDC_SIN                         1032
#define IDC_MITERANGLE                  1032
#define IDC_COS                         1033
#define IDC_VORGX                       1034
#define IDC_ASIN                        1034
#define IDC_VORGY                       1035
#define IDC_ACOS                        1035
#define IDC_VEXTX                       1036
#define IDC_DEGREES                     1036
#define IDC_VEXTY                       1037
#define IDC_CHANGEFONT                  1037
#define IDC_VALUE                       1037
#define IDC_WORGX                       1038
#define IDC_COMPATIBLE                  1038
#define IDC_WORGY                       1039
#define IDC_ADVANCED                    1039
#define IDC_WEXTX                       1040
#define IDC_IDENTITY                    1040
#define IDC_WEXTY                       1041
#define IDC_TAN                         1041
#define IDC_SCALING                     1042
#define IDC_SHOWROP                     1042
#define IDC_2TAN                        1042
#define IDC_SX                          1043
#define IDC_ATAN                        1043
#define IDC_SY                          1044
#define IDC_SAMPLE                      1045
#define IDC_TOP                         1046
#define IDC_POLYEXAMPLE                 1046
#define IDC_PENSPIN                     1047
#define IDC_BRUSHEXAMPLE                1047
#define IDC_BASELINE                    1047
#define IDC_PENSAMPLE                   1048
#define IDC_BOTTOM                      1048
#define IDC_LEFT                        1049
#define IDC_MITERSPIN                   1049
#define IDC_TEXTSAMPLE                  1050
#define IDC_CENTER                      1050
#define IDC_MITERANGLESPIN              1050
#define IDC_COLOR_CAPTION               1051
#define IDC_GRAPHICSAMPLE               1051
#define IDC_RIGHT                       1051
#define IDC_BRUSH_CAPTION               1052
#define IDC_ENDCAPS_CAPTION             1053
#define IDC_LINEJOIN_CAPTION            1054
#define IDC_PENSTYLE_CAPTION            1055
#define IDC_ORIGIN_CAPTION              1055
#define IDC_TRIG_CAPTION                1056
#define IDC_DEGREES_CAPTION             1057
#define IDC_ERROR                       1059
#define IDC_UPDATECP                    1062
#define IDC_RTLREADING                  1063
#define IDC_SPIN12                      1064
#define IDC_SPIN22                      1065
#define IDC_SPINDY                      1066
#define IDC_SPIN11                      1067
#define IDC_SPIN21                      1068
#define IDC_SPINDX                      1069
#define IDC_ROTATE                      1070
#define IDC_HSHEAR                      1071
#define IDC_10                          1072
#define IDC_VSHEAR                      1072
#define IDC_100                         1073
#define IDC_1000                        1074
#define IDC_VEXT_CAPTION                1076
#define IDC_WEXT_CAPTION                1077
#define IDC_VSCROLL                     1078
#define IDC_HSCROLL                     1079
#define IDC_DRIVERVERSION               1079
#define IDC_WIDTH_CAPTION               1080
#define IDC_TECHNOLOGY                  1080
#define IDC_OPERATIONS                  1081
#define IDC_HORZSIZE                    1081
#define IDC_MITER_CAPTION               1081
#define IDC_HATCHSAMPLE                 1082
#define IDC_VERTSIZE                    1082
#define IDC_SPINX                       1083
#define IDC_HORZRES                     1083
#define IDC_SPINY                       1084
#define IDC_ROP2                        1084
#define IDC_VERTRES                     1084
#define IDC_LOGPIXELSX                  1085
#define IDC_TEXTCHAREXTRA               1085
#define IDC_LOGPIXELSY                  1086
#define IDC_SPINCHAREXTRA               1086
#define IDC_BITSPIXEL                   1087
#define IDC_PALETTE                     1087
#define IDC_PLANES                      1088
#define IDC_RGB                         1088
#define IDC_NUMBRUSHES                  1089
#define IDC_ANGLE_CAPTION               1089
#define IDC_NUMPENS                     1090
#define IDC_SHOW                        1090
#define IDC_NUMFONTS                    1091
#define IDC_RECT                        1091
#define IDC_NUMCOLORS                   1092
#define IDC_BRICKS                      1092
#define IDC_ASPECTX                     1093
#define IDC_COPY                        1093
#define IDC_ASPECTY                     1094
#define IDC_PDEVICESIZE                 1095
#define IDC_CLIPCAPS                    1096
#define IDC_SIZEPALETTE                 1097
#define IDC_NUMRESERVED                 1098
#define IDC_COLORRES                    1099
#define IDC_ASPECTXY                    1101
#define IDC_C_SIZEPALETTE               1102
#define IDC_RASTERCAPS                  1103
#define IDC_CURVECAPS                   1104
#define IDC_LINECAPS                    1105
#define IDC_POLYGONALCAPS               1106
#define IDC_TEXTCAPS                    1107
#define IDM_HATCHED_BRUSH               32771
#define IDM_DC_EXP                      32772
#define ID_TEXT                         32773
#define ID_LINES                        32774
#define ID_FILLEDFIG                    32775
#define ID_POLYGON                      32776
#define IDM_BRICKS                      32781

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1094
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
