######################################################################
# Automatically generated by qmake (2.01a) lö 21. okt 18:14:24 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mulmodel.h
SOURCES += mulmodel.cpp main.cpp
