//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by HttpServer.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_HTTPSERVER_DIALOG           102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDC_BTN_SERVER                  1000
#define IDC_BTN_STOP                    1002
#define IDC_LIST_INFO                   1003
#define IDC_STATIC_STATUS               1005
#define IDC_BTN_SETPATH                 1006
#define IDC_STATIC_PATH                 1007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
