######################################################################
# Automatically generated by qmake (2.01a) lö 9. sep 14:12:57 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += buttondialog.h
SOURCES += buttondialog.cpp main.cpp
