######################################################################
# Automatically generated by qmake (2.00a) to 10. aug 17:06:34 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += anything.cpp
CONFIG += console 
