######################################################################
# Automatically generated by qmake (2.01a) ti 17. apr 20:40:12 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h mybutton.h
FORMS += dialog.ui
SOURCES += dialog.cpp main.cpp mybutton.cpp
