//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MessageBoxColor.rc
//
#define IDS_PROGNAME                    1
#define IDM_GRAYMSGBOX                  100
#define IDM_REDMSGBOX                   101
#define IDB_PLAID                       101
#define IDB_PLAID800                    102
#define IDI_MAINFRAME                   103
#define IDB_PLAID8                      104
#define IDB_PLAID8X8                    106
#define ID_EXIT                         40001
#define IDM_PLAIDBOX                    40002

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40003
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
