######################################################################
# Automatically generated by qmake (2.01a) lö 11. nov 18:58:04 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
CONFIG += console 
