######################################################################
# Automatically generated by qmake (2.01a) to 18. jan 13:28:11 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
CONFIG += console 
