######################################################################
# Automatically generated by qmake (2.01a) to 1. feb 15:14:26 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += clientdialog.h
FORMS += clientdialog.ui
SOURCES += clientdialog.cpp main.cpp
QT += network 
CONFIG += console 
