######################################################################
# Automatically generated by qmake (2.01a) fr 16. mar 19:38:14 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += listener.h
SOURCES += listener.cpp main.cpp
QT += network 
CONFIG += console 
