######################################################################
# Automatically generated by qmake (2.01a) on 18. okt 20:30:04 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += bardelegate.h
SOURCES += bardelegate.cpp main.cpp
