// Machine generated IDispatch wrapper class(es) created with ClassWizard
/////////////////////////////////////////////////////////////////////////////
// IText wrapper class

class IText : public COleDispatchDriver
{
public:
    IText() {}      // Calls COleDispatchDriver default constructor
    IText(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
    IText(const IText& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
    VARIANT GetText();
    void SetText(const VARIANT&);

// Operations
public:
};
