######################################################################
# Automatically generated by qmake (2.01a) to 4. jan 09:51:01 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
