######################################################################
# Automatically generated by qmake (2.01a) on 25. okt 19:15:29 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += numerickeypad.h
SOURCES += main.cpp numerickeypad.cpp
