######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 22 19:28:09 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += opengl 
