######################################################################
# Automatically generated by qmake (2.01a) ti 2. jan 19:20:40 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += processdialog.h
FORMS += processdialog.ui
SOURCES += main.cpp processdialog.cpp
CONFIG += console 
