//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by print.rc
//
#define IDD_ABORT                       138
#define IDS_PRINTING_PAGE               286
#define IDC_PRINTER                     1104
#define IDC_PORT                        1105
#define IDC_PAGE                        1106
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
