Calculator: node_function Class Reference
node_function Class Reference
#include <node_impl.hpp>
Public Member Functions
node_function (identifier_list parameters, node definition)
node_function (std::istream &stream)
identifier_list const & parameters () const
node definition () const
Public Member Functions inherited from node_impl
node_impl ()
virtual ~node_impl ()
void print (std::ostream &stream, int indent) const
double evaluate () const
std::string to_string () const
identifier_list const & get_parameters () const
void save (std::ostream &stream) const
Private Member Functions
virtual void print_node (std::ostream &stream, int indent) const override
virtual double evaluate_node () const override
virtual identifier_list const & evaluate_parameters () const override
virtual void save_node (std::ostream &stream) const override
Private Attributes
identifier_list parameters_
node definition_
Additional Inherited Members
Static Public Member Functions inherited from node_impl
static std::shared_ptr< node_impl > read_node (std::istream &stream)
Detailed Description
Function definition. A function has parameters and a definition.
Definition at line 98 of file node_impl.hpp.
Constructor & Destructor Documentation
node_function::node_function (identifier_list parameters, node definition)
Definition at line 203 of file node_impl.cpp.
 : node_impl{}, parameters_{std::move(parameters)}, definition_(definition)
 {}
node_function::node_function (std::istream & stream)
Definition at line 207 of file node_impl.cpp.
 : node_impl{}
 {
   std::size_t size{};
   if (not (stream >> size))
     throw calc_error{"malformed library file, cannot read function"};
   parameters_.reserve(size);
   while (size-- != 0) {
     std::string parameter{};
     if (not (stream >> parameter))
       throw calc_error{"malformed library file, cannot read function parameter"};
     parameters_.emplace_back(std::move(parameter));
   }
   definition_ = node(stream);
 }
Member Function Documentation
node node_function::definition () const
Definition at line 229 of file node_impl.cpp.
References definition_.
Referenced by evaluate_node(), print_node(), and save_node().
 {
   return definition_;
 }
double node_function::evaluate_node () const override private virtual
Implements node_impl.
Definition at line 255 of file node_impl.cpp.
References definition(), and node::evaluate().
 {
   return definition().evaluate();
 }
identifier_list const & node_function::evaluate_parameters () const override private virtual
Reimplemented from node_impl.
Definition at line 261 of file node_impl.cpp.
References parameters().
 {
   return parameters();
 }
identifier_list const & node_function::parameters () const
Definition at line 223 of file node_impl.cpp.
References parameters_.
Referenced by evaluate_parameters(), print_node(), and save_node().
 {
   return parameters_;
 }
void node_function::print_node (std::ostream & stream, int indent) const override private virtual
Implements node_impl.
Definition at line 246 of file node_impl.cpp.
References definition(), parameters(), node::print(), and print_identifier_list().
 {
   stream << std::setw(indent) << "" << "fun\n";
   print_identifier_list(stream, parameters());
   stream << '=';
   definition().print(stream, indent + 2);
 }
void node_function::save_node (std::ostream & stream) const override private virtual
Implements node_impl.
Definition at line 267 of file node_impl.cpp.
References definition(), parameters(), and node::save().
 {
   stream << "function " << parameters().size() << ' ';
   for (auto const& parameter : parameters())
     stream << parameter << ' ';
   definition().save(stream);
 }
Member Data Documentation
node node_function::definition_ private
Definition at line 111 of file node_impl.hpp.
Referenced by definition().
identifier_list node_function::parameters_ private
Definition at line 110 of file node_impl.hpp.
Referenced by parameters().
The documentation for this class was generated from the following files:
node_impl.hpp
node_impl.cpp