######################################################################
# Automatically generated by qmake (2.01a) må 29. jan 10:06:12 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += httpdialog.h
FORMS += httpdialog.ui
SOURCES += httpdialog.cpp main.cpp
QT += network 
CONFIG += console 
