#ifndef _NSIPROXYIP_H_
#define _NSIPROXYIP_H_

#include "ntifs.h"
#include <ntimage.h>
#include "InitWindowsVersion.h"
#include "ntos.h"

BOOL PeLoad(
	WCHAR *FileFullPath,
	BYTE **ImageModeleBase,
	PDRIVER_OBJECT DeviceObject,
	DWORD ExistImageBase
	);

NTSTATUS GetDriverObject(
	WCHAR *lpwzDevice,
	PDRIVER_OBJECT *PDriverObject
	);

//IRP_MJ_MAXIMUM_FUNCTION

typedef struct _NSIPROXYDISPATCH {
	ULONG ulNumber;
	ULONG ulNsiproxyDispatch;
	ULONG ulCurrentNsiproxyDispatch;
	CHAR lpszBaseModule[256];
	ULONG ulModuleSize;
	ULONG ulModuleBase;
	WCHAR lpwzNsiproxyDispatchName[256];
	int Hooked;
} NSIPROXYDISPATCH, *PNSIPROXYDISPATCH;

typedef struct _NSIPROXYDISPATCHBAKUP {
	ULONG ulCount;
	NSIPROXYDISPATCH NsiproxyDispatch[1];
} NSIPROXYDISPATCHBAKUP, *PNSIPROXYDISPATCHBAKUP;

PNSIPROXYDISPATCHBAKUP NsiproxyDispatchBakUp;

ULONG ulNsiproxyModuleBase;
ULONG ulNsiproxyModuleSize;

ULONG ulReLoadNsiproxyModuleBase;

extern BOOL DebugOn;

PDRIVER_OBJECT PNsiproxyDriverObjectBakup;

ULONG ulReal_NSIPROXY_IRP_MJ_CREATE;
ULONG ulReal_NSIPROXY_IRP_MJ_CREATE_NAMED_PIPE;
ULONG ulReal_NSIPROXY_IRP_MJ_CLOSE;
ULONG ulReal_NSIPROXY_IRP_MJ_READ;
ULONG ulReal_NSIPROXY_IRP_MJ_WRITE;
ULONG ulReal_NSIPROXY_IRP_MJ_QUERY_INFORMATION;
ULONG ulReal_NSIPROXY_IRP_MJ_SET_INFORMATION;
ULONG ulReal_NSIPROXY_IRP_MJ_QUERY_EA;
ULONG ulReal_NSIPROXY_IRP_MJ_SET_EA;
ULONG ulReal_NSIPROXY_IRP_MJ_FLUSH_BUFFERS;
ULONG ulReal_NSIPROXY_IRP_MJ_QUERY_VOLUME_INFORMATION;
ULONG ulReal_NSIPROXY_IRP_MJ_SET_VOLUME_INFORMATION;
ULONG ulReal_NSIPROXY_IRP_MJ_DIRECTORY_CONTROL;
ULONG ulReal_NSIPROXY_IRP_MJ_FILE_SYSTEM_CONTROL;
ULONG ulReal_NSIPROXY_IRP_MJ_DEVICE_CONTROL;
ULONG ulReal_NSIPROXY_IRP_MJ_SHUTDOWN;
ULONG ulReal_NSIPROXY_IRP_MJ_LOCK_CONTROL;
ULONG ulReal_NSIPROXY_IRP_MJ_CLEANUP;
ULONG ulReal_NSIPROXY_IRP_MJ_CREATE_MAILSLOT;
ULONG ulReal_NSIPROXY_IRP_MJ_QUERY_SECURITY;
ULONG ulReal_NSIPROXY_IRP_MJ_SET_SECURITY;
ULONG ulReal_NSIPROXY_IRP_MJ_POWER;
ULONG ulReal_NSIPROXY_IRP_MJ_SYSTEM_CONTROL;
ULONG ulReal_NSIPROXY_IRP_MJ_DEVICE_CHANGE;
ULONG ulReal_NSIPROXY_IRP_MJ_QUERY_QUOTA;
ULONG ulReal_NSIPROXY_IRP_MJ_SET_QUOTA;
ULONG ulReal_NSIPROXY_IRP_MJ_PNP_POWER;

NTSTATUS GetDriverObject(WCHAR *lpwzDevice,PDRIVER_OBJECT *PDriverObject);
BOOL GetDriverEntryPoint(PVOID ImageBase,DWORD *pOutDriverEntry);

BOOL IsAddressInSystem(
	ULONG ulDriverBase,
	ULONG *ulSysModuleBase,
	ULONG *ulSize,
	char *lpszSysModuleImage
	);

unsigned long __fastcall GetFunctionCodeSize(
	void *Proc
	);

#endif