CHAR XPProcName[][40]=
{
	 "NtGdiAbortDoc"
	,"NtGdiAbortPath"
	,"NtGdiAddFontResourceW"
	,"NtGdiAddRemoteFontToDC"
	,"NtGdiAddFontMemResourceEx"
	,"NtGdiRemoveMergeFont"
	,"NtGdiAddRemoteMMInstanceToDC"
	,"NtGdiAlphaBlend"
	,"NtGdiAngleArc"
	,"NtGdiAnyLinkedFonts"
	,"NtGdiFontIsLinked"
	,"NtGdiArcInterna"
	,"NtGdiBeginPath"
	,"NtGdiBitBlt"
	,"NtGdiCancelDC"
	,"NtGdiCheckBitmapBits"
	,"NtGdiCloseFigure"
	,"NtGdiClearBitmapAttributes"
	,"NtGdiClearBrushAttributes"
	,"NtGdiColorCorrectPalette"
	,"NtGdiCombineRgn"
	,"NtGdiCombineTransform"
	,"NtGdiComputeXformCoefficients"
	,"NtGdiConsoleTextOut"
	,"NtGdiConvertMetafileRect"
	,"NtGdiCreateBitmap"
	,"NtGdiCreateClientObj"
	,"NtGdiCreateColorSpace"
	,"NtGdiCreateColorTransform"
	,"NtGdiCreateCompatibleBitmap"
	,"NtGdiCreateCompatibleDC"
	,"NtGdiCreateDIBBrush"
	,"NtGdiCreateDIBitmapInterna"
	,"NtGdiCreateDIBSection"
	,"NtGdiCreateEllipticRgn"
	,"NtGdiCreateHalftonePalette"
	,"NtGdiCreateHatchBrushInterna"
	,"NtGdiCreateMetafileDC"
	,"NtGdiCreatePaletteInterna"
	,"NtGdiCreatePatternBrushInterna"
	,"NtGdiCreatePen"
	,"NtGdiCreateRectRgn"
	,"NtGdiCreateRoundRectRgn"
	,"NtGdiCreateServerMetaFile"
	,"NtGdiCreateSolidBrush"
	,"NtGdiD3dContextCreate"
	,"NtGdiD3dContextDestroy"
	,"NtGdiD3dContextDestroyAl"
	,"NtGdiD3dValidateTextureStageState"
	,"NtGdiD3dDrawPrimitives2"
	,"NtGdiDdGetDriverState"
	,"NtGdiDdAddAttachedSurface"
	,"NtGdiDdAlphaBlt"
	,"NtGdiDdAttachSurface"
	,"NtGdiDdBeginMoCompFrame"
	,"NtGdiDdBlt"
	,"NtGdiDdCanCreateSurface"
	,"NtGdiDdCanCreateD3DBuffer"
	,"NtGdiDdColorContro"
	,"NtGdiDdCreateDirectDrawObject"
	,"NtGdiDdCreateSurface"
	,"NtGdiDdCreateD3DBuffer"
	,"NtGdiDdCreateMoComp"
	,"NtGdiDdCreateSurfaceObject"
	,"NtGdiDdDeleteDirectDrawObject"
	,"NtGdiDdDeleteSurfaceObject"
	,"NtGdiDdDestroyMoComp"
	,"NtGdiDdDestroySurface"
	,"NtGdiDdDestroyD3DBuffer"
	,"NtGdiDdEndMoCompFrame"
	,"NtGdiDdFlip"
	,"NtGdiDdFlipToGDISurface"
	,"NtGdiDdGetAvailDriverMemory"
	,"NtGdiDdGetBltStatus"
	,"NtGdiDdGetDC"
	,"NtGdiDdGetDriverInfo"
	,"NtGdiDdGetDxHandle"
	,"NtGdiDdGetFlipStatus"
	,"NtGdiDdGetInternalMoCompInfo"
	,"NtGdiDdGetMoCompBuffInfo"
	,"NtGdiDdGetMoCompGuids"
	,"NtGdiDdGetMoCompFormats"
	,"NtGdiDdGetScanLine"
	,"NtGdiDdLock"
	,"NtGdiDdLockD3D"
	,"NtGdiDdQueryDirectDrawObject"
	,"NtGdiDdQueryMoCompStatus"
	,"NtGdiDdReenableDirectDrawObject"
	,"NtGdiDdReleaseDC"
	,"NtGdiDdRenderMoComp"
	,"NtGdiDdResetVisrgn"
	,"NtGdiDdSetColorKey"
	,"NtGdiDdSetExclusiveMode"
	,"NtGdiDdSetGammaRamp"
	,"NtGdiDdCreateSurfaceEx"
	,"NtGdiDdSetOverlayPosition"
	,"NtGdiDdUnattachSurface"
	,"NtGdiDdUnlock"
	,"NtGdiDdUnlockD3D"
	,"NtGdiDdUpdateOverlay"
	,"NtGdiDdWaitForVerticalBlank"
	,"NtGdiDvpCanCreateVideoPort"
	,"NtGdiDvpColorContro"
	,"NtGdiDvpCreateVideoPort"
	,"NtGdiDvpDestroyVideoPort"
	,"NtGdiDvpFlipVideoPort"
	,"NtGdiDvpGetVideoPortBandwidth"
	,"NtGdiDvpGetVideoPortField"
	,"NtGdiDvpGetVideoPortFlipStatus"
	,"NtGdiDvpGetVideoPortInputFormats"
	,"NtGdiDvpGetVideoPortLine"
	,"NtGdiDvpGetVideoPortOutputFormats"
	,"NtGdiDvpGetVideoPortConnectInfo"
	,"NtGdiDvpGetVideoSignalStatus"
	,"NtGdiDvpUpdateVideoPort"
	,"NtGdiDvpWaitForVideoPortSync"
	,"NtGdiDvpAcquireNotification"
	,"NtGdiDvpReleaseNotification"
	,"NtGdiDxgGenericThunk"
	,"NtGdiDeleteClientObj"
	,"NtGdiDeleteColorSpace"
	,"NtGdiDeleteColorTransform"
	,"NtGdiDeleteObjectApp"
	,"NtGdiDescribePixelFormat"
	,"NtGdiGetPerBandInfo"
	,"NtGdiDoBanding"
	,"NtGdiDoPalette"
	,"NtGdiDrawEscape"
	,"NtGdiEllipse"
	,"NtGdiEnableEudc"
	,"NtGdiEndDoc"
	,"NtGdiEndPage"
	,"NtGdiEndPath"
	,"NtGdiEnumFontChunk"
	,"NtGdiEnumFontClose"
	,"NtGdiEnumFontOpen"
	,"NtGdiEnumObjects"
	,"NtGdiEqualRgn"
	,"NtGdiEudcLoadUnloadLink"
	,"NtGdiExcludeClipRect"
	,"NtGdiExtCreatePen"
	,"NtGdiExtCreateRegion"
	,"NtGdiExtEscape"
	,"NtGdiExtFloodFil"
	,"NtGdiExtGetObjectW"
	,"NtGdiExtSelectClipRgn"
	,"NtGdiExtTextOutW"
	,"NtGdiFillPath"
	,"NtGdiFillRgn"
	,"NtGdiFlattenPath"
	,"NtGdiFlushUserBatch"
	,"NtGdiFlush"
	,"NtGdiForceUFIMapping"
	,"NtGdiFrameRgn"
	,"NtGdiFullscreenContro"
	,"NtGdiGetAndSetDCDword"
	,"NtGdiGetAppClipBox"
	,"NtGdiGetBitmapBits"
	,"NtGdiGetBitmapDimension"
	,"NtGdiGetBoundsRect"
	,"NtGdiGetCharABCWidthsW"
	,"NtGdiGetCharacterPlacementW"
	,"NtGdiGetCharSet"
	,"NtGdiGetCharWidthW"
	,"NtGdiGetCharWidthInfo"
	,"NtGdiGetColorAdjustment"
	,"NtGdiGetColorSpaceforBitmap"
	,"NtGdiGetDCDword"
	,"NtGdiGetDCforBitmap"
	,"NtGdiGetDCObject"
	,"NtGdiGetDCPoint"
	,"NtGdiGetDeviceCaps"
	,"NtGdiGetDeviceGammaRamp"
	,"NtGdiGetDeviceCapsAl"
	,"NtGdiGetDIBitsInterna"
	,"NtGdiGetETM"
	,"NtGdiGetEudcTimeStampEx"
	,"NtGdiGetFontData"
	,"NtGdiGetFontResourceInfoInternalW"
	,"NtGdiGetGlyphIndicesW"
	,"NtGdiGetGlyphIndicesWInterna"
	,"NtGdiGetGlyphOutline"
	,"NtGdiGetKerningPairs"
	,"NtGdiGetLinkedUFIs"
	,"NtGdiGetMiterLimit"
	,"NtGdiGetMonitorID"
	,"NtGdiGetNearestColor"
	,"NtGdiGetNearestPaletteIndex"
	,"NtGdiGetObjectBitmapHandle"
	,"NtGdiGetOutlineTextMetricsInternalW"
	,"NtGdiGetPath"
	,"NtGdiGetPixe"
	,"NtGdiGetRandomRgn"
	,"NtGdiGetRasterizerCaps"
	,"NtGdiGetRealizationInfo"
	,"NtGdiGetRegionData"
	,"NtGdiGetRgnBox"
	,"NtGdiGetServerMetaFileBits"
	,"NtGdiGetSpoolMessage"
	,"NtGdiGetStats"
	,"NtGdiGetStockObject"
	,"NtGdiGetStringBitmapW"
	,"NtGdiGetSystemPaletteUse"
	,"NtGdiGetTextCharsetInfo"
	,"NtGdiGetTextExtent"
	,"NtGdiGetTextExtentExW"
	,"NtGdiGetTextFaceW"
	,"NtGdiGetTextMetricsW"
	,"NtGdiGetTransform"
	,"NtGdiGetUFI"
	,"NtGdiGetEmbUFI"
	,"NtGdiGetUFIPathname"
	,"NtGdiGetEmbedFonts"
	,"NtGdiChangeGhostFont"
	,"NtGdiAddEmbFontToDC"
	,"NtGdiGetFontUnicodeRanges"
	,"NtGdiGetWidthTable"
	,"NtGdiGradientFil"
	,"NtGdiHfontCreate"
	,"NtGdiIcmBrushInfo"
	,"NtGdiInit"
	,"NtGdiInitSpoo"
	,"NtGdiIntersectClipRect"
	,"NtGdiInvertRgn"
	,"NtGdiLineTo"
	,"NtGdiMakeFontDir"
	,"NtGdiMakeInfoDC"
	,"NtGdiMaskBlt"
	,"NtGdiModifyWorldTransform"
	,"NtGdiMonoBitmap"
	,"NtGdiMoveTo"
	,"NtGdiOffsetClipRgn"
	,"NtGdiOffsetRgn"
	,"NtGdiOpenDCW"
	,"NtGdiPatBlt"
	,"NtGdiPolyPatBlt"
	,"NtGdiPathToRegion"
	,"NtGdiPlgBlt"
	,"NtGdiPolyDraw"
	,"NtGdiPolyPolyDraw"
	,"NtGdiPolyTextOutW"
	,"NtGdiPtInRegion"
	,"NtGdiPtVisible"
	,"NtGdiQueryFonts"
	,"NtGdiQueryFontAssocInfo"
	,"NtGdiRectangle"
	,"NtGdiRectInRegion"
	,"NtGdiRectVisible"
	,"NtGdiRemoveFontResourceW"
	,"NtGdiRemoveFontMemResourceEx"
	,"NtGdiResetDC"
	,"NtGdiResizePalette"
	,"NtGdiRestoreDC"
	,"NtGdiRoundRect"
	,"NtGdiSaveDC"
	,"NtGdiScaleViewportExtEx"
	,"NtGdiScaleWindowExtEx"
	,"NtGdiSelectBitmap"
	,"NtGdiSelectBrush"
	,"NtGdiSelectClipPath"
	,"NtGdiSelectFont"
	,"NtGdiSelectPen"
	,"NtGdiSetBitmapAttributes"
	,"NtGdiSetBitmapBits"
	,"NtGdiSetBitmapDimension"
	,"NtGdiSetBoundsRect"
	,"NtGdiSetBrushAttributes"
	,"NtGdiSetBrushOrg"
	,"NtGdiSetColorAdjustment"
	,"NtGdiSetColorSpace"
	,"NtGdiSetDeviceGammaRamp"
	,"NtGdiSetDIBitsToDeviceInterna"
	,"NtGdiSetFontEnumeration"
	,"NtGdiSetFontXform"
	,"NtGdiSetIcmMode"
	,"NtGdiSetLinkedUFIs"
	,"NtGdiSetMagicColors"
	,"NtGdiSetMetaRgn"
	,"NtGdiSetMiterLimit"
	,"NtGdiGetDeviceWidth"
	,"NtGdiMirrorWindowOrg"
	,"NtGdiSetLayout"
	,"NtGdiSetPixe"
	,"NtGdiSetPixelFormat"
	,"NtGdiSetRectRgn"
	,"NtGdiSetSystemPaletteUse"
	,"NtGdiSetTextJustification"
	,"NtGdiSetupPublicCFONT"
	,"NtGdiSetVirtualResolution"
	,"NtGdiSetSizeDevice"
	,"NtGdiStartDoc"
	,"NtGdiStartPage"
	,"NtGdiStretchBlt"
	,"NtGdiStretchDIBitsInterna"
	,"NtGdiStrokeAndFillPath"
	,"NtGdiStrokePath"
	,"NtGdiSwapBuffers"
	,"NtGdiTransformPoints"
	,"NtGdiTransparentBlt"
	,"NtGdiUnloadPrinterDriver"
	,"NtGdiUnmapMemFont"
	,"NtGdiUnrealizeObject"
	,"NtGdiUpdateColors"
	,"NtGdiWidenPath"
	,"NtUserActivateKeyboardLayout"
	,"NtUserAlterWindowStyle"
	,"NtUserAssociateInputContext"
	,"NtUserAttachThreadInput"
	,"NtUserBeginPaint"
	,"NtUserBitBltSysBmp"
	,"NtUserBlockInput"
	,"NtUserBuildHimcList"
	,"NtUserBuildHwndList"
	,"NtUserBuildNameList"
	,"NtUserBuildPropList"
	,"NtUserCallHwnd"
	,"NtUserCallHwndLock"
	,"NtUserCallHwndOpt"
	,"NtUserCallHwndParam"
	,"NtUserCallHwndParamLock"
	,"NtUserCallMsgFilter"
	,"NtUserCallNextHookEx"
	,"NtUserCallNoParam"
	,"NtUserCallOneParam"
	,"NtUserCallTwoParam"
	,"NtUserChangeClipboardChain"
	,"NtUserChangeDisplaySettings"
	,"NtUserCheckImeHotKey"
	,"NtUserCheckMenuItem"
	,"NtUserChildWindowFromPointEx"
	,"NtUserClipCursor"
	,"NtUserCloseClipboard"
	,"NtUserCloseDesktop"
	,"NtUserCloseWindowStation"
	,"NtUserConsoleContro"
	,"NtUserConvertMemHandle"
	,"NtUserCopyAcceleratorTable"
	,"NtUserCountClipboardFormats"
	,"NtUserCreateAcceleratorTable"
	,"NtUserCreateCaret"
	,"NtUserCreateDesktop"
	,"NtUserCreateInputContext"
	,"NtUserCreateLocalMemHandle"
	,"NtUserCreateWindowEx"
	,"NtUserCreateWindowStation"
	,"NtUserDdeGetQualityOfService"
	,"NtUserDdeInitialize"
	,"NtUserDdeSetQualityOfService"
	,"NtUserDeferWindowPos"
	,"NtUserDefSetText"
	,"NtUserDeleteMenu"
	,"NtUserDestroyAcceleratorTable"
	,"NtUserDestroyCursor"
	,"NtUserDestroyInputContext"
	,"NtUserDestroyMenu"
	,"NtUserDestroyWindow"
	,"NtUserDisableThreadIme"
	,"NtUserDispatchMessage"
	,"NtUserDragDetect"
	,"NtUserDragObject"
	,"NtUserDrawAnimatedRects"
	,"NtUserDrawCaption"
	,"NtUserDrawCaptionTemp"
	,"NtUserDrawIconEx"
	,"NtUserDrawMenuBarTemp"
	,"NtUserEmptyClipboard"
	,"NtUserEnableMenuItem"
	,"NtUserEnableScrollBar"
	,"NtUserEndDeferWindowPosEx"
	,"NtUserEndMenu"
	,"NtUserEndPaint"
	,"NtUserEnumDisplayDevices"
	,"NtUserEnumDisplayMonitors"
	,"NtUserEnumDisplaySettings"
	,"NtUserEvent"
	,"NtUserExcludeUpdateRgn"
	,"NtUserFillWindow"
	,"NtUserFindExistingCursorIcon"
	,"NtUserFindWindowEx"
	,"NtUserFlashWindowEx"
	,"NtUserGetAltTabInfo"
	,"NtUserGetAncestor"
	,"NtUserGetAppImeLeve"
	,"NtUserGetAsyncKeyState"
	,"NtUserGetAtomName"
	,"NtUserGetCaretBlinkTime"
	,"NtUserGetCaretPos"
	,"NtUserGetClassInfo"
	,"NtUserGetClassName"
	,"NtUserGetClipboardData"
	,"NtUserGetClipboardFormatName"
	,"NtUserGetClipboardOwner"
	,"NtUserGetClipboardSequenceNumber"
	,"NtUserGetClipboardViewer"
	,"NtUserGetClipCursor"
	,"NtUserGetComboBoxInfo"
	,"NtUserGetControlBrush"
	,"NtUserGetControlColor"
	,"NtUserGetCPD"
	,"NtUserGetCursorFrameInfo"
	,"NtUserGetCursorInfo"
	,"NtUserGetDC"
	,"NtUserGetDCEx"
	,"NtUserGetDoubleClickTime"
	,"NtUserGetForegroundWindow"
	,"NtUserGetGuiResources"
	,"NtUserGetGUIThreadInfo"
	,"NtUserGetIconInfo"
	,"NtUserGetIconSize"
	,"NtUserGetImeHotKey"
	,"NtUserGetImeInfoEx"
	,"NtUserGetInternalWindowPos"
	,"NtUserGetKeyboardLayoutList"
	,"NtUserGetKeyboardLayoutName"
	,"NtUserGetKeyboardState"
	,"NtUserGetKeyNameText"
	,"NtUserGetKeyState"
	,"NtUserGetListBoxInfo"
	,"NtUserGetMenuBarInfo"
	,"NtUserGetMenuIndex"
	,"NtUserGetMenuItemRect"
	,"NtUserGetMessage"
	,"NtUserGetMouseMovePointsEx"
	,"NtUserGetObjectInformation"
	,"NtUserGetOpenClipboardWindow"
	,"NtUserGetPriorityClipboardFormat"
	,"NtUserGetProcessWindowStation"
	,"NtUserGetRawInputBuffer"
	,"NtUserGetRawInputData"
	,"NtUserGetRawInputDeviceInfo"
	,"NtUserGetRawInputDeviceList"
	,"NtUserGetRegisteredRawInputDevices"
	,"NtUserGetScrollBarInfo"
	,"NtUserGetSystemMenu"
	,"NtUserGetThreadDesktop"
	,"NtUserGetThreadState"
	,"NtUserGetTitleBarInfo"
	,"NtUserGetUpdateRect"
	,"NtUserGetUpdateRgn"
	,"NtUserGetWindowDC"
	,"NtUserGetWindowPlacement"
	,"NtUserGetWOWClass"
	,"NtUserHardErrorContro"
	,"NtUserHideCaret"
	,"NtUserHiliteMenuItem"
	,"NtUserImpersonateDdeClientWindow"
	,"NtUserInitialize"
	,"NtUserInitializeClientPfnArrays"
	,"NtUserInitTask"
	,"NtUserInternalGetWindowText"
	,"NtUserInvalidateRect"
	,"NtUserInvalidateRgn"
	,"NtUserIsClipboardFormatAvailable"
	,"NtUserKillTimer"
	,"NtUserLoadKeyboardLayoutEx"
	,"NtUserLockWindowStation"
	,"NtUserLockWindowUpdate"
	,"NtUserLockWorkStation"
	,"NtUserMapVirtualKeyEx"
	,"NtUserMenuItemFromPoint"
	,"NtUserMessageCall"
	,"NtUserMinMaximize"
	,"NtUserMNDragLeave"
	,"NtUserMNDragOver"
	,"NtUserModifyUserStartupInfoFlags"
	,"NtUserMoveWindow"
	,"NtUserNotifyIMEStatus"
	,"NtUserNotifyProcessCreate"
	,"NtUserNotifyWinEvent"
	,"NtUserOpenClipboard"
	,"NtUserOpenDesktop"
	,"NtUserOpenInputDesktop"
	,"NtUserOpenWindowStation"
	,"NtUserPaintDesktop"
	,"NtUserPeekMessage"
	,"NtUserPostMessage"
	,"NtUserPostThreadMessage"
	,"NtUserPrintWindow"
	,"NtUserProcessConnect"
	,"NtUserQueryInformationThread"
	,"NtUserQueryInputContext"
	,"NtUserQuerySendMessage"
	,"NtUserQueryUserCounters"
	,"NtUserQueryWindow"
	,"NtUserRealChildWindowFromPoint"
	,"NtUserRealInternalGetMessage"
	,"NtUserRealWaitMessageEx"
	,"NtUserRedrawWindow"
	,"NtUserRegisterClassExWOW"
	,"NtUserRegisterUserApiHook"
	,"NtUserRegisterHotKey"
	,"NtUserRegisterRawInputDevices"
	,"NtUserRegisterTasklist"
	,"NtUserRegisterWindowMessage"
	,"NtUserRemoveMenu"
	,"NtUserRemoveProp"
	,"NtUserResolveDesktop"
	,"NtUserResolveDesktopForWOW"
	,"NtUserSBGetParms"
	,"NtUserScrollDC"
	,"NtUserScrollWindowEx"
	,"NtUserSelectPalette"
	,"NtUserSendInput"
	,"NtUserSetActiveWindow"
	,"NtUserSetAppImeLeve"
	,"NtUserSetCapture"
	,"NtUserSetClassLong"
	,"NtUserSetClassWord"
	,"NtUserSetClipboardData"
	,"NtUserSetClipboardViewer"
	,"NtUserSetConsoleReserveKeys"
	,"NtUserSetCursor"
	,"NtUserSetCursorContents"
	,"NtUserSetCursorIconData"
	,"NtUserSetDbgTag"
	,"NtUserSetFocus"
	,"NtUserSetImeHotKey"
	,"NtUserSetImeInfoEx"
	,"NtUserSetImeOwnerWindow"
	,"NtUserSetInformationProcess"
	,"NtUserSetInformationThread"
	,"NtUserSetInternalWindowPos"
	,"NtUserSetKeyboardState"
	,"NtUserSetLogonNotifyWindow"
	,"NtUserSetMenu"
	,"NtUserSetMenuContextHelpId"
	,"NtUserSetMenuDefaultItem"
	,"NtUserSetMenuFlagRto"
	,"NtUserSetObjectInformation"
	,"NtUserSetParent"
	,"NtUserSetProcessWindowStation"
	,"NtUserSetProp"
	,"NtUserSetRipFlags"
	,"NtUserSetScrollInfo"
	,"NtUserSetShellWindowEx"
	,"NtUserSetSysColors"
	,"NtUserSetSystemCursor"
	,"NtUserSetSystemMenu"
	,"NtUserSetSystemTimer"
	,"NtUserSetThreadDesktop"
	,"NtUserSetThreadLayoutHandles"
	,"NtUserSetThreadState"
	,"NtUserSetTimer"
	,"NtUserSetWindowFNID"
	,"NtUserSetWindowLong"
	,"NtUserSetWindowPlacement"
	,"NtUserSetWindowPos"
	,"NtUserSetWindowRgn"
	,"NtUserSetWindowsHookAW"
	,"NtUserSetWindowsHookEx"
	,"NtUserSetWindowStationUser"
	,"NtUserSetWindowWord"
	,"NtUserSetWinEventHook"
	,"NtUserShowCaret"
	,"NtUserShowScrollBar"
	,"NtUserShowWindow"
	,"NtUserShowWindowAsync"
	,"NtUserSoundSentry"
	,"NtUserSwitchDesktop"
	,"NtUserSystemParametersInfo"
	,"NtUserTestForInteractiveUser"
	,"NtUserThunkedMenuInfo"
	,"NtUserThunkedMenuItemInfo"
	,"NtUserToUnicodeEx"
	,"NtUserTrackMouseEvent"
	,"NtUserTrackPopupMenuEx"
	,"NtUserCalcMenuBar"
	,"NtUserPaintMenuBar"
	,"NtUserTranslateAccelerator"
	,"NtUserTranslateMessage"
	,"NtUserUnhookWindowsHookEx"
	,"NtUserUnhookWinEvent"
	,"NtUserUnloadKeyboardLayout"
	,"NtUserUnlockWindowStation"
	,"NtUserUnregisterClass"
	,"NtUserUnregisterUserApiHook"
	,"NtUserUnregisterHotKey"
	,"NtUserUpdateInputContext"
	,"NtUserUpdateInstance"
	,"NtUserUpdateLayeredWindow"
	,"NtUserGetLayeredWindowAttributes"
	,"NtUserSetLayeredWindowAttributes"
	,"NtUserUpdatePerUserSystemParameter"
	,"NtUserUserHandleGrantAccess"
	,"NtUserValidateHandleSecure"
	,"NtUserValidateRect"
	,"NtUserValidateTimerCallback"
	,"NtUserVkKeyScanEx"
	,"NtUserWaitForInputIdle"
	,"NtUserWaitForMsgAndEvent"
	,"NtUserWaitMessage"
	,"NtUserWin32PoolAllocationStats"
	,"NtUserWindowFromPoint"
	,"NtUserYieldTask"
	,"NtUserRemoteConnect"
	,"NtUserRemoteRedrawRectangle"
	,"NtUserRemoteRedrawScreen"
	,"NtUserRemoteStopScreenUpdates"
	,"NtUserCtxDisplayIOCt"
	,"NtGdiEngAssociateSurface"
	,"NtGdiEngCreateBitmap"
	,"NtGdiEngCreateDeviceSurface"
	,"NtGdiEngCreateDeviceBitmap"
	,"NtGdiEngCreatePalette"
	,"NtGdiEngComputeGlyphSet"
	,"NtGdiEngCopyBits"
	,"NtGdiEngDeletePalette"
	,"NtGdiEngDeleteSurface"
	,"NtGdiEngEraseSurface"
	,"NtGdiEngUnlockSurface"
	,"NtGdiEngLockSurface"
	,"NtGdiEngBitBlt"
	,"NtGdiEngStretchBlt"
	,"NtGdiEngPlgBlt"
	,"NtGdiEngMarkBandingSurface"
	,"NtGdiEngStrokePath"
	,"NtGdiEngFillPath"
	,"NtGdiEngStrokeAndFillPath"
	,"NtGdiEngPaint"
	,"NtGdiEngLineTo"
	,"NtGdiEngAlphaBlend"
	,"NtGdiEngGradientFil"
	,"NtGdiEngTransparentBlt"
	,"NtGdiEngTextOut"
	,"NtGdiEngStretchBltROP"
	,"NtGdiXLATEOBJ_cGetPalette"
	,"NtGdiXLATEOBJ_iXlate"
	,"NtGdiXLATEOBJ_hGetColorTransform"
	,"NtGdiCLIPOBJ_bEnum"
	,"NtGdiCLIPOBJ_cEnumStart"
	,"NtGdiCLIPOBJ_ppoGetPath"
	,"NtGdiEngDeletePath"
	,"NtGdiEngCreateClip"
	,"NtGdiEngDeleteClip"
	,"NtGdiBRUSHOBJ_ulGetBrushColor"
	,"NtGdiBRUSHOBJ_pvAllocRbrush"
	,"NtGdiBRUSHOBJ_pvGetRbrush"
	,"NtGdiBRUSHOBJ_hGetColorTransform"
	,"NtGdiXFORMOBJ_bApplyXform"
	,"NtGdiXFORMOBJ_iGetXform"
	,"NtGdiFONTOBJ_vGetInfo"
	,"NtGdiFONTOBJ_pxoGetXform"
	,"NtGdiFONTOBJ_cGetGlyphs"
	,"NtGdiFONTOBJ_pifi"
	,"NtGdiFONTOBJ_pfdg"
	,"NtGdiFONTOBJ_pQueryGlyphAttrs"
	,"NtGdiFONTOBJ_pvTrueTypeFontFile"
	,"NtGdiFONTOBJ_cGetAllGlyphHandles"
	,"NtGdiSTROBJ_bEnum"
	,"NtGdiSTROBJ_bEnumPositionsOnly"
	,"NtGdiSTROBJ_bGetAdvanceWidths"
	,"NtGdiSTROBJ_vEnumStart"
	,"NtGdiSTROBJ_dwGetCodePage"
	,"NtGdiPATHOBJ_vGetBounds"
	,"NtGdiPATHOBJ_bEnum"
	,"NtGdiPATHOBJ_vEnumStart"
	,"NtGdiPATHOBJ_vEnumStartClipLines"
	,"NtGdiPATHOBJ_bEnumClipLines"
	,"NtGdiGetDhpdev"
	,"NtGdiEngCheckAbort"
	,"NtGdiHT_Get8BPPFormatPalette"
	,"NtGdiHT_Get8BPPMaskPalette"
	,"NtGdiUpdateTransform"
	,"NtGdiSetPUMPDOBJ"
	,"NtGdiBRUSHOBJ_DeleteRbrush"
	,"NtGdiUnmapMemFont"
	,"NtGdiDrawStream"
};

CHAR Win2003ProcName[][50]=
{
	"NtGdiAbortDoc",
	"NtGdiAbortPath",
	"NtGdiAddFontResourceW",
	"NtGdiAddRemoteFontToDC",
	"NtGdiAddFontMemResourceEx",
	"NtGdiRemoveMergeFont",
	"NtGdiAddRemoteMMInstanceToDC",
	"NtGdiAlphaBlend",
	"NtGdiAngleArc",
	"NtGdiAnyLinkedFonts",
	"NtGdiFontIsLinked",
	"NtGdiArcInterna",
	"NtGdiBeginPath",
	"NtGdiBitBlt",
	"NtGdiCancelDC",
	"NtGdiCheckBitmapBits",
	"NtGdiCloseFigure",
	"NtGdiClearBitmapAttributes",
	"NtGdiClearBrushAttributes",
	"NtGdiColorCorrectPalette",
	"NtGdiCombineRgn",
	"NtGdiCombineTransform",
	"NtGdiComputeXformCoefficients",
	"NtGdiConsoleTextOut",
	"NtGdiConvertMetafileRect",
	"NtGdiCreateBitmap",
	"NtGdiCreateClientObj",
	"NtGdiCreateColorSpace",
	"NtGdiCreateColorTransform",
	"NtGdiCreateCompatibleBitmap",
	"NtGdiCreateCompatibleDC",
	"NtGdiCreateDIBBrush",
	"NtGdiCreateDIBitmapInterna",
	"NtGdiCreateDIBSection",
	"NtGdiCreateEllipticRgn",
	"NtGdiCreateHalftonePalette",
	"NtGdiCreateHatchBrushInterna",
	"NtGdiCreateMetafileDC",
	"NtGdiCreatePaletteInterna",
	"NtGdiCreatePatternBrushInterna",
	"NtGdiCreatePen",
	"NtGdiCreateRectRgn",
	"NtGdiCreateRoundRectRgn",
	"NtGdiCreateServerMetaFile",
	"NtGdiCreateSolidBrush",
	"NtGdiD3dContextCreate",
	"NtGdiD3dContextDestroy",
	"NtGdiD3dContextDestroyAl",
	"NtGdiD3dValidateTextureStageState",
	"NtGdiD3dDrawPrimitives2",
	"NtGdiDdGetDriverState",
	"NtGdiDdAddAttachedSurface",
	"NtGdiDdAlphaBlt",
	"NtGdiDdAttachSurface",
	"NtGdiDdBeginMoCompFrame",
	"NtGdiDdBlt",
	"NtGdiDdCanCreateSurface",
	"NtGdiDdCanCreateD3DBuffer",
	"NtGdiDdColorContro",
	"NtGdiDdCreateDirectDrawObject",
	"NtGdiDdCreateSurface",
	"NtGdiDdCreateD3DBuffer",
	"NtGdiDdCreateMoComp",
	"NtGdiDdCreateSurfaceObject",
	"NtGdiDdDeleteDirectDrawObject",
	"NtGdiDdDeleteSurfaceObject",
	"NtGdiDdDestroyMoComp",
	"NtGdiDdDestroySurface",
	"NtGdiDdDestroyD3DBuffer",
	"NtGdiDdEndMoCompFrame",
	"NtGdiDdFlip",
	"NtGdiDdFlipToGDISurface",
	"NtGdiDdGetAvailDriverMemory",
	"NtGdiDdGetBltStatus",
	"NtGdiDdGetDC",
	"NtGdiDdGetDriverInfo",
	"NtGdiDdGetDxHandle",
	"NtGdiDdGetFlipStatus",
	"NtGdiDdGetInternalMoCompInfo",
	"NtGdiDdGetMoCompBuffInfo",
	"NtGdiDdGetMoCompGuids",
	"NtGdiDdGetMoCompFormats",
	"NtGdiDdGetScanLine",
	"NtGdiDdLock",
	"NtGdiDdLockD3D",
	"NtGdiDdQueryDirectDrawObject",
	"NtGdiDdQueryMoCompStatus",
	"NtGdiDdReenableDirectDrawObject",
	"NtGdiDdReleaseDC",
	"NtGdiDdRenderMoComp",
	"NtGdiDdResetVisrgn",
	"NtGdiDdSetColorKey",
	"NtGdiDdSetExclusiveMode",
	"NtGdiDdSetGammaRamp",
	"NtGdiDdCreateSurfaceEx",
	"NtGdiDdSetOverlayPosition",
	"NtGdiDdUnattachSurface",
	"NtGdiDdUnlock",
	"NtGdiDdUnlockD3D",
	"NtGdiDdUpdateOverlay",
	"NtGdiDdWaitForVerticalBlank",
	"NtGdiDvpCanCreateVideoPort",
	"NtGdiDvpColorContro",
	"NtGdiDvpCreateVideoPort",
	"NtGdiDvpDestroyVideoPort",
	"NtGdiDvpFlipVideoPort",
	"NtGdiDvpGetVideoPortBandwidth",
	"NtGdiDvpGetVideoPortField",
	"NtGdiDvpGetVideoPortFlipStatus",
	"NtGdiDvpGetVideoPortInputFormats",
	"NtGdiDvpGetVideoPortLine",
	"NtGdiDvpGetVideoPortOutputFormats",
	"NtGdiDvpGetVideoPortConnectInfo",
	"NtGdiDvpGetVideoSignalStatus",
	"NtGdiDvpUpdateVideoPort",
	"NtGdiDvpWaitForVideoPortSync",
	"NtGdiDvpAcquireNotification",
	"NtGdiDvpReleaseNotification",
	"NtGdiDxgGenericThunk",
	"NtGdiDeleteClientObj",
	"NtGdiDeleteColorSpace",
	"NtGdiDeleteColorTransform",
	"NtGdiDeleteObjectApp",
	"NtGdiDescribePixelFormat",
	"NtGdiGetPerBandInfo",
	"NtGdiDoBanding",
	"NtGdiDoPalette",
	"NtGdiDrawEscape",
	"NtGdiEllipse",
	"NtGdiEnableEudc",
	"NtGdiEndDoc",
	"NtGdiEndPage",
	"NtGdiEndPath",
	"NtGdiEnumFontChunk",
	"NtGdiEnumFontClose",
	"NtGdiEnumFontOpen",
	"NtGdiEnumObjects",
	"NtGdiEqualRgn",
	"NtGdiEudcLoadUnloadLink",
	"NtGdiExcludeClipRect",
	"NtGdiExtCreatePen",
	"NtGdiExtCreateRegion",
	"NtGdiExtEscape",
	"NtGdiExtFloodFil",
	"NtGdiExtGetObjectW",
	"NtGdiExtSelectClipRgn",
	"NtGdiExtTextOutW",
	"NtGdiFillPath",
	"NtGdiFillRgn",
	"NtGdiFlattenPath",
	"NtGdiFlush",
	"NtGdiForceUFIMapping",
	"NtGdiFrameRgn",
	"NtGdiFullscreenContro",
	"NtGdiGetAndSetDCDword",
	"NtGdiGetAppClipBox",
	"NtGdiGetBitmapBits",
	"NtGdiGetBitmapDimension",
	"NtGdiGetBoundsRect",
	"NtGdiGetCharABCWidthsW",
	"NtGdiGetCharacterPlacementW",
	"NtGdiGetCharSet",
	"NtGdiGetCharWidthW",
	"NtGdiGetCharWidthInfo",
	"NtGdiGetColorAdjustment",
	"NtGdiGetColorSpaceforBitmap",
	"NtGdiGetDCDword",
	"NtGdiGetDCforBitmap",
	"NtGdiGetDCObject",
	"NtGdiGetDCPoint",
	"NtGdiGetDeviceCaps",
	"NtGdiGetDeviceGammaRamp",
	"NtGdiGetDeviceCapsAl",
	"NtGdiGetDIBitsInterna",
	"NtGdiGetETM",
	"NtGdiGetEudcTimeStampEx",
	"NtGdiGetFontData",
	"NtGdiGetFontResourceInfoInternalW",
	"NtGdiGetGlyphIndicesW",
	"NtGdiGetGlyphIndicesWInterna",
	"NtGdiGetGlyphOutline",
	"NtGdiGetKerningPairs",
	"NtGdiGetLinkedUFIs",
	"NtGdiGetMiterLimit",
	"NtGdiGetMonitorID",
	"NtGdiGetNearestColor",
	"NtGdiGetNearestPaletteIndex",
	"NtGdiGetObjectBitmapHandle",
	"NtGdiGetOutlineTextMetricsInternalW",
	"NtGdiGetPath",
	"NtGdiGetPixe",
	"NtGdiGetRandomRgn",
	"NtGdiGetRasterizerCaps",
	"NtGdiGetRealizationInfo",
	"NtGdiGetRegionData",
	"NtGdiGetRgnBox",
	"NtGdiGetServerMetaFileBits",
	"NtGdiGetSpoolMessage",
	"NtGdiGetStats",
	"NtGdiGetStockObject",
	"NtGdiGetStringBitmapW",
	"NtGdiGetSystemPaletteUse",
	"NtGdiGetTextCharsetInfo",
	"NtGdiGetTextExtent",
	"NtGdiGetTextExtentExW",
	"NtGdiGetTextFaceW",
	"NtGdiGetTextMetricsW",
	"NtGdiGetTransform",
	"NtGdiGetUFI",
	"NtGdiGetEmbUFI",
	"NtGdiGetUFIPathname",
	"NtGdiGetEmbedFonts",
	"NtGdiChangeGhostFont",
	"NtGdiAddEmbFontToDC",
	"NtGdiGetFontUnicodeRanges",
	"NtGdiGetWidthTable",
	"NtGdiGradientFil",
	"NtGdiHfontCreate",
	"NtGdiIcmBrushInfo",
	"NtGdiInit",
	"NtGdiInitSpoo",
	"NtGdiIntersectClipRect",
	"NtGdiInvertRgn",
	"NtGdiLineTo",
	"NtGdiMakeFontDir",
	"NtGdiMakeInfoDC",
	"NtGdiMaskBlt",
	"NtGdiModifyWorldTransform",
	"NtGdiMonoBitmap",
	"NtGdiMoveTo",
	"NtGdiOffsetClipRgn",
	"NtGdiOffsetRgn",
	"NtGdiOpenDCW",
	"NtGdiPatBlt",
	"NtGdiPolyPatBlt",
	"NtGdiPathToRegion",
	"NtGdiPlgBlt",
	"NtGdiPolyDraw",
	"NtGdiPolyPolyDraw",
	"NtGdiPolyTextOutW",
	"NtGdiPtInRegion",
	"NtGdiPtVisible",
	"NtGdiQueryFonts",
	"NtGdiQueryFontAssocInfo",
	"NtGdiRectangle",
	"NtGdiRectInRegion",
	"NtGdiRectVisible",
	"NtGdiRemoveFontResourceW",
	"NtGdiRemoveFontMemResourceEx",
	"NtGdiResetDC",
	"NtGdiResizePalette",
	"NtGdiRestoreDC",
	"NtGdiRoundRect",
	"NtGdiSaveDC",
	"NtGdiScaleViewportExtEx",
	"NtGdiScaleWindowExtEx",
	"NtGdiSelectBitmap",
	"NtGdiSelectBrush",
	"NtGdiSelectClipPath",
	"NtGdiSelectFont",
	"NtGdiSelectPen",
	"NtGdiSetBitmapAttributes",
	"NtGdiSetBitmapBits",
	"NtGdiSetBitmapDimension",
	"NtGdiSetBoundsRect",
	"NtGdiSetBrushAttributes",
	"NtGdiSetBrushOrg",
	"NtGdiSetColorAdjustment",
	"NtGdiSetColorSpace",
	"NtGdiSetDeviceGammaRamp",
	"NtGdiSetDIBitsToDeviceInterna",
	"NtGdiSetFontEnumeration",
	"NtGdiSetFontXform",
	"NtGdiSetIcmMode",
	"NtGdiSetLinkedUFIs",
	"NtGdiSetMagicColors",
	"NtGdiSetMetaRgn",
	"NtGdiSetMiterLimit",
	"NtGdiGetDeviceWidth",
	"NtGdiMirrorWindowOrg",
	"NtGdiSetLayout",
	"NtGdiSetPixe",
	"NtGdiSetPixelFormat",
	"NtGdiSetRectRgn",
	"NtGdiSetSystemPaletteUse",
	"NtGdiSetTextJustification",
	"NtGdiSetupPublicCFONT",
	"NtGdiSetVirtualResolution",
	"NtGdiSetSizeDevice",
	"NtGdiStartDoc",
	"NtGdiStartPage",
	"NtGdiStretchBlt",
	"NtGdiStretchDIBitsInterna",
	"NtGdiStrokeAndFillPath",
	"NtGdiStrokePath",
	"NtGdiSwapBuffers",
	"NtGdiTransformPoints",
	"NtGdiTransparentBlt",
	"NtGdiUnloadPrinterDriver",
	"NtGdiUnmapMemFont",
	"NtGdiUnrealizeObject",
	"NtGdiUpdateColors",
	"NtGdiWidenPath",
	"NtUserActivateKeyboardLayout",
	"NtUserAlterWindowStyle",
	"NtUserAssociateInputContext",
	"NtUserAttachThreadInput",
	"NtUserBeginPaint",
	"NtUserBitBltSysBmp",
	"NtUserBlockInput",
	"NtUserBuildHimcList",
	"NtUserBuildHwndList",
	"NtUserBuildNameList",
	"NtUserBuildPropList",
	"NtUserCallHwnd",
	"NtUserCallHwndLock",
	"NtUserCallHwndOpt",
	"NtUserCallHwndParam",
	"NtUserCallHwndParamLock",
	"NtUserCallMsgFilter",
	"NtUserCallNextHookEx",
	"NtUserCallNoParam",
	"NtUserCallOneParam",
	"NtUserCallTwoParam",
	"NtUserChangeClipboardChain",
	"NtUserChangeDisplaySettings",
	"NtUserCheckImeHotKey",
	"NtUserCheckMenuItem",
	"NtUserChildWindowFromPointEx",
	"NtUserClipCursor",
	"NtUserCloseClipboard",
	"NtUserCloseDesktop",
	"NtUserCloseWindowStation",
	"NtUserConsoleContro",
	"NtUserConvertMemHandle",
	"NtUserCopyAcceleratorTable",
	"NtUserCountClipboardFormats",
	"NtUserCreateAcceleratorTable",
	"NtUserCreateCaret",
	"NtUserCreateDesktop",
	"NtUserCreateInputContext",
	"NtUserCreateLocalMemHandle",
	"NtUserCreateWindowEx",
	"NtUserCreateWindowStation",
	"NtUserDdeGetQualityOfService",
	"NtUserDdeInitialize",
	"NtUserDdeSetQualityOfService",
	"NtUserDeferWindowPos",
	"NtUserDefSetText",
	"NtUserDeleteMenu",
	"NtUserDestroyAcceleratorTable",
	"NtUserDestroyCursor",
	"NtUserDestroyInputContext",
	"NtUserDestroyMenu",
	"NtUserDestroyWindow",
	"NtUserDisableThreadIme",
	"NtUserDispatchMessage",
	"NtUserDragDetect",
	"NtUserDragObject",
	"NtUserDrawAnimatedRects",
	"NtUserDrawCaption",
	"NtUserDrawCaptionTemp",
	"NtUserDrawIconEx",
	"NtUserDrawMenuBarTemp",
	"NtUserEmptyClipboard",
	"NtUserEnableMenuItem",
	"NtUserEnableScrollBar",
	"NtUserEndDeferWindowPosEx",
	"NtUserEndMenu",
	"NtUserEndPaint",
	"NtUserEnumDisplayDevices",
	"NtUserEnumDisplayMonitors",
	"NtUserEnumDisplaySettings",
	"NtUserEvent",
	"NtUserExcludeUpdateRgn",
	"NtUserFillWindow",
	"NtUserFindExistingCursorIcon",
	"NtUserFindWindowEx",
	"NtUserFlashWindowEx",
	"NtUserGetAltTabInfo",
	"NtUserGetAncestor",
	"NtUserGetAppImeLeve",
	"NtUserGetAsyncKeyState",
	"NtUserGetAtomName",
	"NtUserGetCaretBlinkTime",
	"NtUserGetCaretPos",
	"NtUserGetClassInfo",
	"NtUserGetClassName",
	"NtUserGetClipboardData",
	"NtUserGetClipboardFormatName",
	"NtUserGetClipboardOwner",
	"NtUserGetClipboardSequenceNumber",
	"NtUserGetClipboardViewer",
	"NtUserGetClipCursor",
	"NtUserGetComboBoxInfo",
	"NtUserGetControlBrush",
	"NtUserGetControlColor",
	"NtUserGetCPD",
	"NtUserGetCursorFrameInfo",
	"NtUserGetCursorInfo",
	"NtUserGetDC",
	"NtUserGetDCEx",
	"NtUserGetDoubleClickTime",
	"NtUserGetForegroundWindow",
	"NtUserGetGuiResources",
	"NtUserGetGUIThreadInfo",
	"NtUserGetIconInfo",
	"NtUserGetIconSize",
	"NtUserGetImeHotKey",
	"NtUserGetImeInfoEx",
	"NtUserGetInternalWindowPos",
	"NtUserGetKeyboardLayoutList",
	"NtUserGetKeyboardLayoutName",
	"NtUserGetKeyboardState",
	"NtUserGetKeyNameText",
	"NtUserGetKeyState",
	"NtUserGetListBoxInfo",
	"NtUserGetMenuBarInfo",
	"NtUserGetMenuIndex",
	"NtUserGetMenuItemRect",
	"NtUserGetMessage",
	"NtUserGetMouseMovePointsEx",
	"NtUserGetObjectInformation",
	"NtUserGetOpenClipboardWindow",
	"NtUserGetPriorityClipboardFormat",
	"NtUserGetProcessWindowStation",
	"NtUserGetRawInputBuffer",
	"NtUserGetRawInputData",
	"NtUserGetRawInputDeviceInfo",
	"NtUserGetRawInputDeviceList",
	"NtUserGetRegisteredRawInputDevices",
	"NtUserGetScrollBarInfo",
	"NtUserGetSystemMenu",
	"NtUserGetThreadDesktop",
	"NtUserGetThreadState",
	"NtUserGetTitleBarInfo",
	"NtUserGetUpdateRect",
	"NtUserGetUpdateRgn",
	"NtUserGetWindowDC",
	"NtUserGetWindowPlacement",
	"NtUserGetWOWClass",
	"NtUserHardErrorContro",
	"NtUserHideCaret",
	"NtUserHiliteMenuItem",
	"NtUserImpersonateDdeClientWindow",
	"NtUserInitialize",
	"NtUserInitializeClientPfnArrays",
	"NtUserInitTask",
	"NtUserInternalGetWindowText",
	"NtUserInvalidateRect",
	"NtUserInvalidateRgn",
	"NtUserIsClipboardFormatAvailable",
	"NtUserKillTimer",
	"NtUserLoadKeyboardLayoutEx",
	"NtUserLockWindowStation",
	"NtUserLockWindowUpdate",
	"NtUserLockWorkStation",
	"NtUserMapVirtualKeyEx",
	"NtUserMenuItemFromPoint",
	"NtUserMessageCall",
	"NtUserMinMaximize",
	"NtUserMNDragLeave",
	"NtUserMNDragOver",
	"NtUserModifyUserStartupInfoFlags",
	"NtUserMoveWindow",
	"NtUserNotifyIMEStatus",
	"NtUserNotifyProcessCreate",
	"NtUserNotifyWinEvent",
	"NtUserOpenClipboard",
	"NtUserOpenDesktop",
	"NtUserOpenInputDesktop",
	"NtUserOpenWindowStation",
	"NtUserPaintDesktop",
	"NtUserPeekMessage",
	"NtUserPostMessage",
	"NtUserPostThreadMessage",
	"NtUserPrintWindow",
	"NtUserProcessConnect",
	"NtUserQueryInformationThread",
	"NtUserQueryInputContext",
	"NtUserQuerySendMessage",
	"NtUserQueryWindow",
	"NtUserRealChildWindowFromPoint",
	"NtUserRealInternalGetMessage",
	"NtUserRealWaitMessageEx",
	"NtUserRedrawWindow",
	"NtUserRegisterClassExWOW",
	"NtUserRegisterUserApiHook",
	"NtUserRegisterHotKey",
	"NtUserRegisterRawInputDevices",
	"NtUserRegisterTasklist",
	"NtUserRegisterWindowMessage",
	"NtUserRemoveMenu",
	"NtUserRemoveProp",
	"NtUserResolveDesktop",
	"NtUserResolveDesktopForWOW",
	"NtUserSBGetParms",
	"NtUserScrollDC",
	"NtUserScrollWindowEx",
	"NtUserSelectPalette",
	"NtUserSendInput",
	"NtUserSetActiveWindow",
	"NtUserSetAppImeLeve",
	"NtUserSetCapture",
	"NtUserSetClassLong",
	"NtUserSetClassWord",
	"NtUserSetClipboardData",
	"NtUserSetClipboardViewer",
	"NtUserSetConsoleReserveKeys",
	"NtUserSetCursor",
	"NtUserSetCursorContents",
	"NtUserSetCursorIconData",
	"NtUserSetFocus",
	"NtUserSetImeHotKey",
	"NtUserSetImeInfoEx",
	"NtUserSetImeOwnerWindow",
	"NtUserSetInformationProcess",
	"NtUserSetInformationThread",
	"NtUserSetInternalWindowPos",
	"NtUserSetKeyboardState",
	"NtUserSetLogonNotifyWindow",
	"NtUserSetMenu",
	"NtUserSetMenuContextHelpId",
	"NtUserSetMenuDefaultItem",
	"NtUserSetMenuFlagRto",
	"NtUserSetObjectInformation",
	"NtUserSetParent",
	"NtUserSetProcessWindowStation",
	"NtUserSetProp",
	"NtUserSetScrollInfo",
	"NtUserSetShellWindowEx",
	"NtUserSetSysColors",
	"NtUserSetSystemCursor",
	"NtUserSetSystemMenu",
	"NtUserSetSystemTimer",
	"NtUserSetThreadDesktop",
	"NtUserSetThreadLayoutHandles",
	"NtUserSetThreadState",
	"NtUserSetTimer",
	"NtUserSetWindowFNID",
	"NtUserSetWindowLong",
	"NtUserSetWindowPlacement",
	"NtUserSetWindowPos",
	"NtUserSetWindowRgn",
	"NtUserSetWindowsHookAW",
	"NtUserSetWindowsHookEx",
	"NtUserSetWindowStationUser",
	"NtUserSetWindowWord",
	"NtUserSetWinEventHook",
	"NtUserShowCaret",
	"NtUserShowScrollBar",
	"NtUserShowWindow",
	"NtUserShowWindowAsync",
	"NtUserSoundSentry",
	"NtUserSwitchDesktop",
	"NtUserSystemParametersInfo",
	"NtUserTestForInteractiveUser",
	"NtUserThunkedMenuInfo",
	"NtUserThunkedMenuItemInfo",
	"NtUserToUnicodeEx",
	"NtUserTrackMouseEvent",
	"NtUserTrackPopupMenuEx",
	"NtUserCalcMenuBar",
	"NtUserPaintMenuBar",
	"NtUserTranslateAccelerator",
	"NtUserTranslateMessage",
	"NtUserUnhookWindowsHookEx",
	"NtUserUnhookWinEvent",
	"NtUserUnloadKeyboardLayout",
	"NtUserUnlockWindowStation",
	"NtUserUnregisterClass",
	"NtUserUnregisterUserApiHook",
	"NtUserUnregisterHotKey",
	"NtUserUpdateInputContext",
	"NtUserUpdateInstance",
	"NtUserUpdateLayeredWindow",
	"NtUserGetLayeredWindowAttributes",
	"NtUserSetLayeredWindowAttributes",
	"NtUserUpdatePerUserSystemParameters",
	"NtUserUserHandleGrantAccess",
	"NtUserValidateHandleSecure",
	"NtUserValidateRect",
	"NtUserValidateTimerCallback",
	"NtUserVkKeyScanEx",
	"NtUserWaitForInputIdle",
	"NtUserWaitForMsgAndEvent",
	"NtUserWaitMessage",
	"NtUserWin32PoolAllocationStats",
	"NtUserWindowFromPoint",
	"NtUserYieldTask",
	"NtUserRemoteConnect",
	"NtUserRemoteRedrawRectangle",
	"NtUserRemoteRedrawScreen",
	"NtUserRemoteStopScreenUpdates",
	"NtUserCtxDisplayIOCt",
	"NtGdiEngAssociateSurface",
	"NtGdiEngCreateBitmap",
	"NtGdiEngCreateDeviceSurface",
	"NtGdiEngCreateDeviceBitmap",
	"NtGdiEngCreatePalette",
	"NtGdiEngComputeGlyphSet",
	"NtGdiEngCopyBits",
	"NtGdiEngDeletePalette",
	"NtGdiEngDeleteSurface",
	"NtGdiEngEraseSurface",
	"NtGdiEngUnlockSurface",
	"NtGdiEngLockSurface",
	"NtGdiEngBitBlt",
	"NtGdiEngStretchBlt",
	"NtGdiEngPlgBlt",
	"NtGdiEngMarkBandingSurface",
	"NtGdiEngStrokePath",
	"NtGdiEngFillPath",
	"NtGdiEngStrokeAndFillPath",
	"NtGdiEngPaint",
	"NtGdiEngLineTo",
	"NtGdiEngAlphaBlend",
	"NtGdiEngGradientFil",
	"NtGdiEngTransparentBlt",
	"NtGdiEngTextOut",
	"NtGdiEngStretchBltROP",
	"NtGdiXLATEOBJ_cGetPalette",
	"NtGdiXLATEOBJ_iXlate",
	"NtGdiXLATEOBJ_hGetColorTransform",
	"NtGdiCLIPOBJ_bEnum",
	"NtGdiCLIPOBJ_cEnumStart",
	"NtGdiCLIPOBJ_ppoGetPath",
	"NtGdiEngDeletePath",
	"NtGdiEngCreateClip",
	"NtGdiEngDeleteClip",
	"NtGdiBRUSHOBJ_ulGetBrushColor",
	"NtGdiBRUSHOBJ_pvAllocRbrush",
	"NtGdiBRUSHOBJ_pvGetRbrush",
	"NtGdiBRUSHOBJ_hGetColorTransform",
	"NtGdiXFORMOBJ_bApplyXform",
	"NtGdiXFORMOBJ_iGetXform",
	"NtGdiFONTOBJ_vGetInfo",
	"NtGdiFONTOBJ_pxoGetXform",
	"NtGdiFONTOBJ_cGetGlyphs",
	"NtGdiFONTOBJ_pifi",
	"NtGdiFONTOBJ_pfdg",
	"NtGdiFONTOBJ_pQueryGlyphAttrs",
	"NtGdiFONTOBJ_pvTrueTypeFontFile",
	"NtGdiFONTOBJ_cGetAllGlyphHandles",
	"NtGdiSTROBJ_bEnum",
	"NtGdiSTROBJ_bEnumPositionsOnly",
	"NtGdiSTROBJ_bGetAdvanceWidths",
	"NtGdiSTROBJ_vEnumStart",
	"NtGdiSTROBJ_dwGetCodePage",
	"NtGdiPATHOBJ_vGetBounds",
	"NtGdiPATHOBJ_bEnum",
	"NtGdiPATHOBJ_vEnumStart",
	"NtGdiPATHOBJ_vEnumStartClipLines",
	"NtGdiPATHOBJ_bEnumClipLines",
	"NtGdiGetDhpdev",
	"NtGdiEngCheckAbort",
	"NtGdiHT_Get8BPPFormatPalette",
	"NtGdiHT_Get8BPPMaskPalette",
	"NtGdiUpdateTransform",
	"NtGdiSetPUMPDOBJ",
	"NtGdiBRUSHOBJ_DeleteRbrush",
	"NtGdiUMPDEngFreeUserMem",
	"NTGdiDrawStream",
	"DUMPDDryQuerySpoolType",
	"NtGdiMakeObjectUnXferable"
};

CHAR VistaProcName[][50]=
{
	"NtGdiAbortDoc",
	"NtGdiAbortPath",
	"NtGdiAddFontResourceW",
	"NtGdiAddRemoteFontToDC",
	"NtGdiAddFontMemResourceEx",
	"NtGdiRemoveMergeFont",
	"NtGdiAddRemoteMMInstanceToDC",
	"NtGdiAlphaBlend",
	"NtGdiAngleArc",
	"NtGdiAnyLinkedFonts",
	"NtGdiFontIsLinked",
	"NtGdiArcInterna",
	"NtGdiBeginPath",
	"NtGdiBitBlt",
	"NtGdiCancelDC",
	"NtGdiCheckBitmapBits",
	"NtGdiCloseFigure",
	"NtGdiClearBitmapAttributes",
	"NtGdiClearBrushAttributes",
	"NtGdiColorCorrectPalette",
	"NtGdiCombineRgn",
	"NtGdiCombineTransform",
	"NtGdiComputeXformCoefficients",
	"NtGdiConfigureOPMProtectedOutput",
	"NtGdiConsoleTextOut",
	"NtGdiConvertMetafileRect",
	"NtGdiCreateBitmap",
	"NtGdiCreateClientObj",
	"NtGdiCreateColorSpace",
	"NtGdiCreateColorTransform",
	"NtGdiCreateCompatibleBitmap",
	"NtGdiCreateCompatibleDC",
	"NtGdiCreateDIBBrush",
	"NtGdiCreateDIBitmapInterna",
	"NtGdiCreateDIBSection",
	"NtGdiCreateEllipticRgn",
	"NtGdiCreateHalftonePalette",
	"NtGdiCreateHatchBrushInterna",
	"NtGdiCreateMetafileDC",
	"NtGdiCreateOPMProtectedOutputs",
	"NtGdiCreatePaletteInterna",
	"NtGdiCreatePatternBrushInterna",
	"NtGdiCreatePen",
	"NtGdiCreateRectRgn",
	"NtGdiCreateRoundRectRgn",
	"NtGdiCreateServerMetaFile",
	"NtGdiCreateSolidBrush",
	"NtGdiD3dContextCreate",
	"NtGdiD3dContextDestroy",
	"NtGdiD3dContextDestroyAl",
	"NtGdiD3dValidateTextureStageState",
	"NtGdiD3dDrawPrimitives2",
	"NtGdiDdGetDriverState",
	"NtGdiDdAddAttachedSurface",
	"NtGdiDdAlphaBlt",
	"NtGdiDdAttachSurface",
	"NtGdiDdBeginMoCompFrame",
	"NtGdiDdBlt",
	"NtGdiDdCanCreateSurface",
	"NtGdiDdCanCreateD3DBuffer",
	"NtGdiDdColorContro",
	"NtGdiDdCreateDirectDrawObject",
	"NtGdiDdCreateSurface",
	"NtGdiDdCreateD3DBuffer",
	"NtGdiDdCreateMoComp",
	"NtGdiDdCreateSurfaceObject",
	"NtGdiDdDeleteDirectDrawObject",
	"NtGdiDdDeleteSurfaceObject",
	"NtGdiDdDestroyMoComp",
	"NtGdiDdDestroySurface",
	"NtGdiDdDestroyD3DBuffer",
	"NtGdiDdEndMoCompFrame",
	"NtGdiDdFlip",
	"NtGdiDdFlipToGDISurface",
	"NtGdiDdGetAvailDriverMemory",
	"NtGdiDdGetBltStatus",
	"NtGdiDdGetDC",
	"NtGdiDdGetDriverInfo",
	"NtGdiDdGetDxHandle",
	"NtGdiDdGetFlipStatus",
	"NtGdiDdGetInternalMoCompInfo",
	"NtGdiDdGetMoCompBuffInfo",
	"NtGdiDdGetMoCompGuids",
	"NtGdiDdGetMoCompFormats",
	"NtGdiDdGetScanLine",
	"NtGdiDdLock",
	"NtGdiDdLockD3D",
	"NtGdiDdQueryDirectDrawObject",
	"NtGdiDdQueryMoCompStatus",
	"NtGdiDdReenableDirectDrawObject",
	"NtGdiDdReleaseDC",
	"NtGdiDdRenderMoComp",
	"NtGdiDdResetVisrgn",
	"NtGdiDdSetColorKey",
	"NtGdiDdSetExclusiveMode",
	"NtGdiDdSetGammaRamp",
	"NtGdiDdCreateSurfaceEx",
	"NtGdiDdSetOverlayPosition",
	"NtGdiDdUnattachSurface",
	"NtGdiDdUnlock",
	"NtGdiDdUnlockD3D",
	"NtGdiDdUpdateOverlay",
	"NtGdiDdWaitForVerticalBlank",
	"NtGdiDvpCanCreateVideoPort",
	"NtGdiDvpColorContro",
	"NtGdiDvpCreateVideoPort",
	"NtGdiDvpDestroyVideoPort",
	"NtGdiDvpFlipVideoPort",
	"NtGdiDvpGetVideoPortBandwidth",
	"NtGdiDvpGetVideoPortField",
	"NtGdiDvpGetVideoPortFlipStatus",
	"NtGdiDvpGetVideoPortInputFormats",
	"NtGdiDvpGetVideoPortLine",
	"NtGdiDvpGetVideoPortOutputFormats",
	"NtGdiDvpGetVideoPortConnectInfo",
	"NtGdiDvpGetVideoSignalStatus",
	"NtGdiDvpUpdateVideoPort",
	"NtGdiDvpWaitForVideoPortSync",
	"NtGdiDvpAcquireNotification",
	"NtGdiDvpReleaseNotification",
	"NtGdiDxgGenericThunk",
	"NtGdiDeleteClientObj",
	"NtGdiDeleteColorSpace",
	"NtGdiDeleteColorTransform",
	"NtGdiDeleteObjectApp",
	"NtGdiDescribePixelFormat",
	"NtGdiDestroyOPMProtectedOutput",
	"NtGdiGetPerBandInfo",
	"NtGdiDoBanding",
	"NtGdiDoPalette",
	"NtGdiDrawEscape",
	"NtGdiEllipse",
	"NtGdiEnableEudc",
	"NtGdiEndDoc",
	"NtGdiEndPage",
	"NtGdiEndPath",
	"NtGdiEnumFontChunk",
	"NtGdiEnumFontClose",
	"NtGdiEnumFontOpen",
	"NtGdiEnumObjects",
	"NtGdiEqualRgn",
	"NtGdiEudcLoadUnloadLink",
	"NtGdiExcludeClipRect",
	"NtGdiExtCreatePen",
	"NtGdiExtCreateRegion",
	"NtGdiExtEscape",
	"NtGdiExtFloodFil",
	"NtGdiExtGetObjectW",
	"NtGdiExtSelectClipRgn",
	"NtGdiExtTextOutW",
	"NtGdiFillPath",
	"NtGdiFillRgn",
	"NtGdiFlattenPath",
	"NtGdiFlush",
	"NtGdiForceUFIMapping",
	"NtGdiFrameRgn",
	"NtGdiFullscreenContro",
	"NtGdiGetAndSetDCDword",
	"NtGdiGetAppClipBox",
	"NtGdiGetBitmapBits",
	"NtGdiGetBitmapDimension",
	"NtGdiGetBoundsRect",
	"NtGdiGetCertificate",
	"NtGdiGetCertificateSize",
	"NtGdiGetCharABCWidthsW",
	"NtGdiGetCharacterPlacementW",
	"NtGdiGetCharSet",
	"NtGdiGetCharWidthW",
	"NtGdiGetCharWidthInfo",
	"NtGdiGetColorAdjustment",
	"NtGdiGetColorSpaceforBitmap",
	"NtGdiGetCOPPCompatibleOPMInformation",
	"NtGdiGetDCDword",
	"NtGdiGetDCforBitmap",
	"NtGdiGetDCObject",
	"NtGdiGetDCPoint",
	"NtGdiGetDeviceCaps",
	"NtGdiGetDeviceGammaRamp",
	"NtGdiGetDeviceCapsAl",
	"NtGdiGetDIBitsInterna",
	"NtGdiGetETM",
	"NtGdiGetEudcTimeStampEx",
	"NtGdiGetFontData",
	"NtGdiGetFontResourceInfoInternalW",
	"NtGdiGetGlyphIndicesW",
	"NtGdiGetGlyphIndicesWInterna",
	"NtGdiGetGlyphOutline",
	"NtGdiGetOPMInformation",
	"NtGdiGetKerningPairs",
	"NtGdiGetLinkedUFIs",
	"NtGdiGetMiterLimit",
	"NtGdiGetMonitorID",
	"NtGdiGetNearestColor",
	"NtGdiGetNearestPaletteIndex",
	"NtGdiGetObjectBitmapHandle",
	"NtGdiGetOPMRandomNumber",
	"NtGdiGetOutlineTextMetricsInternalW",
	"NtGdiGetPath",
	"NtGdiGetPixe",
	"NtGdiGetRandomRgn",
	"NtGdiGetRasterizerCaps",
	"NtGdiGetRealizationInfo",
	"NtGdiGetRegionData",
	"NtGdiGetRgnBox",
	"NtGdiGetServerMetaFileBits",
	"NtGdiGetSpoolMessage",
	"NtGdiGetStats",
	"NtGdiGetStockObject",
	"NtGdiGetStringBitmapW",
	"NtGdiGetSuggestedOPMProtectedOutputArraySize",
	"NtGdiGetSystemPaletteUse",
	"NtGdiGetTextCharsetInfo",
	"NtGdiGetTextExtent",
	"NtGdiGetTextExtentExW",
	"NtGdiGetTextFaceW",
	"NtGdiGetTextMetricsW",
	"NtGdiGetTransform",
	"NtGdiGetUFI",
	"NtGdiGetEmbUFI",
	"NtGdiGetUFIPathname",
	"NtGdiGetEmbedFonts",
	"NtGdiChangeGhostFont",
	"NtGdiAddEmbFontToDC",
	"NtGdiGetFontUnicodeRanges",
	"NtGdiGetWidthTable",
	"NtGdiGradientFil",
	"NtGdiHfontCreate",
	"NtGdiIcmBrushInfo",
	"bInitRedirDev",
	"NtGdiInitSpoo",
	"NtGdiIntersectClipRect",
	"NtGdiInvertRgn",
	"NtGdiLineTo",
	"NtGdiMakeFontDir",
	"NtGdiMakeInfoDC",
	"NtGdiMaskBlt",
	"NtGdiModifyWorldTransform",
	"NtGdiMonoBitmap",
	"NtGdiMoveTo",
	"NtGdiOffsetClipRgn",
	"NtGdiOffsetRgn",
	"NtGdiOpenDCW",
	"NtGdiPatBlt",
	"NtGdiPolyPatBlt",
	"NtGdiPathToRegion",
	"NtGdiPlgBlt",
	"NtGdiPolyDraw",
	"NtGdiPolyPolyDraw",
	"NtGdiPolyTextOutW",
	"NtGdiPtInRegion",
	"NtGdiPtVisible",
	"NtGdiQueryFonts",
	"NtGdiQueryFontAssocInfo",
	"NtGdiRectangle",
	"NtGdiRectInRegion",
	"NtGdiRectVisible",
	"NtGdiRemoveFontResourceW",
	"NtGdiRemoveFontMemResourceEx",
	"NtGdiResetDC",
	"NtGdiResizePalette",
	"NtGdiRestoreDC",
	"NtGdiRoundRect",
	"NtGdiSaveDC",
	"NtGdiScaleViewportExtEx",
	"NtGdiScaleWindowExtEx",
	"NtGdiSelectBitmap",
	"NtGdiSelectBrush",
	"NtGdiSelectClipPath",
	"NtGdiSelectFont",
	"NtGdiSelectPen",
	"NtGdiSetBitmapAttributes",
	"NtGdiSetBitmapBits",
	"NtGdiSetBitmapDimension",
	"NtGdiSetBoundsRect",
	"NtGdiSetBrushAttributes",
	"NtGdiSetBrushOrg",
	"NtGdiSetColorAdjustment",
	"NtGdiSetColorSpace",
	"NtGdiSetDeviceGammaRamp",
	"NtGdiSetDIBitsToDeviceInterna",
	"NtGdiSetFontEnumeration",
	"NtGdiSetFontXform",
	"NtGdiSetIcmMode",
	"NtGdiSetLinkedUFIs",
	"NtGdiSetMagicColors",
	"NtGdiSetMetaRgn",
	"NtGdiSetMiterLimit",
	"NtGdiGetDeviceWidth",
	"NtGdiMirrorWindowOrg",
	"NtGdiSetLayout",
	"NtGdiSetOPMSigningKeyAndSequenceNumbers",
	"NtGdiSetPixe",
	"NtGdiSetPixelFormat",
	"NtGdiSetRectRgn",
	"NtGdiSetSystemPaletteUse",
	"NtGdiSetTextJustification",
	"NtGdiSetupPublicCFONT",
	"NtGdiSetVirtualResolution",
	"NtGdiSetSizeDevice",
	"NtGdiStartDoc",
	"NtGdiStartPage",
	"NtGdiStretchBlt",
	"NtGdiStretchDIBitsInterna",
	"NtGdiStrokeAndFillPath",
	"NtGdiStrokePath",
	"NtGdiSwapBuffers",
	"NtGdiTransformPoints",
	"NtGdiTransparentBlt",
	"DxgStubDvpGetVideoPortFlipStatus",
	"NtGdiUMPDEngFreeUserMem",
	"NtGdiUnrealizeObject",
	"NtGdiUpdateColors",
	"NtGdiWidenPath",
	"NtUserActivateKeyboardLayout",
	"NtUserAddClipboardFormatListener",
	"NtUserAlterWindowStyle",
	"NtUserAssociateInputContext",
	"NtUserAttachThreadInput",
	"NtUserBeginPaint",
	"NtUserBitBltSysBmp",
	"NtUserBlockInput",
	"NtUserBuildHimcList",
	"NtUserBuildHwndList",
	"NtUserBuildNameList",
	"NtUserBuildPropList",
	"NtUserCallHwnd",
	"NtUserCallHwndLock",
	"NtUserCallHwndOpt",
	"NtUserCallHwndParam",
	"NtUserCallHwndParamLock",
	"NtUserCallMsgFilter",
	"NtUserCallNextHookEx",
	"NtUserCallNoParam",
	"NtUserCallOneParam",
	"NtUserCallTwoParam",
	"NtUserChangeClipboardChain",
	"NtUserChangeDisplaySettings",
	"NtUserCheckAccessForIntegrityLeve",
	"NtUserCheckDesktopByThreadId",
	"NtUserCheckWindowThreadDesktop",
	"NtUserCheckImeHotKey",
	"NtUserCheckMenuItem",
	"NtUserChildWindowFromPointEx",
	"NtUserClipCursor",
	"NtUserCloseClipboard",
	"NtUserCloseDesktop",
	"NtUserCloseWindowStation",
	"NtUserConsoleContro",
	"NtUserConvertMemHandle",
	"NtUserCopyAcceleratorTable",
	"NtUserCountClipboardFormats",
	"NtUserCreateAcceleratorTable",
	"NtUserCreateCaret",
	"NtUserCreateDesktopEx",
	"NtUserCreateInputContext",
	"NtUserCreateLocalMemHandle",
	"NtUserCreateWindowEx",
	"NtUserCreateWindowStation",
	"NtUserDdeInitialize",
	"NtUserDeferWindowPos",
	"NtUserDefSetText",
	"NtUserDeleteMenu",
	"NtUserDestroyAcceleratorTable",
	"NtUserDestroyCursor",
	"NtUserDestroyInputContext",
	"NtUserDestroyMenu",
	"NtUserDestroyWindow",
	"NtUserDisableThreadIme",
	"NtUserDispatchMessage",
	"NtUserDoSoundConnect",
	"NtUserDoSoundDisconnect",
	"NtUserDragDetect",
	"NtUserDragObject",
	"NtUserDrawAnimatedRects",
	"NtUserDrawCaption",
	"NtUserDrawCaptionTemp",
	"NtUserDrawIconEx",
	"NtUserDrawMenuBarTemp",
	"NtUserEmptyClipboard",
	"NtUserEnableMenuItem",
	"NtUserEnableScrollBar",
	"NtUserEndDeferWindowPosEx",
	"NtUserEndMenu",
	"NtUserEndPaint",
	"NtUserEnumDisplayDevices",
	"NtUserEnumDisplayMonitors",
	"NtUserEnumDisplaySettings",
	"NtUserEvent",
	"NtUserExcludeUpdateRgn",
	"NtUserFillWindow",
	"NtUserFindExistingCursorIcon",
	"NtUserFindWindowEx",
	"NtUserFlashWindowEx",
	"NtUserFrostCrashedWindow",
	"NtUserGetAltTabInfo",
	"NtUserGetAncestor",
	"NtUserGetAppImeLeve",
	"NtUserGetAsyncKeyState",
	"NtUserGetAtomName",
	"NtUserGetCaretBlinkTime",
	"NtUserGetCaretPos",
	"NtUserGetClassInfoEx",
	"NtUserGetClassName",
	"NtUserGetClipboardData",
	"NtUserGetClipboardFormatName",
	"NtUserGetClipboardOwner",
	"NtUserGetClipboardSequenceNumber",
	"NtUserGetClipboardViewer",
	"NtUserGetClipCursor",
	"NtUserGetComboBoxInfo",
	"NtUserGetControlBrush",
	"NtUserGetControlColor",
	"NtUserGetCPD",
	"NtUserGetCursorFrameInfo",
	"NtUserGetCursorInfo",
	"NtUserGetDC",
	"NtUserGetDCEx",
	"NtUserGetDoubleClickTime",
	"NtUserGetForegroundWindow",
	"NtUserGetGuiResources",
	"NtUserGetGUIThreadInfo",
	"NtUserGetIconInfo",
	"NtUserGetIconSize",
	"NtUserGetImeHotKey",
	"NtUserGetImeInfoEx",
	"NtUserGetInternalWindowPos",
	"NtUserGetKeyboardLayoutList",
	"NtUserGetKeyboardLayoutName",
	"NtUserGetKeyboardState",
	"NtUserGetKeyNameText",
	"NtUserGetKeyState",
	"NtUserGetListBoxInfo",
	"NtUserGetMenuBarInfo",
	"NtUserGetMenuIndex",
	"NtUserGetMenuItemRect",
	"NtUserGetMessage",
	"NtUserGetMouseMovePointsEx",
	"NtUserGetObjectInformation",
	"NtUserGetOpenClipboardWindow",
	"NtUserGetPriorityClipboardFormat",
	"NtUserGetProcessWindowStation",
	"NtUserGetRawInputBuffer",
	"NtUserGetRawInputData",
	"NtUserGetRawInputDeviceInfo",
	"NtUserGetRawInputDeviceList",
	"NtUserGetRegisteredRawInputDevices",
	"NtUserGetScrollBarInfo",
	"NtUserGetSystemMenu",
	"NtUserGetThreadDesktop",
	"NtUserGetThreadState",
	"NtUserGetTitleBarInfo",
	"NtUserGetUpdatedClipboardFormats",
	"NtUserGetUpdateRect",
	"NtUserGetUpdateRgn",
	"NtUserGetWindowDC",
	"NtUserGetWindowPlacement",
	"NtUserGetWOWClass",
	"NtUserGhostWindowFromHungWindow",
	"NtUserHardErrorContro",
	"NtUserHideCaret",
	"NtUserHiliteMenuItem",
	"NtUserHungWindowFromGhostWindow",
	"NtUserImpersonateDdeClientWindow",
	"NtUserInitialize",
	"NtUserInitializeClientPfnArrays",
	"NtUserInitTask",
	"NtUserInternalGetWindowText",
	"NtUserInternalGetWindowIcon",
	"NtUserInvalidateRect",
	"NtUserInvalidateRgn",
	"NtUserIsClipboardFormatAvailable",
	"NtUserKillTimer",
	"NtUserLoadKeyboardLayoutEx",
	"NtUserLockWindowStation",
	"NtUserLockWindowUpdate",
	"NtUserLockWorkStation",
	"NtUserLogicalToPhysicalPoint",
	"NtUserMapVirtualKeyEx",
	"NtUserMenuItemFromPoint",
	"NtUserMessageCall",
	"NtUserMinMaximize",
	"NtUserMNDragLeave",
	"NtUserMNDragOver",
	"NtUserModifyUserStartupInfoFlags",
	"NtUserMoveWindow",
	"NtUserNotifyIMEStatus",
	"NtUserNotifyProcessCreate",
	"NtUserNotifyWinEvent",
	"NtUserOpenClipboard",
	"NtUserOpenDesktop",
	"NtUserOpenInputDesktop",
	"NtUserOpenThreadDesktop",
	"NtUserOpenWindowStation",
	"NtUserPaintDesktop",
	"NtUserPaintMonitor",
	"NtUserPhysicalToLogicalPoint",
	"NtUserPostMessage",
	"NtUserPostThreadMessage",
	"NtUserPrintWindow",
	"NtUserProcessConnect",
	"NtUserQueryInformationThread",
	"NtUserQueryInputContext",
	"NtUserQuerySendMessage",
	"NtUserQueryWindow",
	"NtUserRealChildWindowFromPoint",
	"NtUserRealInternalGetMessage",
	"NtUserRealWaitMessageEx",
	"NtUserRedrawWindow",
	"NtUserRegisterClassExWOW",
	"NtUserRegisterErrorReportingDialog",
	"NtUserRegisterUserApiHook",
	"NtUserRegisterHotKey",
	"NtUserRegisterRawInputDevices",
	"NtUserRegisterTasklist",
	"NtUserRegisterWindowMessage",
	"NuUserRemoveClipborardFormatListener",
	"NtUserRemoveMenu",
	"NtUserRemoveProp",
	"NtUserResolveDesktop",
	"NtUserResolveDesktopForWOW",
	"NtUserSBGetParms",
	"NtUserScrollDC",
	"NtUserScrollWindowEx",
	"NtUserSelectPalette",
	"NtUserSendInput",
	"NtUserSetActiveWindow",
	"NtUserSetAppImeLeve",
	"NtUserSetCapture",
	"NtUserSetClassLong",
	"NtUserSetClassWord",
	"NtUserSetClipboardData",
	"NtUserSetClipboardViewer",
	"NtUserSetConsoleReserveKeys",
	"NtUserSetCursor",
	"NtUserSetCursorContents",
	"NtUserSetCursorIconData",
	"NtUserSetFocus",
	"NtUserSetImeHotKey",
	"NtUserSetImeInfoEx",
	"NtUserSetImeOwnerWindow",
	"NtUserSetInformationProcess",
	"NtUserSetInformationThread",
	"NtUserSetInternalWindowPos",
	"NtUserSetKeyboardState",
	"NtUserSetLogonNotifyWindow",
	"NtUserSetMenu",
	"NtUserSetMenuContextHelpId",
	"NtUserSetMenuDefaultItem",
	"NtUserSetMenuFlagRto",
	"NtUserSetObjectInformation",
	"NtUserSetParent",
	"NtUserSetProcessWindowStation",
	"NtUserGetProp",
	"NtUserSetProp",
	"NtUserSetScrollInfo",
	"NtUserSetShellWindowEx",
	"NtUserSetSysColors",
	"NtUserSetSystemCursor",
	"NtUserSetSystemMenu",
	"NtUserSetSystemTimer",
	"NtUserSetThreadDesktop",
	"NtUserSetThreadLayoutHandles",
	"NtUserSetThreadState",
	"NtUserSetTimer",
	"NtUserSetProcessDPIAware",
	"NtUserSetWindowFNID",
	"NtUserSetWindowLong",
	"NtUserSetWindowPlacement",
	"NtUserSetWindowPos",
	"NtUserSetWindowRgn",
	"NtUserGetWindowRgnEx",
	"NtUserSetWindowRgnEx",
	"NtUserSetWindowsHookAW",
	"NtUserSetWindowsHookEx",
	"NtUserSetWindowStationUser",
	"NtUserSetWindowWord",
	"NtUserSetWinEventHook",
	"NtUserShowCaret",
	"NtUserShowScrollBar",
	"NtUserShowWindow",
	"NtUserShowWindowAsync",
	"NtUserSoundSentry",
	"NtUserSwitchDesktop",
	"NtUserSystemParametersInfo",
	"NtUserTestForInteractiveUser",
	"NtUserThunkedMenuInfo",
	"NtUserThunkedMenuItemInfo",
	"NtUserToUnicodeEx",
	"NtUserTrackMouseEvent",
	"NtUserTrackPopupMenuEx",
	"NtUserCalcMenuBar",
	"NtUserPaintMenuBar",
	"NtUserTranslateAccelerator",
	"NtUserTranslateMessage",
	"NtUserUnhookWindowsHookEx",
	"NtUserUnhookWinEvent",
	"NtUserUnloadKeyboardLayout",
	"NtUserUnlockWindowStation",
	"NtUserUnregisterClass",
	"NtUserUnregisterUserApiHook",
	"NtUserUnregisterHotKey",
	"NtUserUpdateInputContext",
	"NtUserUpdateInstance",
	"NtUserUpdateLayeredWindow",
	"NtUserGetLayeredWindowAttributes",
	"NtUserSetLayeredWindowAttributes",
	"NtUserUpdatePerUserSystemParameters",
	"NtUserUserHandleGrantAccess",
	"NtUserValidateHandleSecure",
	"NtUserValidateRect",
	"NtUserValidateTimerCallback",
	"NtUserVkKeyScanEx",
	"NtUserWaitForInputIdle",
	"NtUserWaitForMsgAndEvent",
	"NtUserWaitMessage",
	"DxgStubGenericThunk",
	"NtUserWindowFromPhysicalPoint",
	"NtUserWindowFromPoint",
	"NtUserYieldTask",
	"NtUserRemoteConnect",
	"NtUserRemoteRedrawRectangle",
	"NtUserRemoteRedrawScreen",
	"NtUserRemoteStopScreenUpdates",
	"NtUserCtxDisplayIOCt",
	"NtUserRegisterSessionPort",
	"NtUserUnregisterSessionPort",
	"NtUserUpdataWindowTransform",
	"NtUserDwmStartRedirection",
	"NtUserDwmStopRedirection",
	"NtUserDwmHintDxUpdate",
	"NtUserDwmGetDxRgn",
	"NtUserGetWindowMinimizeRect",
	"NtGdiEngAssociateSurface",
	"NtGdiEngCreateBitmap",
	"NtGdiEngCreateDeviceSurface",
	"NtGdiEngCreateDeviceBitmap",
	"NtGdiEngCreatePalette",
	"NtGdiEngComputeGlyphSet",
	"NtGdiEngCopyBits",
	"NtGdiEngDeletePalette",
	"NtGdiEngDeleteSurface",
	"NtGdiEngEraseSurface",
	"NtGdiEngUnlockSurface",
	"NtGdiEngLockSurface",
	"NtGdiEngBitBlt",
	"NtGdiEngStretchBlt",
	"NtGdiEngPlgBlt",
	"NtGdiEngMarkBandingSurface",
	"NtGdiEngStrokePath",
	"NtGdiEngFillPath",
	"NtGdiEngStrokeAndFillPath",
	"NtGdiEngPaint",
	"NtGdiEngLineTo",
	"NtGdiEngAlphaBlend",
	"NtGdiEngGradientFil",
	"NtGdiEngTransparentBlt",
	"NtGdiEngTextOut",
	"NtGdiEngStretchBltROP",
	"NtGdiXLATEOBJ_cGetPalette",
	"NtGdiXLATEOBJ_iXlate",
	"NtGdiXLATEOBJ_hGetColorTransform",
	"NtGdiCLIPOBJ_bEnum",
	"NtGdiCLIPOBJ_cEnumStart",
	"NtGdiCLIPOBJ_ppoGetPath",
	"NtGdiEngDeletePath",
	"NtGdiEngCreateClip",
	"NtGdiEngDeleteClip",
	"NtGdiBRUSHOBJ_ulGetBrushColor",
	"NtGdiBRUSHOBJ_pvAllocRbrush",
	"NtGdiBRUSHOBJ_pvGetRbrush",
	"NtGdiBRUSHOBJ_hGetColorTransform",
	"NtGdiXFORMOBJ_bApplyXform",
	"NtGdiXFORMOBJ_iGetXform",
	"NtGdiFONTOBJ_vGetInfo",
	"NtGdiFONTOBJ_pxoGetXform",
	"NtGdiFONTOBJ_cGetGlyphs",
	"NtGdiFONTOBJ_pifi",
	"NtGdiFONTOBJ_pfdg",
	"NtGdiFONTOBJ_pQueryGlyphAttrs",
	"NtGdiFONTOBJ_pvTrueTypeFontFile",
	"NtGdiFONTOBJ_cGetAllGlyphHandles",
	"NtGdiSTROBJ_bEnum",
	"NtGdiSTROBJ_bEnumPositionsOnly",
	"NtGdiSTROBJ_bGetAdvanceWidths",
	"NtGdiSTROBJ_vEnumStart",
	"NtGdiSTROBJ_dwGetCodePage",
	"NtGdiPATHOBJ_vGetBounds",
	"NtGdiPATHOBJ_bEnum",
	"NtGdiPATHOBJ_vEnumStart",
	"NtGdiPATHOBJ_vEnumStartClipLines",
	"NtGdiPATHOBJ_bEnumClipLines",
	"NtGdiGetDhpdev",
	"NtGdiEngCheckAbort",
	"NtGdiHT_Get8BPPFormatPalette",
	"NtGdiHT_Get8BPPMaskPalette",
	"NtGdiUpdateTransform",
	"NtGdiSetPUMPDOBJ",
	"NtGdiBRUSHOBJ_DeleteRbrush",
	"NtGdiUMPDEngFreeUserMem",
	"NtGdiDrawStream",
	"NtGdiDwmGetDirtyRgn",
	"NtGdiDwnGetSurfaceData",
	"NtGdiDdDDICreateAllocation",
	"NtGdiDdDDIQueryResourceInfo",
	"NtGdiDdDDIOpenResource",
	"NtGdiDdDDIDestroyAllocation",
	"NtGdiDdDDISetAllocationPriority",
	"NtGdiDDIQueryAllocationResidency",
	"NtGdiDdDDICreateDevice",
	"NtGdiDdDDIDestroyDevice",
	"NtGdiDdDDICreateContext",
	"NtGdiDdDDIDestroyContext",
	"NtGdiDdDDICreateSynchronizationObject",
	"NtGdiDdDDIDestroySynchronizationObject",
	"NtGdiDdDDIWaitForSynchronizationObject",
	"NtGdiDdDDISignalSynchronizationObject",
	"NtGdiDdDDIGetRuntimeData",
	"NtGdiDdDDIQueryAdapterInfo",
	"NtGdiDdDDILock",
	"NtGdiDdDDIUnlock",
	"NtGdiDdDDIGetDisplayModeList",
	"NtGdiDdDDISetDisplayMode",
	"NtGdiDdDDIGetMultisampleMethodList",
	"NtGdiDdDDIPresent",
	"NtGdiDdDDIRender",
	"NtGdiDdDDIOpenAdapterFromDeviceName",
	"NtGdiDdDDIOpenAdapterFromHdc",
	"NtGdiDdDDICloseAdapter",
	"NtGdiDdDDIGetSharedPrimaryHandle",
	"NtGdiDdDDIEscape",
	"NtGdiDdDDIQueryStatistics",
	"NtGdiDdDDISetVidPnSourceOwner",
	"NtGdiDdDDIGetPresentHistory",
	"NtGdiDdDDICreateOverlay",
	"NtGdiDdDDIUpdateOverlay",
	"NtGdiDdDDIFlipOverlay",
	"NtGdiDdDDIDestroyOverlay",
	"NtGdiDdDDIWaitForVerticalBlankEvent",
	"NtGdiDdDDISetGammaRamp",
	"NtGdiDdDDIGetDeviceState",
	"NtGdiDdDDICreateDCFromMemory",
	"NtGdiDdDDIDestroyDCFromMemory",
	"NtGdiDdDDISetContextSchedulingPriority",
	"NtGdiDdDDIGetContextSchedulingPriority",
	"NtGdiDdDDISetProcessSchedulingPriorityClass",
	"NtGdiDdDDIGetProcessSchedulingPriorityClass",
	"NtGdiDdDDIReleaseProcessVidPnSourceOwners",
	"NtGdiDdDDIGetScanLine",
	"NtGdiDdDDISetQueuedLimit",
	"NtGdiDdDDIPollDisplayChildren",
	"NtGdiDdDDIInvalidateActiveVidPn",
	"NtGdiDdDDICheckOcclusion",
	"NtGdiDdDDIWaitForIdle",
	"NtGdiDdDDICheckMonitoPowerState",
	"NtGdiDdDDICheckExclusiveOwnership",
	"NtGdiDdDDISetDisplayPrivateDriverFormat",
	"NtGdiDdDDISharedPrimaryLockNotification",
	"NtGdiDdDDISharedPrimaryUnLockNotification",
	"DxgStubDvpGetVideoPortFlipStatus",
	"DxgStubLockDirectDrawSurface",
	"NtGdiGetNumberOfPhysicalMonitors",
	"NtGdiGetPhysicalMonitors",
	"NtGdiGetPhysicalMonitorsDescription",
	"NtGdiDestroyPhysicalMonitor",
	"NtGdiDDCCIGetVCPFeature",
	"NtGdiDDCCISetVCPFeature",
	"NtGdiDDCCISaveCurrentSettings",
	"NtGdiDDCCIGetCapabilitiesStringLength",
	"NtGdiDDCCIGetCapabilitiesString",
	"NtGdiDDCCIGetTimingReport",
	"NtUserSetMirrorRendering",
	"NtUserShowSystemCursor"
};

CHAR Win7ProcName[][50]=
{
	 "NtGdiAbortDoc"
	,"NtGdiAbortPath"
	,"NtGdiAddFontResourceW"
	,"NtGdiAddRemoteFontToDC"
	,"NtGdiAddFontMemResourceEx"
	,"NtGdiRemoveMergeFont"
	,"NtGdiAddRemoteMMInstanceToDC"
	,"NtGdiAlphaBlend"
	,"NtGdiAngleArc"
	,"NtGdiAnyLinkedFonts"
	,"NtGdiFontIsLinked"
	,"NtGdiArcInterna"
	,"NtGdiBeginGdiRendering"
	,"NtGdiBeginPath"
	,"NtGdiBitBlt"
	,"NtGdiCancelDC"
	,"NtGdiCheckBitmapBits"
	,"NtGdiCloseFigure"
	,"NtGdiClearBitmapAttributes"
	,"NtGdiClearBrushAttributes"
	,"NtGdiColorCorrectPalette"
	,"NtGdiCombineRgn"
	,"NtGdiCombineTransform"
	,"NtGdiComputeXformCoefficients"
	,"NtGdiConfigureOPMProtectedOutput"
	,"NtGdiConvertMetafileRect"
	,"NtGdiCreateBitmap"
	,"NtGdiCreateBitmapFromDxSurface"
	,"NtGdiCreateClientObj"
	,"NtGdiCreateColorSpace"
	,"NtGdiCreateColorTransform"
	,"NtGdiCreateCompatibleBitmap"
	,"NtGdiCreateCompatibleDC"
	,"NtGdiCreateDIBBrush"
	,"NtGdiCreateDIBitmapInterna"
	,"NtGdiCreateDIBSection"
	,"NtGdiCreateEllipticRgn"
	,"NtGdiCreateHalftonePalette"
	,"NtGdiCreateHatchBrushInterna"
	,"NtGdiCreateMetafileDC"
	,"NtGdiCreateOPMProtectedOutputs"
	,"NtGdiCreatePaletteInterna"
	,"NtGdiCreatePatternBrushInterna"
	,"NtGdiCreatePen"
	,"NtGdiCreateRectRgn"
	,"NtGdiCreateRoundRectRgn"
	,"NtGdiCreateServerMetaFile"
	,"NtGdiCreateSolidBrush"
	,"NtGdiDdContextCreate"
	,"NtGdiDdContextDestroy"
	,"NtGdiDdContextDestroyAl"
	,"NtGdiDdValidateTextureStageState"
	,"NtGdiDdDrawPrimitives"
	,"NtGdiDdGetDriverState"
	,"NtGdiDdAddAttachedSurface"
	,"NtGdiDdAlphaBlt"
	,"NtGdiDdAttachSurface"
	,"NtGdiDdBeginMoCompFrame"
	,"NtGdiDdBlt"
	,"NtGdiDdCanCreateSurface"
	,"NtGdiDdCanCreateDDBuffer"
	,"NtGdiDdColorContro"
	,"NtGdiDdCreateDirectDrawObject"
	,"NtGdiDdCreateSurface"
	,"NtGdiDdCreateDDBuffer"
	,"NtGdiDdCreateMoComp"
	,"NtGdiDdCreateSurfaceObject"
	,"NtGdiDdDeleteDirectDrawObject"
	,"NtGdiDdDeleteSurfaceObject"
	,"NtGdiDdDestroyMoComp"
	,"NtGdiDdDestroySurface"
	,"NtGdiDdDestroyDDBuffer"
	,"NtGdiDdEndMoCompFrame"
	,"NtGdiDdFlip"
	,"NtGdiDdFlipToGDISurface"
	,"NtGdiDdGetAvailDriverMemory"
	,"NtGdiDdGetBltStatus"
	,"NtGdiDdGetDC"
	,"NtGdiDdGetDriverInfo"
	,"NtGdiDdGetDxHandle"
	,"NtGdiDdGetFlipStatus"
	,"NtGdiDdGetInternalMoCompInfo"
	,"NtGdiDdGetMoCompBuffInfo"
	,"NtGdiDdGetMoCompGuids"
	,"NtGdiDdGetMoCompFormats"
	,"NtGdiDdGetScanLine"
	,"NtGdiDdLock"
	,"NtGdiDdLockDD"
	,"NtGdiDdQueryDirectDrawObject"
	,"NtGdiDdQueryMoCompStatus"
	,"NtGdiDdReenableDirectDrawObject"
	,"NtGdiDdReleaseDC"
	,"NtGdiDdRenderMoComp"
	,"NtGdiDdResetVisrgn"
	,"NtGdiDdSetColorKey"
	,"NtGdiDdSetExclusiveMode"
	,"NtGdiDdSetGammaRamp"
	,"NtGdiDdCreateSurfaceEx"
	,"NtGdiDdSetOverlayPosition"
	,"NtGdiDdUnattachSurface"
	,"NtGdiDdUnlock"
	,"NtGdiDdUnlockDD"
	,"NtGdiDdUpdateOverlay"
	,"NtGdiDdWaitForVerticalBlank"
	,"NtGdiDvpCanCreateVideoPort"
	,"NtGdiDvpColorContro"
	,"NtGdiDvpCreateVideoPort"
	,"NtGdiDvpDestroyVideoPort"
	,"NtGdiDvpFlipVideoPort"
	,"NtGdiDvpGetVideoPortBandwidth"
	,"NtGdiDvpGetVideoPortField"
	,"NtGdiDvpGetVideoPortFlipStatus"
	,"NtGdiDvpGetVideoPortInputFormats"
	,"NtGdiDvpGetVideoPortLine"
	,"NtGdiDvpGetVideoPortOutputFormats"
	,"NtGdiDvpGetVideoPortConnectInfo"
	,"NtGdiDvpGetVideoSignalStatus"
	,"NtGdiDvpUpdateVideoPort"
	,"NtGdiDvpWaitForVideoPortSync"
	,"NtGdiDvpAcquireNotification"
	,"NtGdiDvpReleaseNotification"
	,"NtGdiDxgGenericThunk"
	,"NtGdiDeleteClientObj"
	,"NtGdiDeleteColorSpace"
	,"NtGdiDeleteColorTransform"
	,"NtGdiDeleteObjectApp"
	,"NtGdiDescribePixelFormat"
	,"NtGdiDestroyOPMProtectedOutput"
	,"NtGdiGetPerBandInfo"
	,"NtGdiDoBanding"
	,"NtGdiDoPalette"
	,"NtGdiDrawEscape"
	,"NtGdiEllipse"
	,"NtGdiEnableEudc"
	,"NtGdiEndDoc"
	,"NtGdiEndGdiRendering"
	,"NtGdiEndPage"
	,"NtGdiEndPath"
	,"NtGdiEnumFonts"
	,"NtGdiEnumObjects"
	,"NtGdiEqualRgn"
	,"NtGdiEudcLoadUnloadLink"
	,"NtGdiExcludeClipRect"
	,"NtGdiExtCreatePen"
	,"NtGdiExtCreateRegion"
	,"NtGdiExtEscape"
	,"NtGdiExtFloodFil"
	,"NtGdiExtGetObjectW"
	,"NtGdiExtSelectClipRgn"
	,"NtGdiExtTextOutW"
	,"NtGdiFillPath"
	,"NtGdiFillRgn"
	,"NtGdiFlattenPath"
	,"NtGdiFlush"
	,"NtGdiForceUFIMapping"
	,"NtGdiFrameRgn"
	,"NtGdiFullscreenContro"
	,"NtGdiGetAndSetDCDword"
	,"NtGdiGetAppClipBox"
	,"NtGdiGetBitmapBits"
	,"NtGdiGetBitmapDimension"
	,"NtGdiGetBoundsRect"
	,"NtGdiGetCertificate"
	,"NtGdiGetCertificateSize"
	,"NtGdiGetCharABCWidthsW"
	,"NtGdiGetCharacterPlacementW"
	,"NtGdiGetCharSet"
	,"NtGdiGetCharWidthW"
	,"NtGdiGetCharWidthInfo"
	,"NtGdiGetColorAdjustment"
	,"NtGdiGetColorSpaceforBitmap"
	,"NtGdiGetCOPPCompatibleOPMInformation"
	,"NtGdiGetDCDword"
	,"NtGdiGetDCforBitmap"
	,"NtGdiGetDCObject"
	,"NtGdiGetDCPoint"
	,"NtGdiGetDeviceCaps"
	,"NtGdiGetDeviceGammaRamp"
	,"NtGdiGetDeviceCapsAl"
	,"NtGdiGetDIBitsInterna"
	,"NtGdiGetETM"
	,"NtGdiGetEudcTimeStampEx"
	,"NtGdiGetFontData"
	,"NtGdiGetFontFileData"
	,"NtGdiGetFontFileInfo"
	,"NtGdiGetFontResourceInfoInternalW"
	,"NtGdiGetGlyphIndicesW"
	,"NtGdiGetGlyphIndicesWInterna"
	,"NtGdiGetGlyphOutline"
	,"NtGdiGetOPMInformatio"
	,"NtGdiGetKerningPairs"
	,"NtGdiGetLinkedUFIs"
	,"NtGdiGetMiterLimit"
	,"NtGdiGetMonitorID"
	,"NtGdiGetNearestColor"
	,"NtGdiGetNearestPaletteIndex"
	,"NtGdiGetObjectBitmapHandle"
	,"NtGdiGetOPMRandomNumber"
	,"NtGdiGetOutlineTextMetricsInternalW"
	,"NtGdiGetPath"
	,"NtGdiGetPixe"
	,"NtGdiGetRandomRgn"
	,"NtGdiGetRasterizerCaps"
	,"NtGdiGetRealizationInfo"
	,"NtGdiGetRegionData"
	,"NtGdiGetRgnBox"
	,"NtGdiGetServerMetaFileBits"
	,"DxgStubContextCreate"
	,"NtGdiGetStats"
	,"NtGdiGetStockObject"
	,"NtGdiGetStringBitmapW"
	,"NtGdiGetSuggestedOPMProtectedOutputArra"
	,"NtGdiGetSystemPaletteUse"
	,"NtGdiGetTextCharsetInfo"
	,"NtGdiGetTextExtent"
	,"NtGdiGetTextExtentExW"
	,"NtGdiGetTextFaceW"
	,"NtGdiGetTextMetricsW"
	,"NtGdiGetTransform"
	,"NtGdiGetUFI"
	,"NtGdiGetEmbUFI"
	,"NtGdiGetUFIPathname"
	,"NtGdiGetEmbedFonts"
	,"NtGdiChangeGhostFont"
	,"NtGdiAddEmbFontToDC"
	,"NtGdiGetFontUnicodeRanges"
	,"NtGdiGetWidthTable"
	,"NtGdiGradientFil"
	,"NtGdiHfontCreate"
	,"NtGdiIcmBrushInfo"
	,"IsIMMEnabledSystem"
	,"NtGdiInitSpoo"
	,"NtGdiIntersectClipRect"
	,"NtGdiInvertRgn"
	,"NtGdiLineTo"
	,"NtGdiMakeFontDir"
	,"NtGdiMakeInfoDC"
	,"NtGdiMaskBlt"
	,"NtGdiModifyWorldTransform"
	,"NtGdiMonoBitmap"
	,"NtGdiMoveTo"
	,"NtGdiOffsetClipRgn"
	,"NtGdiOffsetRgn"
	,"NtGdiOpenDCW"
	,"NtGdiPatBlt"
	,"NtGdiPolyPatBlt"
	,"NtGdiPathToRegion"
	,"NtGdiPlgBlt"
	,"NtGdiPolyDraw"
	,"NtGdiPolyPolyDraw"
	,"NtGdiPolyTextOutW"
	,"NtGdiPtInRegion"
	,"NtGdiPtVisible"
	,"NtGdiQueryFonts"
	,"NtGdiQueryFontAssocInfo"
	,"NtGdiRectangle"
	,"NtGdiRectInRegion"
	,"NtGdiRectVisible"
	,"NtGdiRemoveFontResourceW"
	,"NtGdiRemoveFontMemResourceEx"
	,"NtGdiResetDC"
	,"NtGdiResizePalette"
	,"NtGdiRestoreDC"
	,"NtGdiRoundRect"
	,"NtGdiSaveDC"
	,"NtGdiScaleViewportExtEx"
	,"NtGdiScaleWindowExtEx"
	,"GreSelectBitmap"
	,"NtGdiSelectBrush"
	,"NtGdiSelectClipPath"
	,"NtGdiSelectFont"
	,"NtGdiSelectPen"
	,"NtGdiSetBitmapAttributes"
	,"NtGdiSetBitmapBits"
	,"NtGdiSetBitmapDimension"
	,"NtGdiSetBoundsRect"
	,"NtGdiSetBrushAttributes"
	,"NtGdiSetBrushOrg"
	,"NtGdiSetColorAdjustment"
	,"NtGdiSetColorSpace"
	,"NtGdiSetDeviceGammaRamp"
	,"NtGdiSetDIBitsToDeviceInterna"
	,"NtGdiSetFontEnumeration"
	,"NtGdiSetFontXform"
	,"NtGdiSetIcmMode"
	,"NtGdiSetLinkedUFIs"
	,"NtGdiSetMagicColors"
	,"NtGdiSetMetaRgn"
	,"NtGdiSetMiterLimit"
	,"NtGdiGetDeviceWidth"
	,"NtGdiMirrorWindowOrg"
	,"NtGdiSetLayout"
	,"NtGdiSetOPMSigningKeyAndSequenceNumbers"
	,"NtGdiSetPixe"
	,"NtGdiSetPixelFormat"
	,"NtGdiSetRectRgn"
	,"NtGdiSetSystemPaletteUse"
	,"NtGdiSetTextJustification"
	,"NtGdiSetVirtualResolution"
	,"NtGdiSetSizeDevice"
	,"NtGdiStartDoc"
	,"NtGdiStartPage"
	,"NtGdiStretchBlt"
	,"NtGdiStretchDIBitsInterna"
	,"NtGdiStrokeAndFillPath"
	,"NtGdiStrokePath"
	,"NtGdiSwapBuffers"
	,"NtGdiTransformPoints"
	,"NtGdiTransparentBlt"
	,"DxgStubEnableDirectDrawRedirection"
	,"NtGdiUnmapMemFont"
	,"NtGdiUnrealizeObject"
	,"NtGdiUpdateColors"
	,"NtGdiWidenPath"
	,"NtUserActivateKeyboardLayout"
	,"NtUserAddClipboardFormatListener"
	,"NtUserAlterWindowStyle"
	,"NtUserAssociateInputContext"
	,"NtUserAttachThreadInput"
	,"NtUserBeginPaint"
	,"NtUserBitBltSysBmp"
	,"NtUserBlockInput"
	,"NtUserBuildHimcList"
	,"NtUserBuildHwndList"
	,"NtUserBuildNameList"
	,"NtUserBuildPropList"
	,"NtUserCallHwnd"
	,"NtUserCallHwndLock"
	,"NtUserCallHwndOpt"
	,"NtUserCallHwndParam"
	,"NtUserCallHwndParamLock"
	,"NtUserCallMsgFilter"
	,"NtUserCallNextHookEx"
	,"NtUserCallNoParam"
	,"NtUserCallOneParam"
	,"NtUserCallTwoParam"
	,"NtUserChangeClipboardChain"
	,"NtUserChangeDisplaySettings"
	,"NtUserGetDisplayConfigBufferSizes"
	,"NtUserSetDisplayConfig"
	,"NtUserQueryDisplayConfig"
	,"NtUserDisplayConfigGetDeviceInfo"
	,"NtUserDisplayConfigSetDeviceInfo"
	,"NtUserCheckAccessForIntegrityLeve"
	,"NtUserCheckDesktopByThreadId"
	,"NtUserCheckWindowThreadDesktop"
	,"NtUserCheckMenuItem"
	,"NtUserChildWindowFromPointEx"
	,"NtUserClipCursor"
	,"NtUserCloseClipboard"
	,"NtUserCloseDesktop"
	,"NtUserCloseWindowStation"
	,"NtUserConsoleContro"
	,"NtUserConvertMemHandle"
	,"NtUserCopyAcceleratorTable"
	,"NtUserCountClipboardFormats"
	,"NtUserCreateAcceleratorTable"
	,"NtUserCreateCaret"
	,"NtUserCreateDesktopEx"
	,"NtUserCreateInputContext"
	,"NtUserCreateLocalMemHandle"
	,"NtUserCreateWindowEx"
	,"NtUserCreateWindowStation"
	,"NtUserDdeInitialize"
	,"NtUserDeferWindowPos"
	,"NtUserDefSetText"
	,"NtUserDeleteMenu"
	,"NtUserDestroyAcceleratorTable"
	,"NtUserDestroyCursor"
	,"NtUserDestroyInputContext"
	,"NtUserDestroyMenu"
	,"NtUserDestroyWindow"
	,"NtUserDisableThreadIme"
	,"NtUserDispatchMessage"
	,"NtUserDoSoundConnect"
	,"NtUserDoSoundDisconnect"
	,"NtUserDragDetect"
	,"NtUserDragObject"
	,"NtUserDrawAnimatedRects"
	,"NtUserDrawCaption"
	,"NtUserDrawCaptionTemp"
	,"NtUserDrawIconEx"
	,"NtUserDrawMenuBarTemp"
	,"NtUserEmptyClipboard"
	,"NtUserEnableMenuItem"
	,"NtUserEnableScrollBar"
	,"NtUserEndDeferWindowPosEx"
	,"NtUserEndMenu"
	,"NtUserEndPaint"
	,"NtUserEnumDisplayDevices"
	,"NtUserEnumDisplayMonitors"
	,"NtUserEnumDisplaySettings"
	,"NtUserEventA"
	,"NtUserExcludeUpdateRgn"
	,"NtUserFillWindow"
	,"NtUserFindExistingCursorIcon"
	,"NtUserFindWindowEx"
	,"NtUserFlashWindowEx"
	,"NtUserFrostCrashedWindow"
	,"NtUserGetAltTabInfo"
	,"NtUserGetAncestor"
	,"NtUserGetAppImeLeve"
	,"NtUserGetAsyncKeyState"
	,"NtUserGetAtomName"
	,"NtUserGetCaretBlinkTime"
	,"NtUserGetCaretPos"
	,"NtUserGetClassInfoEx"
	,"NtUserGetClassName"
	,"NtUserGetClipboardData"
	,"NtUserGetClipboardFormatName"
	,"NtUserGetClipboardOwner"
	,"NtUserGetClipboardSequenceNumber"
	,"NtUserGetClipboardViewer"
	,"NtUserGetClipCursor"
	,"NtUserGetComboBoxInfo"
	,"NtUserGetControlBrush"
	,"NtUserGetControlColor"
	,"NtUserGetCPD"
	,"NtUserGetCursorFrameInfo"
	,"NtUserGetCursorInfo"
	,"NtUserGetDC"
	,"NtUserGetDCEx"
	,"NtUserGetDoubleClickTime"
	,"NtUserGetForegroundWindow"
	,"NtUserGetGuiResources"
	,"NtUserGetGUIThreadInfo"
	,"NtUserGetIconInfo"
	,"NtUserGetIconSize"
	,"NtUserGetImeHotKey"
	,"NtUserGetImeInfoEx"
	,"NtUserGetInputLocaleInfo"
	,"NtUserGetInternalWindowPos"
	,"NtUserGetKeyboardLayoutList"
	,"NtUserGetKeyboardLayoutName"
	,"NtUserGetKeyboardState"
	,"NtUserGetKeyNameText"
	,"NtUserGetKeyState"
	,"NtUserGetListBoxInfo"
	,"NtUserGetMenuBarInfo"
	,"NtUserGetMenuIndex"
	,"NtUserGetMenuItemRect"
	,"NtUserGetMessage"
	,"NtUserGetMouseMovePointsEx"
	,"NtUserGetObjectInformation"
	,"NtUserGetOpenClipboardWindow"
	,"NtUserGetPriorityClipboardFormat"
	,"NtUserGetProcessWindowStation"
	,"NtUserGetRawInputBuffer"
	,"NtUserGetRawInputData"
	,"NtUserGetRawInputDeviceInfo"
	,"NtUserGetRawInputDeviceList"
	,"NtUserGetRegisteredRawInputDevices"
	,"NtUserGetScrollBarInfo"
	,"NtUserGetSystemMenu"
	,"NtUserGetThreadDesktop"
	,"NtUserGetThreadState"
	,"NtUserGetTitleBarInfo"
	,"NtUserGetTopLevelWindow"
	,"NtUserGetUpdatedClipboardFormats"
	,"NtUserGetUpdateRect"
	,"NtUserGetUpdateRgn"
	,"NtUserGetWindowCompositionInfo"
	,"NtUserGetWindowCompositionAttribute"
	,"NtUserGetWindowDC"
	,"NtUserGetWindowDisplayAffinity"
	,"NtUserGetWindowPlacement"
	,"NtUserGetWOWClass"
	,"NtUserGhostWindowFromHungWindow"
	,"NtUserHardErrorContro"
	,"NtUserHideCaret"
	,"NtUserHiliteMenuItem"
	,"NtUserHungWindowFromGhostWindow"
	,"NtUserImpersonateDdeClientWindow"
	,"NtUserInitialize"
	,"NtUserInitializeClientPfnArrays"
	,"NtUserInitTask"
	,"NtUserInternalGetWindowText"
	,"NtUserInternalGetWindowIcon"
	,"NtUserInvalidateRect"
	,"NtUserInvalidateRgn"
	,"NtUserIsClipboardFormatAvailable"
	,"NtUserIsTopLevelWindow"
	,"NtUserKillTimer"
	,"NtUserLoadKeyboardLayoutEx"
	,"NtUserLockWindowStation"
	,"NtUserLockWindowUpdate"
	,"NtUserLockWorkStation"
	,"NtUserLogicalToPhysicalPoint"
	,"NtUserMapVirtualKeyEx"
	,"NtUserMenuItemFromPoint"
	,"NtUserMessageCall"
	,"NtUserMinMaximize"
	,"NtUserMNDragLeave"
	,"NtUserMNDragOver"
	,"NtUserModifyUserStartupInfoFlags"
	,"NtUserMoveWindow"
	,"NtUserNotifyIMEStatus"
	,"NtUserNotifyProcessCreate"
	,"NtUserNotifyWinEvent"
	,"NtUserOpenClipboard"
	,"NtUserOpenDesktop"
	,"NtUserOpenInputDesktop"
	,"NtUserOpenThreadDesktop"
	,"NtUserOpenWindowStation"
	,"NtUserPaintDesktop"
	,"NtUserPaintMonitor"
	,"NtUserPeekMessage"
	,"NtUserPhysicalToLogicalPoint"
	,"NtUserPostMessage"
	,"NtUserPostThreadMessage"
	,"NtUserPrintWindow"
	,"NtUserProcessConnect"
	,"NtUserQueryInformationThread"
	,"NtUserQueryInputContext"
	,"NtUserQuerySendMessage"
	,"NtUserQueryWindow"
	,"NtUserRealChildWindowFromPoint"
	,"NtUserRealInternalGetMessage"
	,"NtUserRealWaitMessageEx"
	,"NtUserRedrawWindow"
	,"NtUserRegisterClassExWOW"
	,"NtUserRegisterErrorReportingDialog"
	,"NtUserRegisterUserApiHook"
	,"NtUserRegisterHotKey"
	,"NtUserRegisterRawInputDevices"
	,"NtUserRegisterServicesProcess"
	,"NtUserRegisterTasklist"
	,"NtUserRegisterWindowMessage"
	,"NtUserRemoveClipboardFormatListener"
	,"NtUserRemoveMenu"
	,"NtUserRemoveProp"
	,"NtUserResolveDesktopForWOW"
	,"NtUserSBGetParms"
	,"NtUserScrollDC"
	,"NtUserScrollWindowEx"
	,"NtUserSelectPalette"
	,"NtUserSendInput"
	,"NtUserSetActiveWindow"
	,"NtUserSetAppImeLeve"
	,"NtUserSetCapture"
	,"NtUserSetChildWindowNoActivate"
	,"NtUserSetClassLong"
	,"NtUserSetClassWord"
	,"NtUserSetClipboardData"
	,"NtUserSetClipboardViewer"
	,"NtUserSetCursor"
	,"NtUserSetCursorContents"
	,"NtUserSetCursorIconData"
	,"NtUserSetFocus"
	,"NtUserSetImeHotKey"
	,"NtUserSetImeInfoEx"
	,"NtUserSetImeOwnerWindow"
	,"NtUserSetInformationThread"
	,"NtUserSetInternalWindowPos"
	,"NtUserSetKeyboardState"
	,"NtUserSetMenu"
	,"NtUserSetMenuContextHelpId"
	,"NtUserSetMenuDefaultItem"
	,"NtUserSetMenuFlagRto"
	,"NtUserSetObjectInformation"
	,"NtUserSetParent"
	,"NtUserSetProcessWindowStation"
	,"NtUserGetProp"
	,"NtUserSetProp"
	,"NtUserSetScrollInfo"
	,"NtUserSetShellWindowEx"
	,"NtUserSetSysColors"
	,"NtUserSetSystemCursor"
	,"NtUserSetSystemMenu"
	,"NtUserSetSystemTimer"
	,"NtUserSetThreadDesktop"
	,"NtUserSetThreadLayoutHandles"
	,"NtUserSetThreadState"
	,"NtUserSetTimer"
	,"NtUserSetProcessDPIAware"
	,"NtUserSetWindowCompositionAttribute"
	,"NtUserSetWindowDisplayAffinity"
	,"NtUserSetWindowFNID"
	,"NtUserSetWindowLong"
	,"NtUserSetWindowPlacement"
	,"NtUserSetWindowPos"
	,"NtUserSetWindowRgn"
	,"NtUserGetWindowRgnEx"
	,"NtUserSetWindowRgnEx"
	,"NtUserSetWindowsHookAW"
	,"NtUserSetWindowsHookEx"
	,"NtUserSetWindowStationUser"
	,"NtUserSetWindowWord"
	,"NtUserSetWinEventHook"
	,"NtUserShowCaret"
	,"NtUserShowScrollBar"
	,"NtUserShowWindow"
	,"NtUserShowWindowAsync"
	,"NtUserSoundSentry"
	,"NtUserSwitchDesktop"
	,"NtUserSystemParametersInfo"
	,"NtUserTestForInteractiveUser"
	,"NtUserThunkedMenuInfo"
	,"NtUserThunkedMenuItemInfo"
	,"NtUserToUnicodeEx"
	,"NtUserTrackMouseEvent"
	,"NtUserTrackPopupMenuEx"
	,"NtUserCalculatePopupWindowPosition"
	,"NtUserCalcMenuBar"
	,"NtUserPaintMenuBar"
	,"NtUserTranslateAccelerator"
	,"NtUserTranslateMessage"
	,"NtUserUnhookWindowsHookEx"
	,"NtUserUnhookWinEvent"
	,"NtUserUnloadKeyboardLayout"
	,"NtUserUnlockWindowStation"
	,"NtUserUnregisterClass"
	,"NtUserUnregisterUserApiHook"
	,"NtUserUnregisterHotKey"
	,"NtUserUpdateInputContext"
	,"NtUserUpdateInstance"
	,"NtUserUpdateLayeredWindow"
	,"NtUserGetLayeredWindowAttributes"
	,"NtUserSetLayeredWindowAttributes"
	,"NtUserUpdatePerUserSystemParameters"
	,"NtUserUserHandleGrantAccess"
	,"NtUserValidateHandleSecure"
	,"NtUserValidateRect"
	,"NtUserValidateTimerCallback"
	,"NtUserVkKeyScanEx"
	,"NtUserWaitForInputIdle"
	,"NtUserWaitForMsgAndEvent"
	,"NtUserWaitMessage"
	,"NtUserWindowFromPhysicalPoint"
	,"NtUserWindowFromPoint"
	,"NtUserYieldTask"
	,"NtUserRemoteConnect"
	,"NtUserRemoteRedrawRectangle"
	,"NtUserRemoteRedrawScreen"
	,"NtUserRemoteStopScreenUpdates"
	,"NtUserCtxDisplayIOCt"
	,"NtUserRegisterSessionPort"
	,"NtUserUnregisterSessionPort"
	,"NtUserUpdateWindowTransform"
	,"NtUserDwmStartRedirection"
	,"NtUserDwmStopRedirection"
	,"NtUserGetWindowMinimizeRect"
	,"NtUserSfmDxBindSwapChain"
	,"NtUserSfmDxOpenSwapChain"
	,"NtUserSfmDxReleaseSwapChain"
	,"NtUserSfmDxSetSwapChainBindingStatus"
	,"NtUserSfmDxQuerySwapChainBindingStatus"
	,"NtUserSfmDxReportPendingBindingsToDwm"
	,"NtUserSfmDxGetSwapChainStats"
	,"NtUserSfmDxSetSwapChainStats"
	,"NtUserSfmGetLogicalSurfaceBinding"
	,"NtUserSfmDestroyLogicalSurfaceBinding"
	,"NtUserModifyWindowTouchCapability"
	,"NtUserIsTouchWindow"
	,"NtUserSendTouchInput"
	,"NtUserEndTouchOperation"
	,"NtUserGetTouchInputInfo"
	,"NtUserChangeWindowMessageFilterEx"
	,"NtUserInjectGesture"
	,"NtUserGetGestureInfo"
	,"NtUserGetGestureExtArgs"
	,"NtUserManageGestureHandlerWindow"
	,"NtUserSetGestureConfig"
	,"NtUserGetGestureConfig"
	,"NtGdiEngAssociateSurface"
	,"NtGdiEngCreateBitmap"
	,"NtGdiEngCreateDeviceSurface"
	,"NtGdiEngCreateDeviceBitmap"
	,"NtGdiEngCreatePalette"
	,"NtGdiEngComputeGlyphSet"
	,"NtGdiEngCopyBits"
	,"NtGdiEngDeletePalette"
	,"NtGdiEngDeleteSurface"
	,"NtGdiEngEraseSurface"
	,"NtGdiEngUnlockSurface"
	,"NtGdiEngLockSurface"
	,"NtGdiEngBitBlt"
	,"NtGdiEngStretchBlt"
	,"NtGdiEngPlgBlt"
	,"NtGdiEngMarkBandingSurface"
	,"NtGdiEngStrokePath"
	,"NtGdiEngFillPath"
	,"NtGdiEngStrokeAndFillPath"
	,"NtGdiEngPaint"
	,"NtGdiEngLineTo"
	,"NtGdiEngAlphaBlend"
	,"NtGdiEngGradientFil"
	,"NtGdiEngTransparentBlt"
	,"NtGdiEngTextOut"
	,"NtGdiEngStretchBltROP"
	,"NtGdiXLATEOBJ_cGetPalette"
	,"NtGdiXLATEOBJ_iXlate"
	,"NtGdiXLATEOBJ_hGetColorTransform"
	,"NtGdiCLIPOBJ_bEnum"
	,"NtGdiCLIPOBJ_cEnumStart"
	,"NtGdiCLIPOBJ_ppoGetPath"
	,"NtGdiEngDeletePath"
	,"NtGdiEngCreateClip"
	,"NtGdiEngDeleteClip"
	,"NtGdiBRUSHOBJ_ulGetBrushColor"
	,"NtGdiBRUSHOBJ_pvAllocRbrush"
	,"NtGdiBRUSHOBJ_pvGetRbrush"
	,"NtGdiBRUSHOBJ_hGetColorTransform"
	,"NtGdiXFORMOBJ_bApplyXform"
	,"NtGdiXFORMOBJ_iGetXform"
	,"NtGdiFONTOBJ_vGetInfo"
	,"NtGdiFONTOBJ_pxoGetXform"
	,"NtGdiFONTOBJ_cGetGlyphs"
	,"NtGdiFONTOBJ_pifi"
	,"NtGdiFONTOBJ_pfdg"
	,"NtGdiFONTOBJ_pQueryGlyphAttrs"
	,"NtGdiFONTOBJ_pvTrueTypeFontFile"
	,"NtGdiFONTOBJ_cGetAllGlyphHandles"
	,"NtGdiSTROBJ_bEnum"
	,"NtGdiSTROBJ_bEnumPositionsOnly"
	,"NtGdiSTROBJ_bGetAdvanceWidths"
	,"NtGdiSTROBJ_vEnumStart"
	,"NtGdiSTROBJ_dwGetCodePage"
	,"NtGdiPATHOBJ_vGetBounds"
	,"NtGdiPATHOBJ_bEnum"
	,"NtGdiPATHOBJ_vEnumStart"
	,"NtGdiPATHOBJ_vEnumStartClipLines"
	,"NtGdiPATHOBJ_bEnumClipLines"
	,"NtGdiGetDhpdev"
	,"NtGdiEngCheckAbort"
	,"NtGdiHT_GetBPPFormatPalette"
	,"NtGdiHT_GetBPPMaskPalette"
	,"NtGdiUpdateTransform"
	,"NtGdiSetPUMPDOBJ"
	,"NtGdiBRUSHOBJ_DeleteRbrush"
	,"NtGdiUnmapMemFont"
	,"NtGdiDrawStream"
	,"NtGdiSfmGetNotificationTokens"
	,"NtGdiHLSurfGetInformation"
	,"NtGdiHLSurfSetInformation"
	,"NtGdiDdDDICreateAllocation"
	,"NtGdiDdDDIQueryResourceInfo"
	,"NtGdiDdDDIOpenResource"
	,"NtGdiDdDDIDestroyAllocation"
	,"NtGdiDdDDISetAllocationPriority"
	,"NtGdiDdDDIQueryAllocationResidency"
	,"NtGdiDdDDICreateDevice"
	,"NtGdiDdDDIDestroyDevice"
	,"NtGdiDdDDICreateContext"
	,"NtGdiDdDDIDestroyContext"
	,"NtGdiDdDDICreateSynchronizationObject"
	,"NtGdiDdDDIOpenSynchronizationObject"
	,"NtGdiDdDDIDestroySynchronizationObject"
	,"NtGdiDdDDIWaitForSynchronizationObject"
	,"NtGdiDdDDISignalSynchronizationObject"
	,"NtGdiDdDDIGetRuntimeData"
	,"NtGdiDdDDIQueryAdapterInfo"
	,"NtGdiDdDDILock"
	,"NtGdiDdDDIUnlock"
	,"NtGdiDdDDIGetDisplayModeList"
	,"NtGdiDdDDISetDisplayMode"
	,"NtGdiDdDDIGetMultisampleMethodList"
	,"NtGdiDdDDIPresent"
	,"NtGdiDdDDIRender"
	,"NtGdiDdDDIOpenAdapterFromDeviceName"
	,"NtGdiDdDDIOpenAdapterFromHdc"
	,"NtGdiDdDDICloseAdapter"
	,"NtGdiDdDDIGetSharedPrimaryHandle"
	,"NtGdiDdDDIEscape"
	,"NtGdiDdDDIQueryStatistics"
	,"NtGdiDdDDISetVidPnSourceOwner"
	,"NtGdiDdDDIGetPresentHistory"
	,"NtGdiDdDDIGetPresentQueueEvent"
	,"NtGdiDdDDICreateOverlay"
	,"NtGdiDdDDIUpdateOverlay"
	,"NtGdiDdDDIFlipOverlay"
	,"NtGdiDdDDIDestroyOverlay"
	,"NtGdiDdDDIWaitForVerticalBlankEvent"
	,"NtGdiDdDDISetGammaRamp"
	,"NtGdiDdDDIGetDeviceState"
	,"NtGdiDdDDICreateDCFromMemory"
	,"NtGdiDdDDIDestroyDCFromMemory"
	,"NtGdiDdDDISetContextSchedulingPriority"
	,"NtGdiDdDDIGetContextSchedulingPriority"
	,"NtGdiDdDDISetProcessSchedulingPriorityClass"
	,"NtGdiDdDDIGetProcessSchedulingPriorityClass"
	,"NtGdiDdDDIReleaseProcessVidPnSourceOwners"
	,"NtGdiDdDDIGetScanLine"
	,"NtGdiDdDDISetQueuedLimit"
	,"NtGdiDdDDIPollDisplayChildren"
	,"NtGdiDdDDIInvalidateActiveVidPn"
	,"NtGdiDdDDICheckOcclusion"
	,"NtGdiDdDDIWaitForIdle"
	,"NtGdiDdDDICheckMonitorPowerState"
	,"NtGdiDdDDICheckExclusiveOwnership"
	,"NtGdiDdDDISetDisplayPrivateDriverFormat"
	,"NtGdiDdDDISharedPrimaryLockNotification"
	,"NtGdiDdDDISharedPrimaryUnLockNotification"
	,"NtGdiDdDDICreateKeyedMutex"
	,"NtGdiDdDDIOpenKeyedMutex"
	,"NtGdiDdDDIDestroyKeyedMutex"
	,"NtGdiDdDDIAcquireKeyedMutex"
	,"NtGdiDdDDIReleaseKeyedMutex"
	,"NtGdiDdDDIConfigureSharedResource"
	,"NtGdiDdDDIGetOverlayState"
	,"NtGdiDdDDICheckVidPnExclusiveOwnership"
	,"NtGdiDdDDICheckSharedResourceAccess"
	,"DxgStubEnableDirectDrawRedirection"
	,"DxgStubDeleteDirectDrawObject"
	,"NtGdiGetNumberOfPhysicalMonitors"
	,"NtGdiGetPhysicalMonitors"
	,"NtGdiGetPhysicalMonitorDescription"
	,"DestroyPhysicalMonitor"
	,"NtGdiDDCCIGetVCPFeature"
	,"NtGdiDDCCISetVCPFeature"
	,"NtGdiDDCCISaveCurrentSettings"
	,"NtGdiDDCCIGetCapabilitiesStringLength"
	,"NtGdiDDCCIGetCapabilitiesString"
	,"NtGdiDDCCIGetTimingReport"
	,"NtGdiDdCreateFullscreenSprite"
	,"NtGdiDdNotifyFullscreenSpriteUpdate"
	,"NtGdiDdDestroyFullscreenSprite"
	,"NtGdiDdQueryVisRgnUniqueness"
	,"NtUserSetMirrorRendering"
	,"NtUserShowSystemCursor"
	,"NtUserMagContro"
	,"NtUserMagSetContextInformation"
	,"NtUserMagGetContextInformation"
	,"NtUserHwndQueryRedirectionInfo"
	,"NtUserHwndSetRedirectionInfo"
};