######################################################################
# Automatically generated by qmake (2.01a) on 3. jan 13:45:49 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
CONFIG += console 
