//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by POKER.RC
//
#define IDR_POKER_ICON                  2
#define IDR_POKER_ACCEL                 3
#define IDD_ABOUTBOX                    100
#define MAIN_DLG_WINDOW                 101
#define IDR_POKER_MENU                  102
#define IDC_CARD1                       1003
#define IDC_CARD2                       1004
#define IDC_CARD3                       1005
#define IDC_CARD4                       1006
#define IDC_CARD5                       1007
#define IDC_CARD6                       1008
#define IDC_CARD7                       1009
#define IDC_HAND0                       1010
#define IDC_HAND1                       1011
#define IDC_HAND2                       1012
#define IDC_HAND3                       1013
#define IDC_HAND4                       1014
#define IDC_HAND5                       1015
#define IDC_HAND6                       1016
#define IDC_HAND7                       1017
#define IDC_HAND8                       1018
#define IDC_JACKPOT                     1019
#define IDC_TOTALWIN                    1020
#define IDC_NUMWIN                      1021
#define ID_ABOUT                        32771
#define ID_DIALOGS_FILEOPEN             32773
#define ID_DIALOGS_FILESAVE             32774
#define ID_DIALOGS_FONT                 32775
#define ID_DIALOGS_COLOR                32776
#define ID_DIALOGS_PRINT                32777
#define ID_DIALOGS_ABOUT                32778

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1032
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
