######################################################################
# Automatically generated by qmake (2.00a) to 10. aug 14:07:53 2006
######################################################################

TEMPLATE = app
TARGET +=
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += cpp-with-qstring.cpp

CONFIG += console