//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DOMSamp.rc
//
#define IDS_PROJNAME                    100
#define IDB_DOMCTRL                     101
#define IDR_DOMCTRL                     102
#define IDD_DOMCTRL                     103
#define IDC_EDTTITLE                    201
#define IDC_EDTCOLOR                    202
#define IDC_EDTURL                      203
#define IDC_BTNTITLE                    204
#define IDC_BTNCOLOR                    205
#define IDC_BTNNEWWND                   206

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
    #define _APS_NEXT_RESOURCE_VALUE        201
    #define _APS_NEXT_COMMAND_VALUE         32768
    #define _APS_NEXT_CONTROL_VALUE         205
    #define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
