######################################################################
# Automatically generated by qmake (2.01a) må 1. jan 16:55:20 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
CONFIG += console 
