######################################################################
# Automatically generated by qmake (2.01a) on 22. nov 10:36:59 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += linkdialog.h linkfilter.h
SOURCES += linkdialog.cpp linkfilter.cpp main.cpp
