

#define IDM_FILE      111
#define IDM_DIR       112
#define IDM_PRINT     113
#define IDM_EXIT      115
#define IDM_TIME      116
#define IDM_OPEN      121
#define IDM_SAVELIST  122
#define IDM_EDITLEFT  123
#define IDM_EDITRIGHT 124
#define IDM_EDITCOMP  125
#define IDM_SETEDIT   126
#define IDM_COPYFILES 127

#define IDM_ABOUT     131

#define IDD_ICON      132
#define IDD_VERSION   133
#define IDD_LABEL     136
#define IDD_DIR1      137
#define IDD_DIR2      138
#define IDD_LAB1      139
#define IDD_LAB2      140
#define IDD_LAB3      141
#define IDD_RECURSIVE 143

#define IDM_CLOSE     161

#define IDM_OUTLINE   180
#define IDM_EXPAND    181
#define IDM_FCHANGE   182
#define IDM_LNRS      185
#define IDM_RNRS      186
#define IDM_NONRS     187
#define IDM_LONLY     188
#define IDM_RONLY     189
#define IDM_BOTHFILES 190
#define IDM_UPDATE    194
#define IDM_FPCHANGE  195
#define IDM_IGNBLANKS 196
#define IDM_PICTURE   197
#define IDM_LAZY      198
#define IDM_INCSAME   201
#define IDM_INCLEFT   202
#define IDM_INCRIGHT  203
#define IDM_INCDIFFER 204

#define IDC_RCDISP1   501
#define IDC_BAR       510
#define IDC_STATUS    550
#define IDM_ABORT     551
#define IDL_STATLAB   552
#define IDL_NAMES     553

#define IDD_FILE                    601
#define IDD_IDENTICAL               602
#define IDD_DIFFER                  603
#define IDD_LEFT                    604
#define IDD_RIGHT                   605

#define IDD_FROMGROUP               610
#define IDD_FROMLEFT                611
#define IDD_FROMRIGHT               612

#define IDS_LINE_NOT_VISIBLE        650
#define IDS_ONLY_IN                 651
#define IDS_DIFFERENT_SIZES         652
#define IDS_IDENTICAL               653 
#define IDS_FILES_DIFFER            654 
#define IDS_SAME_SIZE               655 
#define IDS_CANT_OPEN_TMP_FILE      656 
#define IDS_BAD_ARGUMENT            657 
#define IDS_SELECT_FIRST_FILE       658 
#define IDS_SELECT_SECOND_FILE      659 
#define IDS_COULDNT_FIND            660 
#define IDS_CANT_OPEN               661 
#define IDS_IDENTICAL_COMMA         662 
#define IDS_LEFT_ONLY_COMMA         663 
#define IDS_RIGHT_ONLY_COMMA        664 
#define IDS_DIFFERING               665 
#define IDS_FILES_LISTED            666 
#define IDS_ENTER_DIR_NAME          667 
#define IDS_FAILED_TO_COPY          668 
#define IDS_COPYING                 669 
#define IDS_COPY_ABORTED            670 
#define IDS_COPY_FAILED             671 
#define IDS_COPY_COMPLETE           672 
#define IDS_FILES_ONLY              673 
#define IDS_EXIT                    674 
#define IDS_USAGE_STR               675
#define IDS_WINDIFF_USAGE           676 
#define IDS_PAGE                    677 
#define IDS_NO_MORE_CHANGES         678 
#define IDS_NO_PREV_CHANGES         679 
#define IDS_OUTLINE                 680 
#define IDS_EXPAND                  681 
#define IDS_FILE_DOESNT_EXIST       682 
#define IDS_FAILED_TO_LAUNCH_EDT    683 
#define IDS_COMPARING               684 
#define IDS_SCANNING                685 
#define IDS_ABORT                   686 
#define IDS_PLEASE_WAIT             687 
#define IDS_ABORT_PENDING           688 
#define IDS_SECONDS                 690 
#define IDS_CREATE_DIFF_LIST        691 
#define IDS_ENTER_EDT_CMD_LINE      692 
#define IDS_HEADER_LINE_STR         693
#define IDS_SAME_SIZE_ETC           694
#define IDS_COULDNT_BE_OPENED       695
#define IDS_FILEOPEN                696
