######################################################################
# Automatically generated by qmake (2.01a) sö 8. apr 18:27:48 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
