######################################################################
# Automatically generated by qmake (2.01a) to 19. okt 09:18:10 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += singleitemview.h
SOURCES += main.cpp singleitemview.cpp
