######################################################################
# Automatically generated by qmake (2.01a) on 22. nov 09:24:52 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += whatsthisdialog.h
SOURCES += main.cpp whatsthisdialog.cpp
RESOURCES += images.qrc
