######################################################################
# Automatically generated by qmake (2.00a) må 21. aug 09:53:24 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qlist.cpp
CONFIG += console 
