// ****************************************************************************
//
// Module:  ipc.h
// Author:  Dick Lam
//
// Purpose: C++ class header file for ipc classes
//
// Notes:  Include this file to include all of the interface classes for ipc.
//
// ****************************************************************************

#ifndef MODULE_ipch
#define MODULE_ipch

#include "ipcos.h"
#include "ipcmutex.h"
#include "ipcevent.h"
#include "ipcshmem.h"
#include "ipcqueue.h"
#include "ipcsock.h"

#endif

// ****************************************************************************

// end of ipc.h
