######################################################################
# Automatically generated by qmake (2.01a) to 19. okt 15:49:22 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += bardelegate.h
SOURCES += bardelegate.cpp main.cpp
