######################################################################
# Automatically generated by qmake (2.01a) to 16. nov 19:41:56 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
CONFIG += console 
CONFIG += console 
