EXE = algorithm_example
OBJ = algorithm_example.o
CC = g++

.PHONY : all clean

all : algorithm_example
	./algorithm_example

algorithm_example : algorithm_example.o

algorithm_example.o :

clean :
	rm -f $(EXE) $(OBJ)
