/*

  ndis5pkt.h

  Author: Chunhua Liu
  Last Updated: 2004-04-24

  This framework is generated by QuickSYS 0.2.4

*/

#ifndef _NDIS5PKT_H
#define _NDIS5PKT_H 1

#include <ntddndis.h>
#ifdef _NTDDK_
#include <devioctl.h>
#else
#include <WinIoCtl.h>
#endif

//
// Define the various device type values.  Note that values used by Microsoft
// Corporation are in the range 0-0x7FFF(32767), and 0x8000(32768)-0xFFFF(65535)
// are reserved for use by customers.
//

#define FILE_DEVICE_NDIS5PKT	0x8000

//
// Macro definition for defining IOCTL and FSCTL function control codes. Note
// that function codes 0-0x7FF(2047) are reserved for Microsoft Corporation,
// and 0x800(2048)-0xFFF(4095) are reserved for customers.
//

#define NDIS5PKT_IOCTL_BASE	0x800

//
// The device driver IOCTLs
//

#define CTL_CODE_NDIS5PKT(i) CTL_CODE(FILE_DEVICE_NDIS5PKT, NDIS5PKT_IOCTL_BASE+i, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_NDIS5PKT_BIND_ADAPTER		CTL_CODE_NDIS5PKT(0)
#define IOCTL_NDIS5PKT_UNBIND_ADAPTER	CTL_CODE_NDIS5PKT(1)
#define IOCTL_NDIS5PKT_QUERY_STATISTICS	CTL_CODE_NDIS5PKT(2)
#define IOCTL_NDIS5PKT_OPEN_DEVICE		CTL_CODE_NDIS5PKT(3)
#define IOCTL_NDIS5PKT_QUERY_OID_VALUE  CTL_CODE_NDIS5PKT(4)
#define IOCTL_NDIS5PKT_SET_OID_VALUE	CTL_CODE_NDIS5PKT(5)
#define IOCTL_NDIS5PKT_BIND_WAIT		CTL_CODE_NDIS5PKT(6)

#define IOCTL_NDIS5PKT_READ	CTL_CODE(FILE_DEVICE_NDIS5PKT, NDIS5PKT_IOCTL_BASE+20, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

typedef struct _STATISTICS_DATA
{
	LONGLONG		ReceivedPackets;
	LONGLONG		DroppedPackets;
} STATISTICS_DATA, *PSTATISTICS_DATA;

//
//  Structure to go with IOCTL_NDIS5PKT_SET_OID_VALUE
//  and IOCTL_NDIS5PKT_QUERY_OID_VALUE.
//  The Data part is of variable length, determined
//  by the input buffer length passed to DeviceIoControl.
//
typedef struct _PACKET_OID_DATA
{
    NDIS_OID        Oid;
    UCHAR           Data[sizeof(ULONG)];
} PACKET_OID_DATA, *PPACKET_OID_DATA;

#include <PshPack1.h>
#pragma warning(disable:4200)
typedef struct _PACKET_GROUP
{
	LONG			Length;
	UCHAR			Data[0];
} PACKET_GROUP, *PPACKET_GROUP;
#pragma warning(default:4200)
#include <PopPack.h>

//
// Name that Win32 front end will use to open the ndis5pkt device
//

#define NDIS5PKT_DEVICE_NAME_WIN32	"\\\\.\\ndis5pkt"

#endif
