#if !defined(AFX_MFCACTIVEXFORMCLASSWIZARD_H__2CA52F25_F9A8_11D1_96ED_F05F03C10000__INCLUDED_)
#define AFX_MFCACTIVEXFORMCLASSWIZARD_H__2CA52F25_F9A8_11D1_96ED_F05F03C10000__INCLUDED_

#ifndef __AFXWIN_H__
    #error include 'stdafx.h' before including this file for PCH
#endif

#include "resource.h"       // main symbols

// TODO: You may add any other custom AppWizard-wide declarations here.


//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MFCACTIVEXFORMCLASSWIZARD_H__2CA52F25_F9A8_11D1_96ED_F05F03C10000__INCLUDED_)
