//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MFC ActiveX Form ClassWizard.rc
//

#define IDI_MFCACTIVEXFORMCLASSWIZARD               1

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
    #define _APS_3D_CONTROLS                1
    #define _APS_NEXT_RESOURCE_VALUE        117
    #define _APS_NEXT_COMMAND_VALUE         40001
    #define _APS_NEXT_CONTROL_VALUE         1000
    #define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
