######################################################################
# Automatically generated by qmake (2.01a) to 28. sep 16:43:38 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mdiwindow.h documentwindow.h
SOURCES += main.cpp mdiwindow.cpp documentwindow.cpp
RESOURCES += images.qrc
CONFIG+=console 
