/*
	版权：CY001 WDF USB开发板项目  2009/9/1
	
	你所拥有的此份代码拷贝，仅可用于个人学习，任何商业或与利益相关途径的使用，都不被允许。
	如果你未经特许，请不要将代码在网络上传播。项目开发者已将代码发布，并长期维护。

	作者：麦盒数码		张佩 
		  驱动开发网	马勇
		  AMD			夏浩翔

	日期：2009/9/1

	文件：IoCtl.h
	说明：IO_CTL定义
	历史：
	创建：
*/

#ifndef _IOCTL_H___
#define _IOCTL_H___

#define IOCTL_INDEX_START   0x8000

#define IOCTL_USB_CTL_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN,\
	IOCTL_INDEX_START + 3,       \
	METHOD_BUFFERED,   \
	FILE_ANY_ACCESS)

#define IOCTL_FIRMWARE_UPLOAD CTL_CODE(FILE_DEVICE_UNKNOWN,\
	IOCTL_INDEX_START + 4,       \
	METHOD_BUFFERED,   \
	FILE_ANY_ACCESS)

#define IOCTL_FIRMWARE_UPLOAD_OFFSET CTL_CODE(FILE_DEVICE_UNKNOWN,\
	IOCTL_INDEX_START + 4,\
	METHOD_IN_DIRECT,\
	FILE_ANY_ACCESS)

#define IOCTL_FIRMWARE_READ_RAM CTL_CODE(FILE_DEVICE_UNKNOWN,\
	IOCTL_INDEX_START + 5,       \
	METHOD_BUFFERED,   \
	FILE_ANY_ACCESS)

#define IOCTL_USB_VENDOR_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN,\
	IOCTL_INDEX_START + 6,       \
	METHOD_BUFFERED,   \
	FILE_ANY_ACCESS)

#define IOCTL_USB_CLASS_REQUEST   CTL_CODE(FILE_DEVICE_UNKNOWN,  \
	IOCTL_INDEX_START+9,\
	METHOD_IN_DIRECT,  \
	FILE_ANY_ACCESS)

#define IOCTL_USB_GET_CURRENT_CONFIG CTL_CODE(FILE_DEVICE_UNKNOWN,\
	IOCTL_INDEX_START + 7,       \
	METHOD_BUFFERED,   \
	FILE_ANY_ACCESS)

#define IOCTL_USB_GET_CURRENT_FRAME_NUMBER CTL_CODE(FILE_DEVICE_UNKNOWN,\
	IOCTL_INDEX_START + 8,       \
	METHOD_BUFFERED,   \
	FILE_ANY_ACCESS)

#define IOCTL_USB_ABORTPIPE   CTL_CODE(FILE_DEVICE_UNKNOWN,  \
	IOCTL_INDEX_START+10,\
	METHOD_BUFFERED,  \
	FILE_ANY_ACCESS)

#define IOCTL_USB_GET_DEVICE_DESCRIPTOR   CTL_CODE(FILE_DEVICE_UNKNOWN,  \
	IOCTL_INDEX_START+11,\
	METHOD_BUFFERED,  \
	FILE_ANY_ACCESS)

#define IOCTL_USB_GET_STRING_DESCRIPTOR   CTL_CODE(FILE_DEVICE_UNKNOWN,  \
	IOCTL_INDEX_START+12,\
	METHOD_BUFFERED,  \
	FILE_ANY_ACCESS)

#define IOCTL_USB_GET_CONFIGURATION_DESCRIPTOR   CTL_CODE(FILE_DEVICE_UNKNOWN,  \
	IOCTL_INDEX_START+13,\
	METHOD_BUFFERED,  \
	FILE_ANY_ACCESS)

#define IOCTL_USB_SET_INTERFACE   CTL_CODE(FILE_DEVICE_UNKNOWN,  \
	IOCTL_INDEX_START+14,\
	METHOD_BUFFERED,  \
	FILE_ANY_ACCESS)

// 总线端口重置
#define IOCTL_USB_PORT_RESET   CTL_CODE(FILE_DEVICE_UNKNOWN,  \
	IOCTL_INDEX_START+15,\
	METHOD_NEITHER,  \
	FILE_ANY_ACCESS)

// USB芯片重置
#define IOCTL_USB_FIRMWRAE_RESET   CTL_CODE(FILE_DEVICE_UNKNOWN,  \
	IOCTL_INDEX_START+15,\
	METHOD_BUFFERED,  \
	FILE_ANY_ACCESS)

#define IOCTL_USB_BULK_WRITE   CTL_CODE(FILE_DEVICE_UNKNOWN,  \
	IOCTL_INDEX_START+16,\
	METHOD_IN_DIRECT,  \
	FILE_ANY_ACCESS)

#define IOCTL_USB_BULK_READ   CTL_CODE(FILE_DEVICE_UNKNOWN,  \
	IOCTL_INDEX_START+17,\
	METHOD_OUT_DIRECT,  \
	FILE_ANY_ACCESS)

#define IOCTL_USB_GET_LAST_ERROR   CTL_CODE(FILE_DEVICE_UNKNOWN,  \
	IOCTL_INDEX_START+18,\
	METHOD_BUFFERED,  \
	FILE_ANY_ACCESS)

#define IOCTL_USB_GET_PIPE_INFO   CTL_CODE(FILE_DEVICE_UNKNOWN,  \
	IOCTL_INDEX_START+19,\
	METHOD_BUFFERED,  \
	FILE_ANY_ACCESS)

#define IOCTL_USB_SET_CLEAR_FEATURE   CTL_CODE(FILE_DEVICE_UNKNOWN,  \
	IOCTL_INDEX_START+20,\
	METHOD_BUFFERED,  \
	FILE_ANY_ACCESS)

#define IOCTL_USB_PIPE_RESET	CTL_CODE(FILE_DEVICE_UNKNOWN,\
	IOCTL_INDEX_START+21,\
	METHOD_BUFFERED,\
	FILE_ANY_ACCESS)

#define IOCTL_USB_PIPE_ABORT	CTL_CODE(FILE_DEVICE_UNKNOWN,\
	IOCTL_INDEX_START+22,\
	METHOD_BUFFERED,\
	FILE_ANY_ACCESS)

#define IOCTL_USB_SET_DIGITRON	CTL_CODE(FILE_DEVICE_UNKNOWN,\
	IOCTL_INDEX_START+23,\
	METHOD_BUFFERED,\
	FILE_ANY_ACCESS)

#define IOCTL_USB_GET_DIGITRON	CTL_CODE(FILE_DEVICE_UNKNOWN,\
	IOCTL_INDEX_START+123,\
	METHOD_BUFFERED,\
	FILE_ANY_ACCESS)

#define IOCTL_USB_SET_LEDs	CTL_CODE(FILE_DEVICE_UNKNOWN,\
	IOCTL_INDEX_START+24,\
	METHOD_BUFFERED,\
	FILE_ANY_ACCESS)

#define IOCTL_USB_GET_LEDs	CTL_CODE(FILE_DEVICE_UNKNOWN,\
	IOCTL_INDEX_START+124,\
	METHOD_BUFFERED,\
	FILE_ANY_ACCESS)

// 通过Interrupt端口取得鼠标按键信息
#define IOCTL_INT_READ_KEYs	CTL_CODE(FILE_DEVICE_UNKNOWN,\
	IOCTL_INDEX_START+27,\
	METHOD_BUFFERED,\
	FILE_ANY_ACCESS)

// 开始通过Interrupt端口取得鼠标按键信息
#define IOCTL_START_INT_READ	CTL_CODE(FILE_DEVICE_UNKNOWN,\
	IOCTL_INDEX_START+28,\
	METHOD_BUFFERED,\
	FILE_ANY_ACCESS)

// 结束通过Interrupt端口取得鼠标按键信息
#define IOCTL_STOP_INT_READ	CTL_CODE(FILE_DEVICE_UNKNOWN,\
	IOCTL_INDEX_START+29,\
	METHOD_BUFFERED,\
	FILE_ANY_ACCESS)

#define IOCTL_GET_DRIVER_VERSION	CTL_CODE(FILE_DEVICE_UNKNOWN,\
	IOCTL_INDEX_START+26,\
	METHOD_BUFFERED,\
	FILE_ANY_ACCESS)

#define IOCTL_USB_SYNC     CTL_CODE(FILE_DEVICE_UNKNOWN,  \
	IOCTL_INDEX_START+100,\
	METHOD_IN_DIRECT,  \
	FILE_ANY_ACCESS)

#define IOCTL_USB_SYNC_RELEASE     CTL_CODE(FILE_DEVICE_UNKNOWN,  \
	IOCTL_INDEX_START+101,\
	METHOD_BUFFERED,  \
	FILE_ANY_ACCESS)

#define IOCTL_APP_EXIT_CANCEL      CTL_CODE(FILE_DEVICE_UNKNOWN,  \
	IOCTL_INDEX_START+102,\
	METHOD_BUFFERED,  \
	FILE_ANY_ACCESS)

#endif