######################################################################
# Automatically generated by qmake (2.01a) lö 20. jan 18:14:57 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
CONFIG += console 
