//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DB.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_DBTYPE                      129
#define IDC_CREATE_TABLE                32771
#define IDC_READ_TABLE                  32772
#define IDC_WRITE_TABLE                 32773

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
    #define _APS_3D_CONTROLS                     1
    #define _APS_NEXT_RESOURCE_VALUE        130
    #define _APS_NEXT_COMMAND_VALUE         32774
    #define _APS_NEXT_CONTROL_VALUE         1000
    #define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
