//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by FtpFile.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_FTPFILE_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDC_LIST_FILE                   1000
#define IDC_EDIT_FTP                    1001
#define IDC_EDIT_NAME                   1002
#define IDC_EDIT_PWD                    1003
#define IDC_DOWNLOAD                    1004
#define IDC_STATIC_FTP                  1008
#define IDC_STATIC_NAME                 1009
#define IDC_STATIC_PWD                  1010
#define IDC_UPLOAD                      1011

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1012
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
