######################################################################
# Automatically generated by qmake (2.01a) må 19. mar 18:20:02 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h otherdialog.h preferencedialog.h
FORMS += otherdialog.ui preferencedialog.ui
SOURCES += main.cpp mainwindow.cpp otherdialog.cpp preferencedialog.cpp
