######################################################################
# Automatically generated by qmake (2.01a) ti 21. nov 21:01:45 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += tooltipdialog.h
SOURCES += main.cpp tooltipdialog.cpp
RESOURCES += images.qrc
