######################################################################
# Automatically generated by qmake (2.01a) sö 12. nov 11:38:54 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
CONFIG += console 
