######################################################################
# Automatically generated by qmake (2.01a) ti 12. sep 09:05:32 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
