######################################################################
# Automatically generated by qmake (2.01a) ti 2. jan 16:45:28 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += textandnumber.h textdialog.h textthread.h
FORMS += textdialog.ui
SOURCES += main.cpp textandnumber.cpp textdialog.cpp textthread.cpp
CONFIG += console 
