//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WndExp.RC
//
#define IDD_ABOUTBOX                    100
#define IDS_PLATFORM_WIN32_NT           110
#define IDS_PLATFORM_WIN32_NTAS         111
#define IDS_PLATFORM_WIN32_NTW          112
#define IDS_PLATFORM_WIN32_NTS          113
#define IDS_PLATFORM_WIN32s             114
#define IDS_PLATFORM_WIN32_WINDOWS      115
#define IDS_PLATFORM_UNKNOWN            116
#define IDS_ABOUT_CAPTION               117
#define IDS_ABOUT_BODY                  118
#define IDS_PROCESSOR_ARCHITECTURE_UNKNOWN 120
#define IDS_PROCESSOR_ARCHITECTURE_INTEL_386_486 121
#define IDS_PROCESSOR_ARCHITECTURE_INTEL_PENTIUM 122
#define IDS_PROCESSOR_ARCHITECTURE_ALPHA 123
#define IDS_PROCESSOR_ARCHITECTURE_MIPS 124
#define IDS_PROCESSOR_ARCHITECTURE_PPC  125
#define IDS_PROCESSOR_LEVEL_INTEL_UNKNOWN 126
#define IDS_PROCESSOR_LEVEL_ALPHA_UNKNOWN 127
#define IDR_MAINFRAME                   128
#define IDR_WINDOWTYPE                  129
#define IDS_PROCESSOR_LEVEL_MIPS_UNKNOWN 130
#define IDD_CREATEWINDOWEX              131
#define IDS_PROCESSOR_LEVEL_PPC_UNKNOWN 131
#define IDI_JMNCO                       131
#define IDS_PROCESSOR_NOREV_INTEL_386   132
#define IDD_STYLES                      132
#define IDS_PROCESSOR_NOREV_INTEL_486   133
#define IDS_PROCESSOR_NOREV_INTEL_PENTIUM 134
#define IDS_PROCESSOR_NOREV_MIPS_R4000  135
#define IDR_CONTEXTMENU                 135
#define IDS_PROCESSOR_NOREV_ALPHA_21064 136
#define IDS_HANDLE                      200
#define IDS_CONTROL_TYPE                201
#define IDS_EVENT                       202
#define IDS_WS_OVERLAPPED               203
#define IDS_WS_POPUP                    204
#define IDS_WS_CHILD                    205
#define IDS_WS_MINIMIZE                 206
#define IDS_WS_VISIBLE                  207
#define IDS_WS_DISABLED                 208
#define IDS_WS_CLIPSIBLINGS             209
#define IDS_WS_CLIPCHILDREN             210
#define IDS_WS_MAXIMIZE                 211
#define IDS_WS_CAPTION                  212
#define IDS_WS_BORDER                   213
#define IDS_WS_DLGFRAME                 214
#define IDS_WS_VSCROLL                  215
#define IDS_WS_HSCROLL                  216
#define IDS_WS_SYSMENU                  217
#define IDS_WS_THICKFRAME               218
#define IDS_WS_GROUP                    219
#define IDS_WS_TABSTOP                  220
#define IDS_WS_MINIMIZEBOX              221
#define IDS_WS_MAXIMIZEBOX              222
#define IDS_GENERIC_OVERLAPPED          223
#define IDS_GENERIC_POPUP               224
#define IDS_GENERIC_CHILD               225
#define IDS_CREATEWINDOWEX_CAPTION      226
#define IDS_CLASS                       227
#define IDS_CAPTION                     228
#define IDS_EDIT                        229
#define IDS_BUTTON                      230
#define IDS_STATIC                      231
#define IDS_LISTBOX                     232
#define IDS_SCROLLBAR                   233
#define IDS_COMBOBOX                    234
#define IDS_DIALOG                      235
#define IDS_THIS                        236
#define IDS_NONE                        237
#define IDR_MENU1                       250
#define IDC_WS_EX_ACCEPTFILES           1000
#define IDC_WS_EX_APPWINDOW             1001
#define IDC_WS_EX_CLIENTEDGE            1002
#define IDC_WS_EX_CONTEXTHELP           1003
#define IDC_WS_EX_CONTROLPARENT         1004
#define IDC_ABOUT_OSVERSION             1004
#define IDC_WS_EX_DLGMODALFRAME         1005
#define IDC_WS_EX_LEFT                  1006
#define IDC_ABOUT_PROCESSORVERSION      1006
#define IDC_WS_EX_LEFTSCROLLBAR         1007
#define IDC_WS_EX_LTRREADING            1008
#define IDC_ABOUT_FILEDESCRIPTION       1008
#define IDC_WS_EX_MDICHILD              1009
#define IDC_ABOUT_VERSION               1009
#define IDC_WS_EX_NOPARENTNOTIFY        1010
#define IDC_ABOUT_LEGALCOPYRIGHT        1010
#define IDC_WS_EX_OVERLAPPEDWINDOW      1011
#define IDC_ABOUT_LEGALTRADEMARKS       1011
#define IDC_WS_EX_PALETTEWINDOW         1012
#define IDC_ABOUT_COMMENTS              1012
#define IDC_WS_EX_RIGHT                 1013
#define IDC_WS_EX_RIGHTSCROLLBAR        1014
#define IDC_WS_EX_RTLREADING            1015
#define IDC_WS_EX_STATICEDGE            1016
#define IDC_WS_EX_TOOLWINDOW            1017
#define IDC_WS_EX_TOPMOST               1018
#define IDC_WS_EX_TRANSPARENT           1019
#define IDC_WS_EX_WINDOWEDGE            1020
#define IDC_CLASSNAME                   1021
#define IDC_WINDOWNAME                  1022
#define IDC_STYLE                       1023
#define IDC_CREATE                      1024
#define IDC_DESTROY                     1025
#define IDC_X                           1027
#define IDC_XSPIN                       1028
#define IDC_Y                           1029
#define IDC_WS_VISIBLE                  1029
#define IDC_YSPIN                       1030
#define IDC_WS_VSCROLL                  1030
#define IDC_W                           1031
#define IDC_WS_HSCROLL                  1031
#define IDC_WSPIN                       1032
#define IDC_WS_GROUP                    1032
#define IDC_H                           1033
#define IDC_WS_TABSTOP                  1033
#define IDC_HSPIN                       1034
#define IDC_WS_MAXIMIZE                 1034
#define IDC_PARENT                      1035
#define IDC_WS_MINIMIZE                 1035
#define IDC_WS_CLIPSIBLINGS             1036
#define IDC_MESSAGE                     1036
#define IDC_WS_CLIPCHILDREN             1037
#define IDC_SHOW                        1037
#define IDC_WS_BORDER                   1038
#define IDC_WINDOWS                     1038
#define IDC_WS_CAPTION                  1039
#define IDC_API3_ONLY                   1039
#define IDC_WS_DLGFRAME                 1040
#define IDC_ID                          1040
#define IDC_WS_SYSMENU                  1041
#define IDC_SPINID                      1041
#define IDC_WS_THICKFRAME               1042
#define IDC_WS_MINIMIZEBOX              1043
#define IDC_WS_MAXIMIZEBOX              1044
#define IDC_WS_OVERLAPPEDWINDOW         1045
#define IDC_WS_POPUPWINDOW              1046
#define IDC_WS_CHILDWINDOW              1047
#define IDC_FLAGS                       1048
#define IDC_WS_CHILD                    1049
#define IDC_MENU                        1049
#define IDC_WS_OVERLAPPED               1050
#define IDC_WS_POPUP                    1051
#define IDM_WNDEXP                      32771
#define IDM_DESTROY                     32773
#define IDM_PROPERTIES                  32774
#define IDM_ROUND_FILE                  32775
#define IDM_FLAT_FILE                   32776
#define IDM_HALF_ROUND                  32777
#define IDM_OCEAN_VIEW                  32778
#define IDM_MOUNTAIN_VIEW               32779
#define IDM_BAY_WINDOW                  32780
#define IDM_PICTURE_WINDOW              32781
#define IDM_TRIPLE_GLAZED               32782
#define IDM_RAT_TAIL                    32783
#define ID_HELP_NOHELP                  32784
#define IDM_NOHELP                      32785
#define IDM_EDIT_SNIP                   32786
#define IDM_PLAGIARIZE                  32787
#define IDM_GLUE                        32788
#define IDM_ABOUT_THIS                  32789
#define IDM_KILLME                      32790

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32791
#define _APS_NEXT_CONTROL_VALUE         1050
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
