######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 26 20:03:14 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
