//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Skeleton.rc
//
#define IDS_APP_TITLE                   1
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    3
#define ID_APP_ABOUT                    4
#define ID_APP_EXIT                     5
#define IDS_NO_UNICODE                  6
#define MAX_RESOURCESTRING              255
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40031
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           141
#endif
#endif
