######################################################################
# Automatically generated by qmake (2.01a) sö 8. apr 19:14:35 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
