#if !defined(AFX_CLOCK_H__58603CB4_61C2_459B_8446_CFF59B15D5EC__INCLUDED_)
#define AFX_CLOCK_H__58603CB4_61C2_459B_8446_CFF59B15D5EC__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CClock wrapper class

class CClock : public CWnd
{
protected:
	DECLARE_DYNCREATE(CClock)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x8e46decb, 0x4fc8, 0x4498, { 0xa2, 0x7, 0xe4, 0xdb, 0x4f, 0x41, 0x96, 0xa9 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	OLE_COLOR GetBackColor();
	void SetBackColor(OLE_COLOR);
	OLE_COLOR GetForeColor();
	void SetForeColor(OLE_COLOR);
	short GetInterval();
	void SetInterval(short);

// Operations
public:
	void Hello();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CLOCK_H__58603CB4_61C2_459B_8446_CFF59B15D5EC__INCLUDED_)
