######################################################################
# Automatically generated by qmake (2.01a) ti 5. dec 18:59:42 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
CONFIG += console 
