######################################################################
# Automatically generated by qmake (2.01a) må 15. jan 17:07:31 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imagecollection.h imagedialog.h
FORMS += imagedialog.ui
SOURCES += imagecollection.cpp imagedialog.cpp main.cpp
QT += sql 
CONFIG += console 
