######################################################################
# Automatically generated by qmake (2.01a) ti 12. sep 15:15:04 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += listwidgetdialog.h
SOURCES += listwidgetdialog.cpp main.cpp
CONFIG += console 
