######################################################################
# Automatically generated by qmake (2.01a) sö 22. okt 16:45:01 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += intmodel.h
SOURCES += intmodel.cpp main.cpp
