######################################################################
# Automatically generated by qmake (2.01a) lö 9. sep 14:30:16 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
