//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by AtlTickerCtrl.rc
//
#define IDS_PROJNAME                    100
#define IDB_TICKER                      101
#define IDR_TICKER                      102
#define IDS_TITLETickerPP               103
#define IDS_HELPFILETickerPP            104
#define IDS_DOCSTRINGTickerPP           105
#define IDR_TICKERPP                    106
#define IDD_TICKERPP                    107
#define ID_SPEED                        201

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
    #define _APS_NEXT_RESOURCE_VALUE        201
    #define _APS_NEXT_COMMAND_VALUE         32768
    #define _APS_NEXT_CONTROL_VALUE         202
    #define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
