######################################################################
# Automatically generated by qmake (2.01a) må 9. apr 19:02:26 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
