######################################################################
# Automatically generated by qmake (2.01a) on 31. jan 09:31:24 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ftpdialog.h
FORMS += ftpdialog.ui
SOURCES += ftpdialog.cpp main.cpp
QT += network 
CONFIG += console 
