######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 5 09:31:35 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
