######################################################################
# Automatically generated by qmake (2.01a) ti 17. apr 22:04:35 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += circlewidget.h
SOURCES += circlewidget.cpp main.cpp
