Calculator: node_unary Class Reference
node_unary Class Reference abstract
#include <node_impl.hpp>
Public Member Functions
node_unary (node operand)
node operand () const
Public Member Functions inherited from node_impl
node_impl ()
node_impl (node_impl &&)=default
node_impl & operator= (node_impl &&)=default
virtual ~node_impl ()
void print (std::ostream &stream, int indent) const
double evaluate () const
std::string to_string () const
identifier_list const & get_parameters () const
Protected Member Functions
double evaluate_operand () const
Private Member Functions
virtual void print_node (std::ostream &stream, int indent) const override=0
virtual double evaluate_node () const override=0
Private Attributes
node operand_
Detailed Description
Abstract base class for unary operators.
Definition at line 115 of file node_impl.hpp.
Constructor & Destructor Documentation
node_unary::node_unary (node operand)
Definition at line 234 of file node_impl.cpp.
 : node_impl(), operand_(operand)
 {}
Member Function Documentation
virtual double node_unary::evaluate_node () const override private pure virtual
Implements node_impl.
Implemented in node_negate.
double node_unary::evaluate_operand () const protected
Definition at line 244 of file node_impl.cpp.
References node::evaluate(), and operand().
Referenced by node_negate::evaluate_node().
 {
   return operand().evaluate();
 }
node node_unary::operand () const
Definition at line 238 of file node_impl.cpp.
References operand_.
Referenced by evaluate_operand(), and node_negate::print_node().
 {
   return operand_;
 }
virtual void node_unary::print_node (std::ostream & stream, int indent) const override private pure virtual
Implements node_impl.
Implemented in node_negate.
Member Data Documentation
node node_unary::operand_ private
Definition at line 125 of file node_impl.hpp.
Referenced by operand().
The documentation for this class was generated from the following files:
node_impl.hpp
node_impl.cpp