Calculator: node_multiply Class Reference
node_multiply Class Reference
#include <node_impl.hpp>
Public Member Functions
node_multiply (node left, node right)
Public Member Functions inherited from node_binary
node_binary (node left, node right)
node left () const
node right () const
Public Member Functions inherited from node_impl
node_impl ()
node_impl (node_impl &&)=default
node_impl & operator= (node_impl &&)=default
virtual ~node_impl ()
void print (std::ostream &stream, int indent) const
double evaluate () const
std::string to_string () const
identifier_list const & get_parameters () const
Private Member Functions
virtual void print_node (std::ostream &stream, int indent) const override
virtual double evaluate_node () const override
Additional Inherited Members
Protected Member Functions inherited from node_binary
double evaluate_left () const
double evaluate_right () const
Detailed Description
Multiplication.
Definition at line 173 of file node_impl.hpp.
Constructor & Destructor Documentation
node_multiply::node_multiply (node left, node right)
Definition at line 335 of file node_impl.cpp.
 : node_binary(left, right)
 {}
Member Function Documentation
double node_multiply::evaluate_node () const override private virtual
Implements node_binary.
Definition at line 347 of file node_impl.cpp.
References node_binary::evaluate_left(), and node_binary::evaluate_right().
 {
   return evaluate_left() * evaluate_right();
 }
void node_multiply::print_node (std::ostream & stream, int indent) const override private virtual
Implements node_binary.
Definition at line 339 of file node_impl.cpp.
References node_binary::left(), node::print(), and node_binary::right().
 {
   stream << std::setw(indent) << "" << "*\n";
   left().print(stream, indent + 2);
   right().print(stream, indent + 2);
 }
The documentation for this class was generated from the following files:
node_impl.hpp
node_impl.cpp