Calculator: variables.cpp File Reference
variables.cpp File Reference
#include <map>
#include "calc_error.hpp"
#include "node.hpp"
#include "variables.hpp"
Functions
bool find_symbol (std::string const &name, node &value)
node get_variable (std::string const &name)
void set_variable (std::string const &name, node value)
node get_function (std::string const &name)
void set_function (std::string const &name, node value)
Function Documentation
bool find_symbol (std::string const & name, node & value)
Definition at line 32 of file variables.cpp.
Referenced by get_function(), and get_variable().
 {
   for (auto iter(symbol_tables.rbegin()), end(symbol_tables.rend()); iter != end; ++iter) {
     symbol_table const& table{ **iter };
     symbol_table::const_iterator entry{ table.find(name) };
     if (entry != table.end()) {
       value = entry->second;
       return true;
     }
   }
   return false;
 }
node get_function (std::string const & name)
Get the definition of a function.
Parameters
name The function name
Returns
The definition of function named name
Exceptions
no_such_function if the function is not defined
Definition at line 61 of file variables.cpp.
References find_symbol().
Referenced by node_function_call::evaluate_node().
 {
   node result{};
   if (not find_symbol(name, result))
     throw no_such_function{name};
   else
     return result;
 }
node get_variable (std::string const & name)
Get the value of a variable.
Parameters
name The variable name
Returns
The value of variable name or node() if the variable is undefined.
Definition at line 45 of file variables.cpp.
References find_symbol().
Referenced by BOOST_AUTO_TEST_CASE(), and node_identifier::evaluate_node().
 {
   node result{};
   if (not find_symbol(name, result))
     return node();
   else if (result.get_parameters().empty())
     return result;
   else
     throw function_error{name, result.get_parameters().size(), 0};
 }
void set_function (std::string const & name, node definition)
Set the definition of a function.
Parameters
name The function name
definition The function definition
Definition at line 70 of file variables.cpp.
References set_variable().
Referenced by BOOST_AUTO_TEST_CASE(), and parser::get_statement().
 {
   set_variable(name, value);
 }
void set_variable (std::string const & name, node value)
Set the value of a variable.
Parameters
name The variable name
value The value. if the variable is already defined, changes its value.
Definition at line 56 of file variables.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and set_function().
 {
   variables[name] = value;
 }