386_OBJECTS= \
    $(_OBJ_DIR)\i386\ctrl2cap.res \
    $(_OBJ_DIR)\i386\ctrl2cap.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\ctrl2cap.res \
    $(_OBJ_DIR)\ia64\ctrl2cap.obj

PASS0_IA64_OBJECTS=

AMD64_OBJECTS= \
    $(_OBJ_DIR)\amd64\ctrl2cap.res \
    $(_OBJ_DIR)\amd64\ctrl2cap.obj

PASS0_AMD64_OBJECTS=

ARM_OBJECTS= \
    $(_OBJ_DIR)\arm\ctrl2cap.res \
    $(_OBJ_DIR)\arm\ctrl2cap.obj

PASS0_ARM_OBJECTS=

