######################################################################
# Automatically generated by qmake (2.01a) to 19. okt 13:22:05 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
