#ifndef _ioctl_h_
#define _ioctl_h_

#define IOCTL_SendFlagControl \
    CTL_CODE(FILE_DEVICE_UNKNOWN,0x200,METHOD_NEITHER,FILE_READ_ACCESS|FILE_WRITE_ACCESS)

#define IOCTL_SendEventProMon   \
    CTL_CODE(FILE_DEVICE_UNKNOWN,0x201,METHOD_NEITHER,FILE_READ_ACCESS|FILE_WRITE_ACCESS)

#define IOCTL_GetShareMemory    \
    CTL_CODE(FILE_DEVICE_UNKNOWN,0x202,METHOD_BUFFERED,FILE_READ_ACCESS|FILE_WRITE_ACCESS)

#define IOCTL_GetShareMemPointer \
    CTL_CODE(FILE_DEVICE_UNKNOWN,0x203,METHOD_BUFFERED,FILE_READ_ACCESS|FILE_WRITE_ACCESS)

#define IOCTL_Choose_T      \
    CTL_CODE(FILE_DEVICE_UNKNOWN,0x204,METHOD_NEITHER,FILE_READ_ACCESS|FILE_WRITE_ACCESS)

#define IOCTL_Choose_F      \
    CTL_CODE(FILE_DEVICE_UNKNOWN,0x205,METHOD_NEITHER,FILE_READ_ACCESS|FILE_WRITE_ACCESS)



#endif

