######################################################################
# Automatically generated by qmake (2.01a) ti 23. jan 19:14:04 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += spinboxtest.h
SOURCES += main.cpp spinboxtest.cpp
CONFIG += qtestlib console 
