######################################################################
# Automatically generated by qmake (2.01a) må 8. jan 09:16:30 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += sql 
CONFIG += console 
