######################################################################
# Automatically generated by qmake (2.01a) lö 9. dec 12:29:02 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
CONFIG += console 
