#include "stdafx.h"
#include "demo.h"
#include "resource.h"
#include "botany.h"


treedata Demo1Data[] = {
		{1, IDS_ORDER_SOLANALES,			DEMO_ORDER,
		 			              IMAGE_BOOKS_UNSELECTED},
		{2,     IDS_FAMILY_SOLANACEAE,			DEMO_FAMILY,
		 				       IMAGE_BOOK_UNSELECTED},
		{3,        IDS_GENUS_SOLANUM,			DEMO_GENUS,
		 			             IMAGE_FOLDER_UNSELECTED},
		{4,           IDS_SPECIES_DULCAMARA,		DEMO_SPECIES,
		 				     IMAGE_FLOWER_UNSELECTED},
		{5,               IDS_COMMON_BITTERSWEET,	DEMO_COMMON, 
		 							   0},
		{4,           IDS_SPECIES_NIGRUM,		DEMO_SPECIES,
		 				     IMAGE_FLOWER_UNSELECTED},
		{5,               IDS_COMMON_BLACK_NIGHTSHADE,	DEMO_COMMON, 
		 							   0},
		{4,           IDS_SPECIES_ROSTRATUM,		DEMO_SPECIES,
		 				     IMAGE_FLOWER_UNSELECTED},
		{5,               IDS_COMMON_BUFFALO_BERRY,	DEMO_COMMON, 
		 							   0},
		{3,        IDS_GENUS_DATURA,			DEMO_GENUS,
		 			             IMAGE_FOLDER_UNSELECTED},
		{4,           IDS_SPECIES_STRAMONIUM,		DEMO_SPECIES,
		 				     IMAGE_FLOWER_UNSELECTED},
		{5,               IDS_COMMON_JIMSON_WEED,	DEMO_COMMON, 
		 							   0},
		{4,           IDS_SPECIES_WRIGHTII,		DEMO_SPECIES,
		 				     IMAGE_FLOWER_UNSELECTED},
		{5,               IDS_COMMON_INDIAN_APPLE,	DEMO_COMMON, 
		 							   0},
		{2,     IDS_FAMILY_CONVOLVULACEAE,		DEMO_FAMILY,
		 				       IMAGE_BOOK_UNSELECTED},
		{3,        IDS_GENUS_CONVOLVULUS,		DEMO_GENUS,
		 			             IMAGE_FOLDER_UNSELECTED},
		{4,           IDS_SPECIES_ARVENSIS,		DEMO_SPECIES,
		 				     IMAGE_FLOWER_UNSELECTED},
		{5,               IDS_COMMON_FIELD_BINDWEED,	DEMO_COMMON, 
		 							   0},
		{2,     IDS_FAMILY_NICOTIANA,			DEMO_FAMILY,
		 				       IMAGE_BOOK_UNSELECTED},
		{3,        IDS_GENUS_NICOTIANA,			DEMO_GENUS,
		 			             IMAGE_FOLDER_UNSELECTED},
		{4,           IDS_SPECIES_ATTENUATA,		DEMO_SPECIES,
		 				     IMAGE_FLOWER_UNSELECTED},
		{5,               IDS_COMMON_COYOTE_TOBACCO,	DEMO_COMMON, 
		 							   0},
		{1, IDS_ORDER_GENTIANALES,			DEMO_ORDER,
		 			              IMAGE_BOOKS_UNSELECTED},
		{2,     IDS_FAMILY_GENTIANACEAE,		DEMO_FAMILY,
		 				       IMAGE_BOOK_UNSELECTED},
		{3,        IDS_GENUS_GENTIANA,			DEMO_GENUS,
		 			             IMAGE_FOLDER_UNSELECTED},
		{4,           IDS_SPECIES_PROSTRATA,		DEMO_SPECIES,
		 				     IMAGE_FLOWER_UNSELECTED},
		{5,               IDS_COMMON_MOSS_GENTIAN,	DEMO_COMMON, 
		 							   0},
		{4,           IDS_SPECIES_AFFINIS,		DEMO_SPECIES,
		 				     IMAGE_FLOWER_UNSELECTED},
		{5,               IDS_COMMON_ROCKY_MOUNTAIN_GENTIAN,
		 						DEMO_COMMON, 
		 							   0},
		{2,     IDS_FAMILY_ASCLEPEIADACEAE,		DEMO_FAMILY,
		 				       IMAGE_BOOK_UNSELECTED},
		{3,        IDS_GENUS_ASCLEPIAS,			DEMO_GENUS,
		 			             IMAGE_FOLDER_UNSELECTED},
		{4,            IDS_SPECIES_SPECIOSA,		DEMO_SPECIES,
		 				     IMAGE_FLOWER_UNSELECTED},
		{5,                IDS_COMMON_COMMON_MILKWEED,	DEMO_COMMON, 
		 							   0},
		{4,            IDS_SPECIES_TUBEROSA,		DEMO_SPECIES,
		 				     IMAGE_FLOWER_UNSELECTED},
		{5,                IDS_COMMON_BUTTERFLYWEED,	DEMO_COMMON, 
		 							   0},
		{1, IDS_ORDER_SCROPHULARIALES,			DEMO_ORDER,
		 			              IMAGE_BOOKS_UNSELECTED},
		{2,     IDS_FAMILY_BIGNONIACEAE,		DEMO_FAMILY,
		 				       IMAGE_BOOK_UNSELECTED},
		{3,        IDS_GENUS_CATALPA,			DEMO_GENUS,
		 			             IMAGE_FOLDER_UNSELECTED},
		{4,            IDS_SPECIES_BIGNONIOIDES,	DEMO_SPECIES,
		 				     IMAGE_FLOWER_UNSELECTED},
		{5,               IDS_COMMON_CATALPA,		DEMO_COMMON, 
		 							   0},
		{4,            IDS_SPECIES_SPECIOSA,		DEMO_SPECIES,
		 				     IMAGE_FLOWER_UNSELECTED},
		{5,               IDS_COMMON_WESTERN_CATALPA,	DEMO_COMMON, 
		 							   0},
		{2,     IDS_FAMILY_OLEACEAE,			DEMO_FAMILY,
		 				       IMAGE_BOOK_UNSELECTED},
		{3,        IDS_GENUS_SYRINGA,			DEMO_GENUS,
		 			             IMAGE_FOLDER_UNSELECTED},
		{4,            IDS_SPECIES_VULGARIS,		DEMO_SPECIES,
		 				     IMAGE_FLOWER_UNSELECTED},
		{5,                IDS_COMMON_COMMON_LILAC,	DEMO_COMMON, 
		 							   0},
		{4,            IDS_SPECIES_PERSICA,		DEMO_SPECIES,
		 				     IMAGE_FLOWER_UNSELECTED},
		{5,                IDS_COMMON_PERSIAN_LILAC,	DEMO_COMMON, 
		 							   0},
		{1, IDS_ORDER_LAMIALES,				DEMO_ORDER,
		 			              IMAGE_BOOKS_UNSELECTED},
		{2,     IDS_FAMILY_LAMIACEAE,			DEMO_FAMILY,
		 				       IMAGE_BOOK_UNSELECTED},
		{3,        IDS_GENUS_MENTHA,			DEMO_GENUS,
		 			             IMAGE_FOLDER_UNSELECTED},
		{4,            IDS_SPECIES_SPICATA,		DEMO_SPECIES,
		 				     IMAGE_FLOWER_UNSELECTED},
		{5,                IDS_COMMON_SPEARMINT,	DEMO_COMMON, 
		 							   0},
		{4,            IDS_SPECIES_PIPERITA,		DEMO_SPECIES,
		 				     IMAGE_FLOWER_UNSELECTED},
		{5,                IDS_COMMON_PEPPERMINT,	DEMO_COMMON, 
		 							   0},
		{3,        IDS_GENUS_SALVIA,			DEMO_GENUS,
		 			             IMAGE_FOLDER_UNSELECTED},
		{4,            IDS_SPECIES_SCLAREA,		DEMO_SPECIES,
		 				     IMAGE_FLOWER_UNSELECTED},
		{5,                IDS_COMMON_CLARY_SAGE,	DEMO_COMMON, 
		 							   0},
		{1, IDS_ORDER_DIPSACALES,			DEMO_ORDER,
		 			              IMAGE_BOOKS_UNSELECTED},
		{2,     IDS_FAMILY_CAPRIFOLIACEAE,		DEMO_FAMILY,
		 				       IMAGE_BOOK_UNSELECTED},
		{3,         IDS_GENUS_LONICERA,			DEMO_GENUS,
		 			             IMAGE_FOLDER_UNSELECTED},
		{4,             IDS_SPECIES_CAPRIFOLIUM,	DEMO_SPECIES,
		 				     IMAGE_FLOWER_UNSELECTED},
		{5,                 IDS_COMMON_HONEYSUCKLE,	DEMO_COMMON, 
		 							   0},
                {4,             IDS_SPECIES_JAPONICA,		DEMO_SPECIES,
		 				     IMAGE_FLOWER_UNSELECTED},
		{5,                 IDS_COMMON_JAPANESE_HONEYSUCKLE,
							        DEMO_COMMON, 
		 							   0},
		{3,         IDS_GENUS_LINNAEA,			DEMO_GENUS,
		 			             IMAGE_FOLDER_UNSELECTED},
		{4,             IDS_SPECIES_BOREALIS,		DEMO_SPECIES,
		 				     IMAGE_FLOWER_UNSELECTED},
		{5,                 IDS_COMMON_TWINFLOWER,	DEMO_COMMON, 
		 							   0},
		{3,         IDS_GENUS_SAMBUCUS,			DEMO_GENUS,
		 			             IMAGE_FOLDER_UNSELECTED},
		{4,             IDS_SPECIES_NIGRA,		DEMO_SPECIES,
		 				     IMAGE_FLOWER_UNSELECTED},
		{5,                 IDS_COMMON_ELDERBERRY,	DEMO_COMMON, 
		 							   0},
		{4,             IDS_SPECIES_RACEMOSA,		DEMO_SPECIES,
		 				     IMAGE_FLOWER_UNSELECTED},
		{5,                 IDS_COMMON_RED_ELDERBERRY,	DEMO_COMMON, 
		 							   0},
		{2,     IDS_FAMILY_DIPSACACEAE,			DEMO_FAMILY,
		 				       IMAGE_BOOK_UNSELECTED},
		{3,         IDS_GENUS_DIPSACUS,			DEMO_GENUS,
		 			             IMAGE_FOLDER_UNSELECTED},
		{4,             IDS_SPECIES_FULLONUM,		DEMO_SPECIES,
		 				     IMAGE_FLOWER_UNSELECTED},
		{5,                 IDS_COMMON_FULLERS_TEASEL,	DEMO_COMMON, 
		 							   0},
		{0,0} // EOT
       
			       };

